// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testingmocks

import (
	"context"

	"github.com/ipfs/go-block-format"
	"github.com/ipfs/go-cid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBlockstore creates a new instance of MockBlockstore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlockstore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlockstore {
	mock := &MockBlockstore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlockstore is an autogenerated mock type for the Blockstore type
type MockBlockstore struct {
	mock.Mock
}

type MockBlockstore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlockstore) EXPECT() *MockBlockstore_Expecter {
	return &MockBlockstore_Expecter{mock: &_m.Mock}
}

// AllKeysChan provides a mock function for the type MockBlockstore
func (_mock *MockBlockstore) AllKeysChan(ctx context.Context) (<-chan cid.Cid, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AllKeysChan")
	}

	var r0 <-chan cid.Cid
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan cid.Cid, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan cid.Cid); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan cid.Cid)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockstore_AllKeysChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllKeysChan'
type MockBlockstore_AllKeysChan_Call struct {
	*mock.Call
}

// AllKeysChan is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBlockstore_Expecter) AllKeysChan(ctx any) *MockBlockstore_AllKeysChan_Call {
	return &MockBlockstore_AllKeysChan_Call{Call: _e.mock.On("AllKeysChan", ctx)}
}

func (_c *MockBlockstore_AllKeysChan_Call) Run(run func(ctx context.Context)) *MockBlockstore_AllKeysChan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlockstore_AllKeysChan_Call) Return(cidCh <-chan cid.Cid, err error) *MockBlockstore_AllKeysChan_Call {
	_c.Call.Return(cidCh, err)
	return _c
}

func (_c *MockBlockstore_AllKeysChan_Call) RunAndReturn(run func(ctx context.Context) (<-chan cid.Cid, error)) *MockBlockstore_AllKeysChan_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBlock provides a mock function for the type MockBlockstore
func (_mock *MockBlockstore) DeleteBlock(context1 context.Context, cid1 cid.Cid) error {
	ret := _mock.Called(context1, cid1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) error); ok {
		r0 = returnFunc(context1, cid1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlockstore_DeleteBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBlock'
type MockBlockstore_DeleteBlock_Call struct {
	*mock.Call
}

// DeleteBlock is a helper method to define mock.On call
//   - context1 context.Context
//   - cid1 cid.Cid
func (_e *MockBlockstore_Expecter) DeleteBlock(context1 any, cid1 any) *MockBlockstore_DeleteBlock_Call {
	return &MockBlockstore_DeleteBlock_Call{Call: _e.mock.On("DeleteBlock", context1, cid1)}
}

func (_c *MockBlockstore_DeleteBlock_Call) Run(run func(context1 context.Context, cid1 cid.Cid)) *MockBlockstore_DeleteBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlockstore_DeleteBlock_Call) Return(err error) *MockBlockstore_DeleteBlock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlockstore_DeleteBlock_Call) RunAndReturn(run func(context1 context.Context, cid1 cid.Cid) error) *MockBlockstore_DeleteBlock_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockBlockstore
func (_mock *MockBlockstore) Get(context1 context.Context, cid1 cid.Cid) (blocks.Block, error) {
	ret := _mock.Called(context1, cid1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 blocks.Block
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) (blocks.Block, error)); ok {
		return returnFunc(context1, cid1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) blocks.Block); ok {
		r0 = returnFunc(context1, cid1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(blocks.Block)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cid.Cid) error); ok {
		r1 = returnFunc(context1, cid1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockstore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBlockstore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - cid1 cid.Cid
func (_e *MockBlockstore_Expecter) Get(context1 any, cid1 any) *MockBlockstore_Get_Call {
	return &MockBlockstore_Get_Call{Call: _e.mock.On("Get", context1, cid1)}
}

func (_c *MockBlockstore_Get_Call) Run(run func(context1 context.Context, cid1 cid.Cid)) *MockBlockstore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlockstore_Get_Call) Return(block blocks.Block, err error) *MockBlockstore_Get_Call {
	_c.Call.Return(block, err)
	return _c
}

func (_c *MockBlockstore_Get_Call) RunAndReturn(run func(context1 context.Context, cid1 cid.Cid) (blocks.Block, error)) *MockBlockstore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetSize provides a mock function for the type MockBlockstore
func (_mock *MockBlockstore) GetSize(context1 context.Context, cid1 cid.Cid) (int, error) {
	ret := _mock.Called(context1, cid1)

	if len(ret) == 0 {
		panic("no return value specified for GetSize")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) (int, error)); ok {
		return returnFunc(context1, cid1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) int); ok {
		r0 = returnFunc(context1, cid1)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cid.Cid) error); ok {
		r1 = returnFunc(context1, cid1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockstore_GetSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSize'
type MockBlockstore_GetSize_Call struct {
	*mock.Call
}

// GetSize is a helper method to define mock.On call
//   - context1 context.Context
//   - cid1 cid.Cid
func (_e *MockBlockstore_Expecter) GetSize(context1 any, cid1 any) *MockBlockstore_GetSize_Call {
	return &MockBlockstore_GetSize_Call{Call: _e.mock.On("GetSize", context1, cid1)}
}

func (_c *MockBlockstore_GetSize_Call) Run(run func(context1 context.Context, cid1 cid.Cid)) *MockBlockstore_GetSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlockstore_GetSize_Call) Return(n int, err error) *MockBlockstore_GetSize_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockBlockstore_GetSize_Call) RunAndReturn(run func(context1 context.Context, cid1 cid.Cid) (int, error)) *MockBlockstore_GetSize_Call {
	_c.Call.Return(run)
	return _c
}

// Has provides a mock function for the type MockBlockstore
func (_mock *MockBlockstore) Has(context1 context.Context, cid1 cid.Cid) (bool, error) {
	ret := _mock.Called(context1, cid1)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) (bool, error)); ok {
		return returnFunc(context1, cid1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) bool); ok {
		r0 = returnFunc(context1, cid1)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cid.Cid) error); ok {
		r1 = returnFunc(context1, cid1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockstore_Has_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Has'
type MockBlockstore_Has_Call struct {
	*mock.Call
}

// Has is a helper method to define mock.On call
//   - context1 context.Context
//   - cid1 cid.Cid
func (_e *MockBlockstore_Expecter) Has(context1 any, cid1 any) *MockBlockstore_Has_Call {
	return &MockBlockstore_Has_Call{Call: _e.mock.On("Has", context1, cid1)}
}

func (_c *MockBlockstore_Has_Call) Run(run func(context1 context.Context, cid1 cid.Cid)) *MockBlockstore_Has_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlockstore_Has_Call) Return(b bool, err error) *MockBlockstore_Has_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBlockstore_Has_Call) RunAndReturn(run func(context1 context.Context, cid1 cid.Cid) (bool, error)) *MockBlockstore_Has_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockBlockstore
func (_mock *MockBlockstore) Put(context1 context.Context, block blocks.Block) error {
	ret := _mock.Called(context1, block)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, blocks.Block) error); ok {
		r0 = returnFunc(context1, block)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlockstore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockBlockstore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - context1 context.Context
//   - block blocks.Block
func (_e *MockBlockstore_Expecter) Put(context1 any, block any) *MockBlockstore_Put_Call {
	return &MockBlockstore_Put_Call{Call: _e.mock.On("Put", context1, block)}
}

func (_c *MockBlockstore_Put_Call) Run(run func(context1 context.Context, block blocks.Block)) *MockBlockstore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 blocks.Block
		if args[1] != nil {
			arg1 = args[1].(blocks.Block)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlockstore_Put_Call) Return(err error) *MockBlockstore_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlockstore_Put_Call) RunAndReturn(run func(context1 context.Context, block blocks.Block) error) *MockBlockstore_Put_Call {
	_c.Call.Return(run)
	return _c
}

// PutMany provides a mock function for the type MockBlockstore
func (_mock *MockBlockstore) PutMany(context1 context.Context, blocks1 []blocks.Block) error {
	ret := _mock.Called(context1, blocks1)

	if len(ret) == 0 {
		panic("no return value specified for PutMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []blocks.Block) error); ok {
		r0 = returnFunc(context1, blocks1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlockstore_PutMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutMany'
type MockBlockstore_PutMany_Call struct {
	*mock.Call
}

// PutMany is a helper method to define mock.On call
//   - context1 context.Context
//   - blocks1 []blocks.Block
func (_e *MockBlockstore_Expecter) PutMany(context1 any, blocks1 any) *MockBlockstore_PutMany_Call {
	return &MockBlockstore_PutMany_Call{Call: _e.mock.On("PutMany", context1, blocks1)}
}

func (_c *MockBlockstore_PutMany_Call) Run(run func(context1 context.Context, blocks1 []blocks.Block)) *MockBlockstore_PutMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []blocks.Block
		if args[1] != nil {
			arg1 = args[1].([]blocks.Block)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlockstore_PutMany_Call) Return(err error) *MockBlockstore_PutMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlockstore_PutMany_Call) RunAndReturn(run func(context1 context.Context, blocks1 []blocks.Block) error) *MockBlockstore_PutMany_Call {
	_c.Call.Return(run)
	return _c
}
