[packages.ipfs-sdk]
versioned_files = ["go.mod"]
changelog = "CHANGELOG.md"

[packages.dnsname]
versioned_files = ["dnsname/go.mod"]
changelog = "dnsname/CHANGELOG.md"

[github]
owner = "LumeWeb"
repo = "ipfs-sdk"
