// Package pinning provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package pinning

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	AccessTokenScopes = "accessToken.Scopes"
)

// Defines values for PinStatusEnum.
const (
	Failed  PinStatusEnum = "failed"
	Pinned  PinStatusEnum = "pinned"
	Pinning PinStatusEnum = "pinning"
	Queued  PinStatusEnum = "queued"
)

// Valid indicates whether the value is a known member of the PinStatusEnum enum.
func (e PinStatusEnum) Valid() bool {
	switch e {
	case Failed:
		return true
	case Pinned:
		return true
	case Pinning:
		return true
	case Queued:
		return true
	default:
		return false
	}
}

// Defines values for TextMatchingStrategy.
const (
	Exact    TextMatchingStrategy = "exact"
	Iexact   TextMatchingStrategy = "iexact"
	Ipartial TextMatchingStrategy = "ipartial"
	Partial  TextMatchingStrategy = "partial"
)

// Valid indicates whether the value is a known member of the TextMatchingStrategy enum.
func (e TextMatchingStrategy) Valid() bool {
	switch e {
	case Exact:
		return true
	case Iexact:
		return true
	case Ipartial:
		return true
	case Partial:
		return true
	default:
		return false
	}
}

// Delegates List of multiaddrs designated by pinning service that will receive the pin data; see Provider Hints in the docs
type Delegates = []string

// Failure Response for a failed request
type Failure struct {
	Error struct {
		// Details Optional, longer description of the error; may include UUID of transaction for support, links to documentation etc
		Details *string `json:"details,omitempty"`

		// Reason Mandatory string identifying the type of error
		Reason string `json:"reason"`
	} `json:"error"`
}

// Origins Optional list of multiaddrs known to provide the data; see Provider Hints in the docs
type Origins = []string

// Pin Pin object
type Pin struct {
	// Cid Content Identifier (CID) to be pinned recursively
	Cid string `json:"cid"`

	// Meta Optional metadata for pin object
	Meta *PinMeta `json:"meta,omitempty"`

	// Name Optional name for pinned data; can be used for lookups later
	Name *string `json:"name,omitempty"`

	// Origins Optional list of multiaddrs known to provide the data; see Provider Hints in the docs
	Origins *Origins `json:"origins,omitempty"`
}

// PinMeta Optional metadata for pin object
type PinMeta map[string]string

// PinResults Response used for listing pin objects matching request
type PinResults struct {
	// Count The total number of pin objects that exist for passed query filters
	Count int32 `json:"count"`

	// Results An array of PinStatus results
	Results []PinStatus `json:"results"`
}

// PinStatus Pin object with status
type PinStatus struct {
	// Created Immutable timestamp indicating when a pin request entered a pinning service; can be used for filtering results and pagination
	Created time.Time `json:"created"`

	// Delegates List of multiaddrs designated by pinning service that will receive the pin data; see Provider Hints in the docs
	Delegates Delegates `json:"delegates"`

	// Info Optional info for PinStatus response
	Info *StatusInfo `json:"info,omitempty"`

	// Pin Pin object
	Pin Pin `json:"pin"`

	// Requestid Globally unique identifier of the pin request; can be used to check the status of ongoing pinning, or pin removal
	Requestid string `json:"requestid"`

	// PinStatusEnum Status a pin object can have at a pinning service
	PinStatusEnum PinStatusEnum `json:"status"`
}

// PinStatusEnum Status a pin object can have at a pinning service
type PinStatusEnum string

// StatusInfo Optional info for PinStatus response
type StatusInfo map[string]string

// TextMatchingStrategy Alternative text matching strategy
type TextMatchingStrategy string

// After defines model for after.
type After = time.Time

// Before defines model for before.
type Before = time.Time

// Cid defines model for cid.
type Cid = []string

// Limit defines model for limit.
type Limit = int32

// Match Alternative text matching strategy
type Match = TextMatchingStrategy

// Meta Optional metadata for pin object
type Meta = PinMeta

// Name defines model for name.
type Name = string

// Status defines model for status.
type Status = []PinStatusEnum

// BadRequest Response for a failed request
type BadRequest = Failure

// CustomServiceError Response for a failed request
type CustomServiceError = Failure

// InsufficientFunds Response for a failed request
type InsufficientFunds = Failure

// InternalServerError Response for a failed request
type InternalServerError = Failure

// NotFound Response for a failed request
type NotFound = Failure

// Unauthorized Response for a failed request
type Unauthorized = Failure

// GetPinsParams defines parameters for GetPins.
type GetPinsParams struct {
	// Cid Return pin objects responsible for pinning the specified CID(s); be aware that using longer hash functions introduces further constraints on the number of CIDs that will fit under the limit of 2000 characters per URL  in browser contexts
	Cid *Cid `form:"cid,omitempty" json:"cid,omitempty"`

	// Name Return pin objects with specified name (by default a case-sensitive, exact match)
	Name *Name `form:"name,omitempty" json:"name,omitempty"`

	// Match Customize the text matching strategy applied when the name filter is present; exact (the default) is a case-sensitive exact match, partial matches anywhere in the name, iexact and ipartial are case-insensitive versions of the exact and partial strategies
	Match *Match `form:"match,omitempty" json:"match,omitempty"`

	// Status Return pin objects for pins with the specified status (when missing, service should default to pinned only)
	Status *Status `form:"status,omitempty" json:"status,omitempty"`

	// Before Return results created (queued) before provided timestamp
	Before *Before `form:"before,omitempty" json:"before,omitempty"`

	// After Return results created (queued) after provided timestamp
	After *After `form:"after,omitempty" json:"after,omitempty"`

	// Limit Max records to return
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Meta Return pin objects that match specified metadata keys passed as a string representation of a JSON object; when implementing a client library, make sure the parameter is URL-encoded to ensure safe transport
	Meta *Meta `form:"meta,omitempty" json:"meta,omitempty"`
}

// AddPinJSONRequestBody defines body for AddPin for application/json ContentType.
type AddPinJSONRequestBody = Pin

// ReplacePinByRequestIdJSONRequestBody defines body for ReplacePinByRequestId for application/json ContentType.
type ReplacePinByRequestIdJSONRequestBody = Pin

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetPins request
	GetPins(ctx context.Context, params *GetPinsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddPinWithBody request with any body
	AddPinWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AddPin(ctx context.Context, body AddPinJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeletePinByRequestId request
	DeletePinByRequestId(ctx context.Context, requestid string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPinByRequestId request
	GetPinByRequestId(ctx context.Context, requestid string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReplacePinByRequestIdWithBody request with any body
	ReplacePinByRequestIdWithBody(ctx context.Context, requestid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ReplacePinByRequestId(ctx context.Context, requestid string, body ReplacePinByRequestIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetPins(ctx context.Context, params *GetPinsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPinsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddPinWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddPinRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddPin(ctx context.Context, body AddPinJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddPinRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeletePinByRequestId(ctx context.Context, requestid string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeletePinByRequestIdRequest(c.Server, requestid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPinByRequestId(ctx context.Context, requestid string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPinByRequestIdRequest(c.Server, requestid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReplacePinByRequestIdWithBody(ctx context.Context, requestid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplacePinByRequestIdRequestWithBody(c.Server, requestid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReplacePinByRequestId(ctx context.Context, requestid string, body ReplacePinByRequestIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplacePinByRequestIdRequest(c.Server, requestid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetPinsRequest generates requests for GetPins
func NewGetPinsRequest(server string, params *GetPinsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pins")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Cid != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "cid", *params.Cid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Name != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "name", *params.Name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Match != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "match", *params.Match, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Status != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "status", *params.Status, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Before != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "before", *params.Before, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date-time"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.After != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "after", *params.After, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date-time"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Meta != nil {

			if queryParamBuf, err := json.Marshal(*params.Meta); err != nil {
				return nil, err
			} else {
				queryValues.Add("meta", string(queryParamBuf))
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddPinRequest calls the generic AddPin builder with application/json body
func NewAddPinRequest(server string, body AddPinJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddPinRequestWithBody(server, "application/json", bodyReader)
}

// NewAddPinRequestWithBody generates requests for AddPin with any type of body
func NewAddPinRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pins")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeletePinByRequestIdRequest generates requests for DeletePinByRequestId
func NewDeletePinByRequestIdRequest(server string, requestid string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "requestid", requestid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pins/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPinByRequestIdRequest generates requests for GetPinByRequestId
func NewGetPinByRequestIdRequest(server string, requestid string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "requestid", requestid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pins/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewReplacePinByRequestIdRequest calls the generic ReplacePinByRequestId builder with application/json body
func NewReplacePinByRequestIdRequest(server string, requestid string, body ReplacePinByRequestIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewReplacePinByRequestIdRequestWithBody(server, requestid, "application/json", bodyReader)
}

// NewReplacePinByRequestIdRequestWithBody generates requests for ReplacePinByRequestId with any type of body
func NewReplacePinByRequestIdRequestWithBody(server string, requestid string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "requestid", requestid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pins/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetPinsWithResponse request
	GetPinsWithResponse(ctx context.Context, params *GetPinsParams, reqEditors ...RequestEditorFn) (*GetPinsResponse, error)

	// AddPinWithBodyWithResponse request with any body
	AddPinWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddPinResponse, error)

	AddPinWithResponse(ctx context.Context, body AddPinJSONRequestBody, reqEditors ...RequestEditorFn) (*AddPinResponse, error)

	// DeletePinByRequestIdWithResponse request
	DeletePinByRequestIdWithResponse(ctx context.Context, requestid string, reqEditors ...RequestEditorFn) (*DeletePinByRequestIdResponse, error)

	// GetPinByRequestIdWithResponse request
	GetPinByRequestIdWithResponse(ctx context.Context, requestid string, reqEditors ...RequestEditorFn) (*GetPinByRequestIdResponse, error)

	// ReplacePinByRequestIdWithBodyWithResponse request with any body
	ReplacePinByRequestIdWithBodyWithResponse(ctx context.Context, requestid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReplacePinByRequestIdResponse, error)

	ReplacePinByRequestIdWithResponse(ctx context.Context, requestid string, body ReplacePinByRequestIdJSONRequestBody, reqEditors ...RequestEditorFn) (*ReplacePinByRequestIdResponse, error)
}

type GetPinsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PinResults
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON404      *NotFound
	JSON409      *InsufficientFunds
	JSON4XX      *CustomServiceError
	JSON5XX      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetPinsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPinsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AddPinResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *PinStatus
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON404      *NotFound
	JSON409      *InsufficientFunds
	JSON4XX      *CustomServiceError
	JSON5XX      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r AddPinResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddPinResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeletePinByRequestIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON404      *NotFound
	JSON409      *InsufficientFunds
	JSON4XX      *CustomServiceError
	JSON5XX      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r DeletePinByRequestIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeletePinByRequestIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPinByRequestIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PinStatus
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON404      *NotFound
	JSON409      *InsufficientFunds
	JSON4XX      *CustomServiceError
	JSON5XX      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetPinByRequestIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPinByRequestIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ReplacePinByRequestIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *PinStatus
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON404      *NotFound
	JSON409      *InsufficientFunds
	JSON4XX      *CustomServiceError
	JSON5XX      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r ReplacePinByRequestIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReplacePinByRequestIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetPinsWithResponse request returning *GetPinsResponse
func (c *ClientWithResponses) GetPinsWithResponse(ctx context.Context, params *GetPinsParams, reqEditors ...RequestEditorFn) (*GetPinsResponse, error) {
	rsp, err := c.GetPins(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPinsResponse(rsp)
}

// AddPinWithBodyWithResponse request with arbitrary body returning *AddPinResponse
func (c *ClientWithResponses) AddPinWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddPinResponse, error) {
	rsp, err := c.AddPinWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddPinResponse(rsp)
}

func (c *ClientWithResponses) AddPinWithResponse(ctx context.Context, body AddPinJSONRequestBody, reqEditors ...RequestEditorFn) (*AddPinResponse, error) {
	rsp, err := c.AddPin(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddPinResponse(rsp)
}

// DeletePinByRequestIdWithResponse request returning *DeletePinByRequestIdResponse
func (c *ClientWithResponses) DeletePinByRequestIdWithResponse(ctx context.Context, requestid string, reqEditors ...RequestEditorFn) (*DeletePinByRequestIdResponse, error) {
	rsp, err := c.DeletePinByRequestId(ctx, requestid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeletePinByRequestIdResponse(rsp)
}

// GetPinByRequestIdWithResponse request returning *GetPinByRequestIdResponse
func (c *ClientWithResponses) GetPinByRequestIdWithResponse(ctx context.Context, requestid string, reqEditors ...RequestEditorFn) (*GetPinByRequestIdResponse, error) {
	rsp, err := c.GetPinByRequestId(ctx, requestid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPinByRequestIdResponse(rsp)
}

// ReplacePinByRequestIdWithBodyWithResponse request with arbitrary body returning *ReplacePinByRequestIdResponse
func (c *ClientWithResponses) ReplacePinByRequestIdWithBodyWithResponse(ctx context.Context, requestid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReplacePinByRequestIdResponse, error) {
	rsp, err := c.ReplacePinByRequestIdWithBody(ctx, requestid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReplacePinByRequestIdResponse(rsp)
}

func (c *ClientWithResponses) ReplacePinByRequestIdWithResponse(ctx context.Context, requestid string, body ReplacePinByRequestIdJSONRequestBody, reqEditors ...RequestEditorFn) (*ReplacePinByRequestIdResponse, error) {
	rsp, err := c.ReplacePinByRequestId(ctx, requestid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReplacePinByRequestIdResponse(rsp)
}

// ParseGetPinsResponse parses an HTTP response from a GetPinsWithResponse call
func ParseGetPinsResponse(rsp *http.Response) (*GetPinsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPinsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PinResults
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest InsufficientFunds
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest CustomServiceError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseAddPinResponse parses an HTTP response from a AddPinWithResponse call
func ParseAddPinResponse(rsp *http.Response) (*AddPinResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddPinResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest PinStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest InsufficientFunds
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest CustomServiceError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseDeletePinByRequestIdResponse parses an HTTP response from a DeletePinByRequestIdWithResponse call
func ParseDeletePinByRequestIdResponse(rsp *http.Response) (*DeletePinByRequestIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeletePinByRequestIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest InsufficientFunds
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest CustomServiceError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseGetPinByRequestIdResponse parses an HTTP response from a GetPinByRequestIdWithResponse call
func ParseGetPinByRequestIdResponse(rsp *http.Response) (*GetPinByRequestIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPinByRequestIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PinStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest InsufficientFunds
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest CustomServiceError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseReplacePinByRequestIdResponse parses an HTTP response from a ReplacePinByRequestIdWithResponse call
func ParseReplacePinByRequestIdResponse(rsp *http.Response) (*ReplacePinByRequestIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReplacePinByRequestIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest PinStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest InsufficientFunds
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest CustomServiceError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}
