// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package servicemocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/ipfs-sdk"
)

// NewMockDAGService creates a new instance of MockDAGService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDAGService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDAGService {
	mock := &MockDAGService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDAGService is an autogenerated mock type for the DAGService type
type MockDAGService struct {
	mock.Mock
}

type MockDAGService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDAGService) EXPECT() *MockDAGService_Expecter {
	return &MockDAGService_Expecter{mock: &_m.Mock}
}

// ResolveDAG provides a mock function for the type MockDAGService
func (_mock *MockDAGService) ResolveDAG(ctx context.Context, cid string) (*ipfs.DAGResponse, error) {
	ret := _mock.Called(ctx, cid)

	if len(ret) == 0 {
		panic("no return value specified for ResolveDAG")
	}

	var r0 *ipfs.DAGResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ipfs.DAGResponse, error)); ok {
		return returnFunc(ctx, cid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ipfs.DAGResponse); ok {
		r0 = returnFunc(ctx, cid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.DAGResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, cid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDAGService_ResolveDAG_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveDAG'
type MockDAGService_ResolveDAG_Call struct {
	*mock.Call
}

// ResolveDAG is a helper method to define mock.On call
//   - ctx context.Context
//   - cid string
func (_e *MockDAGService_Expecter) ResolveDAG(ctx any, cid any) *MockDAGService_ResolveDAG_Call {
	return &MockDAGService_ResolveDAG_Call{Call: _e.mock.On("ResolveDAG", ctx, cid)}
}

func (_c *MockDAGService_ResolveDAG_Call) Run(run func(ctx context.Context, cid string)) *MockDAGService_ResolveDAG_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDAGService_ResolveDAG_Call) Return(v *ipfs.DAGResponse, err error) *MockDAGService_ResolveDAG_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockDAGService_ResolveDAG_Call) RunAndReturn(run func(ctx context.Context, cid string) (*ipfs.DAGResponse, error)) *MockDAGService_ResolveDAG_Call {
	_c.Call.Return(run)
	return _c
}
