// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package servicemocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/ipfs-sdk"
)

// NewMockDNSService creates a new instance of MockDNSService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDNSService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDNSService {
	mock := &MockDNSService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDNSService is an autogenerated mock type for the DNSService type
type MockDNSService struct {
	mock.Mock
}

type MockDNSService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDNSService) EXPECT() *MockDNSService_Expecter {
	return &MockDNSService_Expecter{mock: &_m.Mock}
}

// BulkCreateRecords provides a mock function for the type MockDNSService
func (_mock *MockDNSService) BulkCreateRecords(ctx context.Context, zoneID string, records []ipfs.RecordRequest) ([]ipfs.RecordResponse, error) {
	ret := _mock.Called(ctx, zoneID, records)

	if len(ret) == 0 {
		panic("no return value specified for BulkCreateRecords")
	}

	var r0 []ipfs.RecordResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []ipfs.RecordRequest) ([]ipfs.RecordResponse, error)); ok {
		return returnFunc(ctx, zoneID, records)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []ipfs.RecordRequest) []ipfs.RecordResponse); ok {
		r0 = returnFunc(ctx, zoneID, records)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ipfs.RecordResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []ipfs.RecordRequest) error); ok {
		r1 = returnFunc(ctx, zoneID, records)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSService_BulkCreateRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkCreateRecords'
type MockDNSService_BulkCreateRecords_Call struct {
	*mock.Call
}

// BulkCreateRecords is a helper method to define mock.On call
//   - ctx context.Context
//   - zoneID string
//   - records []ipfs.RecordRequest
func (_e *MockDNSService_Expecter) BulkCreateRecords(ctx any, zoneID any, records any) *MockDNSService_BulkCreateRecords_Call {
	return &MockDNSService_BulkCreateRecords_Call{Call: _e.mock.On("BulkCreateRecords", ctx, zoneID, records)}
}

func (_c *MockDNSService_BulkCreateRecords_Call) Run(run func(ctx context.Context, zoneID string, records []ipfs.RecordRequest)) *MockDNSService_BulkCreateRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []ipfs.RecordRequest
		if args[2] != nil {
			arg2 = args[2].([]ipfs.RecordRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDNSService_BulkCreateRecords_Call) Return(vs []ipfs.RecordResponse, err error) *MockDNSService_BulkCreateRecords_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockDNSService_BulkCreateRecords_Call) RunAndReturn(run func(ctx context.Context, zoneID string, records []ipfs.RecordRequest) ([]ipfs.RecordResponse, error)) *MockDNSService_BulkCreateRecords_Call {
	_c.Call.Return(run)
	return _c
}

// BulkDeleteRecords provides a mock function for the type MockDNSService
func (_mock *MockDNSService) BulkDeleteRecords(ctx context.Context, zoneID string, identifiers []ipfs.RecordIdentifier) ([]ipfs.RecordResult, error) {
	ret := _mock.Called(ctx, zoneID, identifiers)

	if len(ret) == 0 {
		panic("no return value specified for BulkDeleteRecords")
	}

	var r0 []ipfs.RecordResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []ipfs.RecordIdentifier) ([]ipfs.RecordResult, error)); ok {
		return returnFunc(ctx, zoneID, identifiers)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []ipfs.RecordIdentifier) []ipfs.RecordResult); ok {
		r0 = returnFunc(ctx, zoneID, identifiers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ipfs.RecordResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []ipfs.RecordIdentifier) error); ok {
		r1 = returnFunc(ctx, zoneID, identifiers)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSService_BulkDeleteRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkDeleteRecords'
type MockDNSService_BulkDeleteRecords_Call struct {
	*mock.Call
}

// BulkDeleteRecords is a helper method to define mock.On call
//   - ctx context.Context
//   - zoneID string
//   - identifiers []ipfs.RecordIdentifier
func (_e *MockDNSService_Expecter) BulkDeleteRecords(ctx any, zoneID any, identifiers any) *MockDNSService_BulkDeleteRecords_Call {
	return &MockDNSService_BulkDeleteRecords_Call{Call: _e.mock.On("BulkDeleteRecords", ctx, zoneID, identifiers)}
}

func (_c *MockDNSService_BulkDeleteRecords_Call) Run(run func(ctx context.Context, zoneID string, identifiers []ipfs.RecordIdentifier)) *MockDNSService_BulkDeleteRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []ipfs.RecordIdentifier
		if args[2] != nil {
			arg2 = args[2].([]ipfs.RecordIdentifier)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDNSService_BulkDeleteRecords_Call) Return(vs []ipfs.RecordResult, err error) *MockDNSService_BulkDeleteRecords_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockDNSService_BulkDeleteRecords_Call) RunAndReturn(run func(ctx context.Context, zoneID string, identifiers []ipfs.RecordIdentifier) ([]ipfs.RecordResult, error)) *MockDNSService_BulkDeleteRecords_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRecord provides a mock function for the type MockDNSService
func (_mock *MockDNSService) CreateRecord(ctx context.Context, zoneID string, record ipfs.RecordRequest) (*ipfs.RecordResponse, error) {
	ret := _mock.Called(ctx, zoneID, record)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecord")
	}

	var r0 *ipfs.RecordResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ipfs.RecordRequest) (*ipfs.RecordResponse, error)); ok {
		return returnFunc(ctx, zoneID, record)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ipfs.RecordRequest) *ipfs.RecordResponse); ok {
		r0 = returnFunc(ctx, zoneID, record)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.RecordResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ipfs.RecordRequest) error); ok {
		r1 = returnFunc(ctx, zoneID, record)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSService_CreateRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRecord'
type MockDNSService_CreateRecord_Call struct {
	*mock.Call
}

// CreateRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - zoneID string
//   - record ipfs.RecordRequest
func (_e *MockDNSService_Expecter) CreateRecord(ctx any, zoneID any, record any) *MockDNSService_CreateRecord_Call {
	return &MockDNSService_CreateRecord_Call{Call: _e.mock.On("CreateRecord", ctx, zoneID, record)}
}

func (_c *MockDNSService_CreateRecord_Call) Run(run func(ctx context.Context, zoneID string, record ipfs.RecordRequest)) *MockDNSService_CreateRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 ipfs.RecordRequest
		if args[2] != nil {
			arg2 = args[2].(ipfs.RecordRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDNSService_CreateRecord_Call) Return(v *ipfs.RecordResponse, err error) *MockDNSService_CreateRecord_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockDNSService_CreateRecord_Call) RunAndReturn(run func(ctx context.Context, zoneID string, record ipfs.RecordRequest) (*ipfs.RecordResponse, error)) *MockDNSService_CreateRecord_Call {
	_c.Call.Return(run)
	return _c
}

// CreateZone provides a mock function for the type MockDNSService
func (_mock *MockDNSService) CreateZone(ctx context.Context, domain string, nameservers []string) (*ipfs.ZoneResponse, error) {
	ret := _mock.Called(ctx, domain, nameservers)

	if len(ret) == 0 {
		panic("no return value specified for CreateZone")
	}

	var r0 *ipfs.ZoneResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) (*ipfs.ZoneResponse, error)); ok {
		return returnFunc(ctx, domain, nameservers)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) *ipfs.ZoneResponse); ok {
		r0 = returnFunc(ctx, domain, nameservers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.ZoneResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, domain, nameservers)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSService_CreateZone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateZone'
type MockDNSService_CreateZone_Call struct {
	*mock.Call
}

// CreateZone is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - nameservers []string
func (_e *MockDNSService_Expecter) CreateZone(ctx any, domain any, nameservers any) *MockDNSService_CreateZone_Call {
	return &MockDNSService_CreateZone_Call{Call: _e.mock.On("CreateZone", ctx, domain, nameservers)}
}

func (_c *MockDNSService_CreateZone_Call) Run(run func(ctx context.Context, domain string, nameservers []string)) *MockDNSService_CreateZone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDNSService_CreateZone_Call) Return(v *ipfs.ZoneResponse, err error) *MockDNSService_CreateZone_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockDNSService_CreateZone_Call) RunAndReturn(run func(ctx context.Context, domain string, nameservers []string) (*ipfs.ZoneResponse, error)) *MockDNSService_CreateZone_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRecord provides a mock function for the type MockDNSService
func (_mock *MockDNSService) DeleteRecord(ctx context.Context, zoneID string, name string, recordType string, content ...string) error {
	// string
	_va := make([]any, len(content))
	for _i := range content {
		_va[_i] = content[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, zoneID, name, recordType)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRecord")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, ...string) error); ok {
		r0 = returnFunc(ctx, zoneID, name, recordType, content...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDNSService_DeleteRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRecord'
type MockDNSService_DeleteRecord_Call struct {
	*mock.Call
}

// DeleteRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - zoneID string
//   - name string
//   - recordType string
//   - content ...string
func (_e *MockDNSService_Expecter) DeleteRecord(ctx any, zoneID any, name any, recordType any, content ...any) *MockDNSService_DeleteRecord_Call {
	return &MockDNSService_DeleteRecord_Call{Call: _e.mock.On("DeleteRecord",
		append([]any{ctx, zoneID, name, recordType}, content...)...)}
}

func (_c *MockDNSService_DeleteRecord_Call) Run(run func(ctx context.Context, zoneID string, name string, recordType string, content ...string)) *MockDNSService_DeleteRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []string
		variadicArgs := make([]string, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockDNSService_DeleteRecord_Call) Return(err error) *MockDNSService_DeleteRecord_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDNSService_DeleteRecord_Call) RunAndReturn(run func(ctx context.Context, zoneID string, name string, recordType string, content ...string) error) *MockDNSService_DeleteRecord_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteZone provides a mock function for the type MockDNSService
func (_mock *MockDNSService) DeleteZone(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteZone")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDNSService_DeleteZone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteZone'
type MockDNSService_DeleteZone_Call struct {
	*mock.Call
}

// DeleteZone is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDNSService_Expecter) DeleteZone(ctx any, id any) *MockDNSService_DeleteZone_Call {
	return &MockDNSService_DeleteZone_Call{Call: _e.mock.On("DeleteZone", ctx, id)}
}

func (_c *MockDNSService_DeleteZone_Call) Run(run func(ctx context.Context, id string)) *MockDNSService_DeleteZone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDNSService_DeleteZone_Call) Return(err error) *MockDNSService_DeleteZone_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDNSService_DeleteZone_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockDNSService_DeleteZone_Call {
	_c.Call.Return(run)
	return _c
}

// GetCert provides a mock function for the type MockDNSService
func (_mock *MockDNSService) GetCert(ctx context.Context, domain string, namespace string) (*ipfs.CertGetResponse, error) {
	ret := _mock.Called(ctx, domain, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetCert")
	}

	var r0 *ipfs.CertGetResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*ipfs.CertGetResponse, error)); ok {
		return returnFunc(ctx, domain, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *ipfs.CertGetResponse); ok {
		r0 = returnFunc(ctx, domain, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.CertGetResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, domain, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSService_GetCert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCert'
type MockDNSService_GetCert_Call struct {
	*mock.Call
}

// GetCert is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - namespace string
func (_e *MockDNSService_Expecter) GetCert(ctx any, domain any, namespace any) *MockDNSService_GetCert_Call {
	return &MockDNSService_GetCert_Call{Call: _e.mock.On("GetCert", ctx, domain, namespace)}
}

func (_c *MockDNSService_GetCert_Call) Run(run func(ctx context.Context, domain string, namespace string)) *MockDNSService_GetCert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDNSService_GetCert_Call) Return(v *ipfs.CertGetResponse, err error) *MockDNSService_GetCert_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockDNSService_GetCert_Call) RunAndReturn(run func(ctx context.Context, domain string, namespace string) (*ipfs.CertGetResponse, error)) *MockDNSService_GetCert_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecord provides a mock function for the type MockDNSService
func (_mock *MockDNSService) GetRecord(ctx context.Context, zoneID string, name string, recordType string) (*ipfs.RecordResponse, error) {
	ret := _mock.Called(ctx, zoneID, name, recordType)

	if len(ret) == 0 {
		panic("no return value specified for GetRecord")
	}

	var r0 *ipfs.RecordResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*ipfs.RecordResponse, error)); ok {
		return returnFunc(ctx, zoneID, name, recordType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *ipfs.RecordResponse); ok {
		r0 = returnFunc(ctx, zoneID, name, recordType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.RecordResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, zoneID, name, recordType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSService_GetRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecord'
type MockDNSService_GetRecord_Call struct {
	*mock.Call
}

// GetRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - zoneID string
//   - name string
//   - recordType string
func (_e *MockDNSService_Expecter) GetRecord(ctx any, zoneID any, name any, recordType any) *MockDNSService_GetRecord_Call {
	return &MockDNSService_GetRecord_Call{Call: _e.mock.On("GetRecord", ctx, zoneID, name, recordType)}
}

func (_c *MockDNSService_GetRecord_Call) Run(run func(ctx context.Context, zoneID string, name string, recordType string)) *MockDNSService_GetRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDNSService_GetRecord_Call) Return(v *ipfs.RecordResponse, err error) *MockDNSService_GetRecord_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockDNSService_GetRecord_Call) RunAndReturn(run func(ctx context.Context, zoneID string, name string, recordType string) (*ipfs.RecordResponse, error)) *MockDNSService_GetRecord_Call {
	_c.Call.Return(run)
	return _c
}

// GetZone provides a mock function for the type MockDNSService
func (_mock *MockDNSService) GetZone(ctx context.Context, id string) (*ipfs.ZoneResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetZone")
	}

	var r0 *ipfs.ZoneResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ipfs.ZoneResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ipfs.ZoneResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.ZoneResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSService_GetZone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetZone'
type MockDNSService_GetZone_Call struct {
	*mock.Call
}

// GetZone is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDNSService_Expecter) GetZone(ctx any, id any) *MockDNSService_GetZone_Call {
	return &MockDNSService_GetZone_Call{Call: _e.mock.On("GetZone", ctx, id)}
}

func (_c *MockDNSService_GetZone_Call) Run(run func(ctx context.Context, id string)) *MockDNSService_GetZone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDNSService_GetZone_Call) Return(v *ipfs.ZoneResponse, err error) *MockDNSService_GetZone_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockDNSService_GetZone_Call) RunAndReturn(run func(ctx context.Context, id string) (*ipfs.ZoneResponse, error)) *MockDNSService_GetZone_Call {
	_c.Call.Return(run)
	return _c
}

// GetZoneStatus provides a mock function for the type MockDNSService
func (_mock *MockDNSService) GetZoneStatus(ctx context.Context, id string) (*ipfs.ZoneResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetZoneStatus")
	}

	var r0 *ipfs.ZoneResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ipfs.ZoneResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ipfs.ZoneResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.ZoneResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSService_GetZoneStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetZoneStatus'
type MockDNSService_GetZoneStatus_Call struct {
	*mock.Call
}

// GetZoneStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDNSService_Expecter) GetZoneStatus(ctx any, id any) *MockDNSService_GetZoneStatus_Call {
	return &MockDNSService_GetZoneStatus_Call{Call: _e.mock.On("GetZoneStatus", ctx, id)}
}

func (_c *MockDNSService_GetZoneStatus_Call) Run(run func(ctx context.Context, id string)) *MockDNSService_GetZoneStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDNSService_GetZoneStatus_Call) Return(v *ipfs.ZoneResponse, err error) *MockDNSService_GetZoneStatus_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockDNSService_GetZoneStatus_Call) RunAndReturn(run func(ctx context.Context, id string) (*ipfs.ZoneResponse, error)) *MockDNSService_GetZoneStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecords provides a mock function for the type MockDNSService
func (_mock *MockDNSService) ListRecords(ctx context.Context, zoneID string) ([]ipfs.RecordResponse, error) {
	ret := _mock.Called(ctx, zoneID)

	if len(ret) == 0 {
		panic("no return value specified for ListRecords")
	}

	var r0 []ipfs.RecordResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]ipfs.RecordResponse, error)); ok {
		return returnFunc(ctx, zoneID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []ipfs.RecordResponse); ok {
		r0 = returnFunc(ctx, zoneID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ipfs.RecordResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, zoneID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSService_ListRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecords'
type MockDNSService_ListRecords_Call struct {
	*mock.Call
}

// ListRecords is a helper method to define mock.On call
//   - ctx context.Context
//   - zoneID string
func (_e *MockDNSService_Expecter) ListRecords(ctx any, zoneID any) *MockDNSService_ListRecords_Call {
	return &MockDNSService_ListRecords_Call{Call: _e.mock.On("ListRecords", ctx, zoneID)}
}

func (_c *MockDNSService_ListRecords_Call) Run(run func(ctx context.Context, zoneID string)) *MockDNSService_ListRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDNSService_ListRecords_Call) Return(vs []ipfs.RecordResponse, err error) *MockDNSService_ListRecords_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockDNSService_ListRecords_Call) RunAndReturn(run func(ctx context.Context, zoneID string) ([]ipfs.RecordResponse, error)) *MockDNSService_ListRecords_Call {
	_c.Call.Return(run)
	return _c
}

// ListZones provides a mock function for the type MockDNSService
func (_mock *MockDNSService) ListZones(ctx context.Context) ([]ipfs.ZoneListResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListZones")
	}

	var r0 []ipfs.ZoneListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ipfs.ZoneListResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ipfs.ZoneListResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ipfs.ZoneListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSService_ListZones_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListZones'
type MockDNSService_ListZones_Call struct {
	*mock.Call
}

// ListZones is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDNSService_Expecter) ListZones(ctx any) *MockDNSService_ListZones_Call {
	return &MockDNSService_ListZones_Call{Call: _e.mock.On("ListZones", ctx)}
}

func (_c *MockDNSService_ListZones_Call) Run(run func(ctx context.Context)) *MockDNSService_ListZones_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDNSService_ListZones_Call) Return(vs []ipfs.ZoneListResponse, err error) *MockDNSService_ListZones_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockDNSService_ListZones_Call) RunAndReturn(run func(ctx context.Context) ([]ipfs.ZoneListResponse, error)) *MockDNSService_ListZones_Call {
	_c.Call.Return(run)
	return _c
}

// PushCert provides a mock function for the type MockDNSService
func (_mock *MockDNSService) PushCert(ctx context.Context, req ipfs.CertPushRequest) (*ipfs.CertPushResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PushCert")
	}

	var r0 *ipfs.CertPushResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ipfs.CertPushRequest) (*ipfs.CertPushResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ipfs.CertPushRequest) *ipfs.CertPushResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.CertPushResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ipfs.CertPushRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSService_PushCert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushCert'
type MockDNSService_PushCert_Call struct {
	*mock.Call
}

// PushCert is a helper method to define mock.On call
//   - ctx context.Context
//   - req ipfs.CertPushRequest
func (_e *MockDNSService_Expecter) PushCert(ctx any, req any) *MockDNSService_PushCert_Call {
	return &MockDNSService_PushCert_Call{Call: _e.mock.On("PushCert", ctx, req)}
}

func (_c *MockDNSService_PushCert_Call) Run(run func(ctx context.Context, req ipfs.CertPushRequest)) *MockDNSService_PushCert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ipfs.CertPushRequest
		if args[1] != nil {
			arg1 = args[1].(ipfs.CertPushRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDNSService_PushCert_Call) Return(v *ipfs.CertPushResponse, err error) *MockDNSService_PushCert_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockDNSService_PushCert_Call) RunAndReturn(run func(ctx context.Context, req ipfs.CertPushRequest) (*ipfs.CertPushResponse, error)) *MockDNSService_PushCert_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRecord provides a mock function for the type MockDNSService
func (_mock *MockDNSService) UpdateRecord(ctx context.Context, zoneID string, name string, recordType string, record ipfs.RecordRequest) (*ipfs.RecordResponse, error) {
	ret := _mock.Called(ctx, zoneID, name, recordType, record)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRecord")
	}

	var r0 *ipfs.RecordResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, ipfs.RecordRequest) (*ipfs.RecordResponse, error)); ok {
		return returnFunc(ctx, zoneID, name, recordType, record)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, ipfs.RecordRequest) *ipfs.RecordResponse); ok {
		r0 = returnFunc(ctx, zoneID, name, recordType, record)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.RecordResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, ipfs.RecordRequest) error); ok {
		r1 = returnFunc(ctx, zoneID, name, recordType, record)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSService_UpdateRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRecord'
type MockDNSService_UpdateRecord_Call struct {
	*mock.Call
}

// UpdateRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - zoneID string
//   - name string
//   - recordType string
//   - record ipfs.RecordRequest
func (_e *MockDNSService_Expecter) UpdateRecord(ctx any, zoneID any, name any, recordType any, record any) *MockDNSService_UpdateRecord_Call {
	return &MockDNSService_UpdateRecord_Call{Call: _e.mock.On("UpdateRecord", ctx, zoneID, name, recordType, record)}
}

func (_c *MockDNSService_UpdateRecord_Call) Run(run func(ctx context.Context, zoneID string, name string, recordType string, record ipfs.RecordRequest)) *MockDNSService_UpdateRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 ipfs.RecordRequest
		if args[4] != nil {
			arg4 = args[4].(ipfs.RecordRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockDNSService_UpdateRecord_Call) Return(v *ipfs.RecordResponse, err error) *MockDNSService_UpdateRecord_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockDNSService_UpdateRecord_Call) RunAndReturn(run func(ctx context.Context, zoneID string, name string, recordType string, record ipfs.RecordRequest) (*ipfs.RecordResponse, error)) *MockDNSService_UpdateRecord_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTLSA provides a mock function for the type MockDNSService
func (_mock *MockDNSService) UpdateTLSA(ctx context.Context, req ipfs.TLSAUpdateRequest) (*ipfs.CertPushResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTLSA")
	}

	var r0 *ipfs.CertPushResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ipfs.TLSAUpdateRequest) (*ipfs.CertPushResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ipfs.TLSAUpdateRequest) *ipfs.CertPushResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.CertPushResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ipfs.TLSAUpdateRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSService_UpdateTLSA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTLSA'
type MockDNSService_UpdateTLSA_Call struct {
	*mock.Call
}

// UpdateTLSA is a helper method to define mock.On call
//   - ctx context.Context
//   - req ipfs.TLSAUpdateRequest
func (_e *MockDNSService_Expecter) UpdateTLSA(ctx any, req any) *MockDNSService_UpdateTLSA_Call {
	return &MockDNSService_UpdateTLSA_Call{Call: _e.mock.On("UpdateTLSA", ctx, req)}
}

func (_c *MockDNSService_UpdateTLSA_Call) Run(run func(ctx context.Context, req ipfs.TLSAUpdateRequest)) *MockDNSService_UpdateTLSA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ipfs.TLSAUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(ipfs.TLSAUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDNSService_UpdateTLSA_Call) Return(v *ipfs.CertPushResponse, err error) *MockDNSService_UpdateTLSA_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockDNSService_UpdateTLSA_Call) RunAndReturn(run func(ctx context.Context, req ipfs.TLSAUpdateRequest) (*ipfs.CertPushResponse, error)) *MockDNSService_UpdateTLSA_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateZone provides a mock function for the type MockDNSService
func (_mock *MockDNSService) ValidateZone(ctx context.Context, id string) (*ipfs.ValidationResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ValidateZone")
	}

	var r0 *ipfs.ValidationResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ipfs.ValidationResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ipfs.ValidationResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.ValidationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSService_ValidateZone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateZone'
type MockDNSService_ValidateZone_Call struct {
	*mock.Call
}

// ValidateZone is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDNSService_Expecter) ValidateZone(ctx any, id any) *MockDNSService_ValidateZone_Call {
	return &MockDNSService_ValidateZone_Call{Call: _e.mock.On("ValidateZone", ctx, id)}
}

func (_c *MockDNSService_ValidateZone_Call) Run(run func(ctx context.Context, id string)) *MockDNSService_ValidateZone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDNSService_ValidateZone_Call) Return(v *ipfs.ValidationResponse, err error) *MockDNSService_ValidateZone_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockDNSService_ValidateZone_Call) RunAndReturn(run func(ctx context.Context, id string) (*ipfs.ValidationResponse, error)) *MockDNSService_ValidateZone_Call {
	_c.Call.Return(run)
	return _c
}
