// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package servicemocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/ipfs-sdk"
	"go.lumeweb.com/ipfs-sdk/internal/http"
)

// NewMockIPNSService creates a new instance of MockIPNSService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPNSService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPNSService {
	mock := &MockIPNSService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPNSService is an autogenerated mock type for the IPNSService type
type MockIPNSService struct {
	mock.Mock
}

type MockIPNSService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPNSService) EXPECT() *MockIPNSService_Expecter {
	return &MockIPNSService_Expecter{mock: &_m.Mock}
}

// CreateKey provides a mock function for the type MockIPNSService
func (_mock *MockIPNSService) CreateKey(ctx context.Context, name string, opts ...ipfs.CreateKeyOption) (*ipfs.IPNSKeyResponse, error) {
	// ipfs.CreateKeyOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateKey")
	}

	var r0 *ipfs.IPNSKeyResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...ipfs.CreateKeyOption) (*ipfs.IPNSKeyResponse, error)); ok {
		return returnFunc(ctx, name, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...ipfs.CreateKeyOption) *ipfs.IPNSKeyResponse); ok {
		r0 = returnFunc(ctx, name, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.IPNSKeyResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...ipfs.CreateKeyOption) error); ok {
		r1 = returnFunc(ctx, name, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSService_CreateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKey'
type MockIPNSService_CreateKey_Call struct {
	*mock.Call
}

// CreateKey is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts ...ipfs.CreateKeyOption
func (_e *MockIPNSService_Expecter) CreateKey(ctx interface{}, name interface{}, opts ...interface{}) *MockIPNSService_CreateKey_Call {
	return &MockIPNSService_CreateKey_Call{Call: _e.mock.On("CreateKey",
		append([]interface{}{ctx, name}, opts...)...)}
}

func (_c *MockIPNSService_CreateKey_Call) Run(run func(ctx context.Context, name string, opts ...ipfs.CreateKeyOption)) *MockIPNSService_CreateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []ipfs.CreateKeyOption
		variadicArgs := make([]ipfs.CreateKeyOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(ipfs.CreateKeyOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockIPNSService_CreateKey_Call) Return(v *ipfs.IPNSKeyResponse, err error) *MockIPNSService_CreateKey_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockIPNSService_CreateKey_Call) RunAndReturn(run func(ctx context.Context, name string, opts ...ipfs.CreateKeyOption) (*ipfs.IPNSKeyResponse, error)) *MockIPNSService_CreateKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteKey provides a mock function for the type MockIPNSService
func (_mock *MockIPNSService) DeleteKey(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPNSService_DeleteKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteKey'
type MockIPNSService_DeleteKey_Call struct {
	*mock.Call
}

// DeleteKey is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIPNSService_Expecter) DeleteKey(ctx interface{}, id interface{}) *MockIPNSService_DeleteKey_Call {
	return &MockIPNSService_DeleteKey_Call{Call: _e.mock.On("DeleteKey", ctx, id)}
}

func (_c *MockIPNSService_DeleteKey_Call) Run(run func(ctx context.Context, id string)) *MockIPNSService_DeleteKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPNSService_DeleteKey_Call) Return(err error) *MockIPNSService_DeleteKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPNSService_DeleteKey_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockIPNSService_DeleteKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetKey provides a mock function for the type MockIPNSService
func (_mock *MockIPNSService) GetKey(ctx context.Context, id string) (*ipfs.IPNSKeyResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetKey")
	}

	var r0 *ipfs.IPNSKeyResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ipfs.IPNSKeyResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ipfs.IPNSKeyResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.IPNSKeyResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSService_GetKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKey'
type MockIPNSService_GetKey_Call struct {
	*mock.Call
}

// GetKey is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIPNSService_Expecter) GetKey(ctx interface{}, id interface{}) *MockIPNSService_GetKey_Call {
	return &MockIPNSService_GetKey_Call{Call: _e.mock.On("GetKey", ctx, id)}
}

func (_c *MockIPNSService_GetKey_Call) Run(run func(ctx context.Context, id string)) *MockIPNSService_GetKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPNSService_GetKey_Call) Return(v *ipfs.IPNSKeyResponse, err error) *MockIPNSService_GetKey_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockIPNSService_GetKey_Call) RunAndReturn(run func(ctx context.Context, id string) (*ipfs.IPNSKeyResponse, error)) *MockIPNSService_GetKey_Call {
	_c.Call.Return(run)
	return _c
}

// ListKeys provides a mock function for the type MockIPNSService
func (_mock *MockIPNSService) ListKeys(ctx context.Context) ([]ipfs.IPNSKeyResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListKeys")
	}

	var r0 []ipfs.IPNSKeyResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ipfs.IPNSKeyResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ipfs.IPNSKeyResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ipfs.IPNSKeyResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSService_ListKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListKeys'
type MockIPNSService_ListKeys_Call struct {
	*mock.Call
}

// ListKeys is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIPNSService_Expecter) ListKeys(ctx interface{}) *MockIPNSService_ListKeys_Call {
	return &MockIPNSService_ListKeys_Call{Call: _e.mock.On("ListKeys", ctx)}
}

func (_c *MockIPNSService_ListKeys_Call) Run(run func(ctx context.Context)) *MockIPNSService_ListKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPNSService_ListKeys_Call) Return(vs []ipfs.IPNSKeyResponse, err error) *MockIPNSService_ListKeys_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockIPNSService_ListKeys_Call) RunAndReturn(run func(ctx context.Context) ([]ipfs.IPNSKeyResponse, error)) *MockIPNSService_ListKeys_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type MockIPNSService
func (_mock *MockIPNSService) Publish(ctx context.Context, keyID int, cid string, opts ...ipfs.PublishOption) (*ipfs.IPNSPublishResponse, error) {
	// ipfs.PublishOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, keyID, cid)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 *ipfs.IPNSPublishResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, ...ipfs.PublishOption) (*ipfs.IPNSPublishResponse, error)); ok {
		return returnFunc(ctx, keyID, cid, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, ...ipfs.PublishOption) *ipfs.IPNSPublishResponse); ok {
		r0 = returnFunc(ctx, keyID, cid, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.IPNSPublishResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string, ...ipfs.PublishOption) error); ok {
		r1 = returnFunc(ctx, keyID, cid, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSService_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockIPNSService_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID int
//   - cid string
//   - opts ...ipfs.PublishOption
func (_e *MockIPNSService_Expecter) Publish(ctx interface{}, keyID interface{}, cid interface{}, opts ...interface{}) *MockIPNSService_Publish_Call {
	return &MockIPNSService_Publish_Call{Call: _e.mock.On("Publish",
		append([]interface{}{ctx, keyID, cid}, opts...)...)}
}

func (_c *MockIPNSService_Publish_Call) Run(run func(ctx context.Context, keyID int, cid string, opts ...ipfs.PublishOption)) *MockIPNSService_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []ipfs.PublishOption
		variadicArgs := make([]ipfs.PublishOption, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(ipfs.PublishOption)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockIPNSService_Publish_Call) Return(v *ipfs.IPNSPublishResponse, err error) *MockIPNSService_Publish_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockIPNSService_Publish_Call) RunAndReturn(run func(ctx context.Context, keyID int, cid string, opts ...ipfs.PublishOption) (*ipfs.IPNSPublishResponse, error)) *MockIPNSService_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Republish provides a mock function for the type MockIPNSService
func (_mock *MockIPNSService) Republish(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Republish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPNSService_Republish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Republish'
type MockIPNSService_Republish_Call struct {
	*mock.Call
}

// Republish is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIPNSService_Expecter) Republish(ctx interface{}) *MockIPNSService_Republish_Call {
	return &MockIPNSService_Republish_Call{Call: _e.mock.On("Republish", ctx)}
}

func (_c *MockIPNSService_Republish_Call) Run(run func(ctx context.Context)) *MockIPNSService_Republish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPNSService_Republish_Call) Return(err error) *MockIPNSService_Republish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPNSService_Republish_Call) RunAndReturn(run func(ctx context.Context) error) *MockIPNSService_Republish_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function for the type MockIPNSService
func (_mock *MockIPNSService) Resolve(ctx context.Context, name string) (*ipfs.IPNSResolveResponse, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 *ipfs.IPNSResolveResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ipfs.IPNSResolveResponse, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ipfs.IPNSResolveResponse); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.IPNSResolveResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSService_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockIPNSService_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockIPNSService_Expecter) Resolve(ctx interface{}, name interface{}) *MockIPNSService_Resolve_Call {
	return &MockIPNSService_Resolve_Call{Call: _e.mock.On("Resolve", ctx, name)}
}

func (_c *MockIPNSService_Resolve_Call) Run(run func(ctx context.Context, name string)) *MockIPNSService_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPNSService_Resolve_Call) Return(v *ipfs.IPNSResolveResponse, err error) *MockIPNSService_Resolve_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockIPNSService_Resolve_Call) RunAndReturn(run func(ctx context.Context, name string) (*ipfs.IPNSResolveResponse, error)) *MockIPNSService_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForIPNSResolution provides a mock function for the type MockIPNSService
func (_mock *MockIPNSService) WaitForIPNSResolution(ctx context.Context, name string, expectedCID string, opts ...http.PollOption) (*ipfs.IPNSResolveResponse, error) {
	// http.PollOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name, expectedCID)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WaitForIPNSResolution")
	}

	var r0 *ipfs.IPNSResolveResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...http.PollOption) (*ipfs.IPNSResolveResponse, error)); ok {
		return returnFunc(ctx, name, expectedCID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...http.PollOption) *ipfs.IPNSResolveResponse); ok {
		r0 = returnFunc(ctx, name, expectedCID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.IPNSResolveResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, ...http.PollOption) error); ok {
		r1 = returnFunc(ctx, name, expectedCID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSService_WaitForIPNSResolution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForIPNSResolution'
type MockIPNSService_WaitForIPNSResolution_Call struct {
	*mock.Call
}

// WaitForIPNSResolution is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - expectedCID string
//   - opts ...http.PollOption
func (_e *MockIPNSService_Expecter) WaitForIPNSResolution(ctx interface{}, name interface{}, expectedCID interface{}, opts ...interface{}) *MockIPNSService_WaitForIPNSResolution_Call {
	return &MockIPNSService_WaitForIPNSResolution_Call{Call: _e.mock.On("WaitForIPNSResolution",
		append([]interface{}{ctx, name, expectedCID}, opts...)...)}
}

func (_c *MockIPNSService_WaitForIPNSResolution_Call) Run(run func(ctx context.Context, name string, expectedCID string, opts ...http.PollOption)) *MockIPNSService_WaitForIPNSResolution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []http.PollOption
		variadicArgs := make([]http.PollOption, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.PollOption)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockIPNSService_WaitForIPNSResolution_Call) Return(v *ipfs.IPNSResolveResponse, err error) *MockIPNSService_WaitForIPNSResolution_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockIPNSService_WaitForIPNSResolution_Call) RunAndReturn(run func(ctx context.Context, name string, expectedCID string, opts ...http.PollOption) (*ipfs.IPNSResolveResponse, error)) *MockIPNSService_WaitForIPNSResolution_Call {
	_c.Call.Return(run)
	return _c
}
