// Code generated by mockery v2.53.6. DO NOT EDIT.

package servicemocks

import (
	context "context"

	client "go.lumeweb.com/ipfs-sdk/internal/client"

	mock "github.com/stretchr/testify/mock"
)

// MockMetaService is an autogenerated mock type for the MetaService type
type MockMetaService struct {
	mock.Mock
}

type MockMetaService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetaService) EXPECT() *MockMetaService_Expecter {
	return &MockMetaService_Expecter{mock: &_m.Mock}
}

// ExportDAG provides a mock function with given fields: ctx, cid
func (_m *MockMetaService) ExportDAG(ctx context.Context, cid string) (*client.DAGExportResponse, error) {
	ret := _m.Called(ctx, cid)

	if len(ret) == 0 {
		panic("no return value specified for ExportDAG")
	}

	var r0 *client.DAGExportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.DAGExportResponse, error)); ok {
		return rf(ctx, cid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.DAGExportResponse); ok {
		r0 = rf(ctx, cid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.DAGExportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMetaService_ExportDAG_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportDAG'
type MockMetaService_ExportDAG_Call struct {
	*mock.Call
}

// ExportDAG is a helper method to define mock.On call
//   - ctx context.Context
//   - cid string
func (_e *MockMetaService_Expecter) ExportDAG(ctx interface{}, cid interface{}) *MockMetaService_ExportDAG_Call {
	return &MockMetaService_ExportDAG_Call{Call: _e.mock.On("ExportDAG", ctx, cid)}
}

func (_c *MockMetaService_ExportDAG_Call) Run(run func(ctx context.Context, cid string)) *MockMetaService_ExportDAG_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMetaService_ExportDAG_Call) Return(_a0 *client.DAGExportResponse, _a1 error) *MockMetaService_ExportDAG_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMetaService_ExportDAG_Call) RunAndReturn(run func(context.Context, string) (*client.DAGExportResponse, error)) *MockMetaService_ExportDAG_Call {
	_c.Call.Return(run)
	return _c
}

// ExportSiaObject provides a mock function with given fields: ctx, cid
func (_m *MockMetaService) ExportSiaObject(ctx context.Context, cid string) (*client.CIDExportResponse, error) {
	ret := _m.Called(ctx, cid)

	if len(ret) == 0 {
		panic("no return value specified for ExportSiaObject")
	}

	var r0 *client.CIDExportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.CIDExportResponse, error)); ok {
		return rf(ctx, cid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.CIDExportResponse); ok {
		r0 = rf(ctx, cid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.CIDExportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMetaService_ExportSiaObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportSiaObject'
type MockMetaService_ExportSiaObject_Call struct {
	*mock.Call
}

// ExportSiaObject is a helper method to define mock.On call
//   - ctx context.Context
//   - cid string
func (_e *MockMetaService_Expecter) ExportSiaObject(ctx interface{}, cid interface{}) *MockMetaService_ExportSiaObject_Call {
	return &MockMetaService_ExportSiaObject_Call{Call: _e.mock.On("ExportSiaObject", ctx, cid)}
}

func (_c *MockMetaService_ExportSiaObject_Call) Run(run func(ctx context.Context, cid string)) *MockMetaService_ExportSiaObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMetaService_ExportSiaObject_Call) Return(_a0 *client.CIDExportResponse, _a1 error) *MockMetaService_ExportSiaObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMetaService_ExportSiaObject_Call) RunAndReturn(run func(context.Context, string) (*client.CIDExportResponse, error)) *MockMetaService_ExportSiaObject_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetaService creates a new instance of MockMetaService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetaService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetaService {
	mock := &MockMetaService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
