// Code generated by mockery v2.53.6. DO NOT EDIT.

package servicemocks

import (
	context "context"

	cid "github.com/ipfs/go-cid"

	ipfs "go.lumeweb.com/ipfs-sdk"

	mock "github.com/stretchr/testify/mock"

	pinning "go.lumeweb.com/ipfs-sdk/internal/pinning"
)

// MockPinningService is an autogenerated mock type for the PinningService type
type MockPinningService struct {
	mock.Mock
}

type MockPinningService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPinningService) EXPECT() *MockPinningService_Expecter {
	return &MockPinningService_Expecter{mock: &_m.Mock}
}

// AddPin provides a mock function with given fields: ctx, _a1, opts
func (_m *MockPinningService) AddPin(ctx context.Context, _a1 cid.Cid, opts ...ipfs.AddOption) (*pinning.PinStatus, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddPin")
	}

	var r0 *pinning.PinStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, cid.Cid, ...ipfs.AddOption) (*pinning.PinStatus, error)); ok {
		return rf(ctx, _a1, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, cid.Cid, ...ipfs.AddOption) *pinning.PinStatus); ok {
		r0 = rf(ctx, _a1, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pinning.PinStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, cid.Cid, ...ipfs.AddOption) error); ok {
		r1 = rf(ctx, _a1, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPinningService_AddPin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPin'
type MockPinningService_AddPin_Call struct {
	*mock.Call
}

// AddPin is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 cid.Cid
//   - opts ...ipfs.AddOption
func (_e *MockPinningService_Expecter) AddPin(ctx interface{}, _a1 interface{}, opts ...interface{}) *MockPinningService_AddPin_Call {
	return &MockPinningService_AddPin_Call{Call: _e.mock.On("AddPin",
		append([]interface{}{ctx, _a1}, opts...)...)}
}

func (_c *MockPinningService_AddPin_Call) Run(run func(ctx context.Context, _a1 cid.Cid, opts ...ipfs.AddOption)) *MockPinningService_AddPin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]ipfs.AddOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(ipfs.AddOption)
			}
		}
		run(args[0].(context.Context), args[1].(cid.Cid), variadicArgs...)
	})
	return _c
}

func (_c *MockPinningService_AddPin_Call) Return(_a0 *pinning.PinStatus, _a1 error) *MockPinningService_AddPin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPinningService_AddPin_Call) RunAndReturn(run func(context.Context, cid.Cid, ...ipfs.AddOption) (*pinning.PinStatus, error)) *MockPinningService_AddPin_Call {
	_c.Call.Return(run)
	return _c
}

// GetPin provides a mock function with given fields: ctx, requestID
func (_m *MockPinningService) GetPin(ctx context.Context, requestID string) (*pinning.PinStatus, error) {
	ret := _m.Called(ctx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for GetPin")
	}

	var r0 *pinning.PinStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*pinning.PinStatus, error)); ok {
		return rf(ctx, requestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *pinning.PinStatus); ok {
		r0 = rf(ctx, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pinning.PinStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPinningService_GetPin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPin'
type MockPinningService_GetPin_Call struct {
	*mock.Call
}

// GetPin is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID string
func (_e *MockPinningService_Expecter) GetPin(ctx interface{}, requestID interface{}) *MockPinningService_GetPin_Call {
	return &MockPinningService_GetPin_Call{Call: _e.mock.On("GetPin", ctx, requestID)}
}

func (_c *MockPinningService_GetPin_Call) Run(run func(ctx context.Context, requestID string)) *MockPinningService_GetPin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPinningService_GetPin_Call) Return(_a0 *pinning.PinStatus, _a1 error) *MockPinningService_GetPin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPinningService_GetPin_Call) RunAndReturn(run func(context.Context, string) (*pinning.PinStatus, error)) *MockPinningService_GetPin_Call {
	_c.Call.Return(run)
	return _c
}

// ListPins provides a mock function with given fields: ctx, opts
func (_m *MockPinningService) ListPins(ctx context.Context, opts ...ipfs.ListOption) ([]pinning.PinStatus, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListPins")
	}

	var r0 []pinning.PinStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...ipfs.ListOption) ([]pinning.PinStatus, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...ipfs.ListOption) []pinning.PinStatus); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pinning.PinStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...ipfs.ListOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPinningService_ListPins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPins'
type MockPinningService_ListPins_Call struct {
	*mock.Call
}

// ListPins is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...ipfs.ListOption
func (_e *MockPinningService_Expecter) ListPins(ctx interface{}, opts ...interface{}) *MockPinningService_ListPins_Call {
	return &MockPinningService_ListPins_Call{Call: _e.mock.On("ListPins",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockPinningService_ListPins_Call) Run(run func(ctx context.Context, opts ...ipfs.ListOption)) *MockPinningService_ListPins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]ipfs.ListOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(ipfs.ListOption)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockPinningService_ListPins_Call) Return(_a0 []pinning.PinStatus, _a1 error) *MockPinningService_ListPins_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPinningService_ListPins_Call) RunAndReturn(run func(context.Context, ...ipfs.ListOption) ([]pinning.PinStatus, error)) *MockPinningService_ListPins_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePin provides a mock function with given fields: ctx, requestID
func (_m *MockPinningService) RemovePin(ctx context.Context, requestID string) error {
	ret := _m.Called(ctx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for RemovePin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, requestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPinningService_RemovePin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePin'
type MockPinningService_RemovePin_Call struct {
	*mock.Call
}

// RemovePin is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID string
func (_e *MockPinningService_Expecter) RemovePin(ctx interface{}, requestID interface{}) *MockPinningService_RemovePin_Call {
	return &MockPinningService_RemovePin_Call{Call: _e.mock.On("RemovePin", ctx, requestID)}
}

func (_c *MockPinningService_RemovePin_Call) Run(run func(ctx context.Context, requestID string)) *MockPinningService_RemovePin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPinningService_RemovePin_Call) Return(_a0 error) *MockPinningService_RemovePin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPinningService_RemovePin_Call) RunAndReturn(run func(context.Context, string) error) *MockPinningService_RemovePin_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPinningService creates a new instance of MockPinningService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPinningService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPinningService {
	mock := &MockPinningService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
