// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package servicemocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/ipfs-sdk"
)

// NewMockWebsitesService creates a new instance of MockWebsitesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebsitesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebsitesService {
	mock := &MockWebsitesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWebsitesService is an autogenerated mock type for the WebsitesService type
type MockWebsitesService struct {
	mock.Mock
}

type MockWebsitesService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebsitesService) EXPECT() *MockWebsitesService_Expecter {
	return &MockWebsitesService_Expecter{mock: &_m.Mock}
}

// BindDomain provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) BindDomain(ctx context.Context, websiteID string, req ipfs.DomainRequest) (*ipfs.DomainResponse, error) {
	ret := _mock.Called(ctx, websiteID, req)

	if len(ret) == 0 {
		panic("no return value specified for BindDomain")
	}

	var r0 *ipfs.DomainResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ipfs.DomainRequest) (*ipfs.DomainResponse, error)); ok {
		return returnFunc(ctx, websiteID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ipfs.DomainRequest) *ipfs.DomainResponse); ok {
		r0 = returnFunc(ctx, websiteID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.DomainResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ipfs.DomainRequest) error); ok {
		r1 = returnFunc(ctx, websiteID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsitesService_BindDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindDomain'
type MockWebsitesService_BindDomain_Call struct {
	*mock.Call
}

// BindDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - websiteID string
//   - req ipfs.DomainRequest
func (_e *MockWebsitesService_Expecter) BindDomain(ctx any, websiteID any, req any) *MockWebsitesService_BindDomain_Call {
	return &MockWebsitesService_BindDomain_Call{Call: _e.mock.On("BindDomain", ctx, websiteID, req)}
}

func (_c *MockWebsitesService_BindDomain_Call) Run(run func(ctx context.Context, websiteID string, req ipfs.DomainRequest)) *MockWebsitesService_BindDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 ipfs.DomainRequest
		if args[2] != nil {
			arg2 = args[2].(ipfs.DomainRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWebsitesService_BindDomain_Call) Return(v *ipfs.DomainResponse, err error) *MockWebsitesService_BindDomain_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockWebsitesService_BindDomain_Call) RunAndReturn(run func(ctx context.Context, websiteID string, req ipfs.DomainRequest) (*ipfs.DomainResponse, error)) *MockWebsitesService_BindDomain_Call {
	_c.Call.Return(run)
	return _c
}

// CheckPlatformDomainAvailability provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) CheckPlatformDomainAvailability(ctx context.Context, label string) (*ipfs.PlatformAvailabilityResponse, error) {
	ret := _mock.Called(ctx, label)

	if len(ret) == 0 {
		panic("no return value specified for CheckPlatformDomainAvailability")
	}

	var r0 *ipfs.PlatformAvailabilityResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ipfs.PlatformAvailabilityResponse, error)); ok {
		return returnFunc(ctx, label)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ipfs.PlatformAvailabilityResponse); ok {
		r0 = returnFunc(ctx, label)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.PlatformAvailabilityResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, label)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsitesService_CheckPlatformDomainAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPlatformDomainAvailability'
type MockWebsitesService_CheckPlatformDomainAvailability_Call struct {
	*mock.Call
}

// CheckPlatformDomainAvailability is a helper method to define mock.On call
//   - ctx context.Context
//   - label string
func (_e *MockWebsitesService_Expecter) CheckPlatformDomainAvailability(ctx any, label any) *MockWebsitesService_CheckPlatformDomainAvailability_Call {
	return &MockWebsitesService_CheckPlatformDomainAvailability_Call{Call: _e.mock.On("CheckPlatformDomainAvailability", ctx, label)}
}

func (_c *MockWebsitesService_CheckPlatformDomainAvailability_Call) Run(run func(ctx context.Context, label string)) *MockWebsitesService_CheckPlatformDomainAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebsitesService_CheckPlatformDomainAvailability_Call) Return(v *ipfs.PlatformAvailabilityResponse, err error) *MockWebsitesService_CheckPlatformDomainAvailability_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockWebsitesService_CheckPlatformDomainAvailability_Call) RunAndReturn(run func(ctx context.Context, label string) (*ipfs.PlatformAvailabilityResponse, error)) *MockWebsitesService_CheckPlatformDomainAvailability_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) Create(ctx context.Context, domain string, targetHash string, targetType string) (*ipfs.WebsiteResponse, error) {
	ret := _mock.Called(ctx, domain, targetHash, targetType)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *ipfs.WebsiteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*ipfs.WebsiteResponse, error)); ok {
		return returnFunc(ctx, domain, targetHash, targetType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *ipfs.WebsiteResponse); ok {
		r0 = returnFunc(ctx, domain, targetHash, targetType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.WebsiteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, domain, targetHash, targetType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsitesService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWebsitesService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - targetHash string
//   - targetType string
func (_e *MockWebsitesService_Expecter) Create(ctx any, domain any, targetHash any, targetType any) *MockWebsitesService_Create_Call {
	return &MockWebsitesService_Create_Call{Call: _e.mock.On("Create", ctx, domain, targetHash, targetType)}
}

func (_c *MockWebsitesService_Create_Call) Run(run func(ctx context.Context, domain string, targetHash string, targetType string)) *MockWebsitesService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWebsitesService_Create_Call) Return(v *ipfs.WebsiteResponse, err error) *MockWebsitesService_Create_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockWebsitesService_Create_Call) RunAndReturn(run func(ctx context.Context, domain string, targetHash string, targetType string) (*ipfs.WebsiteResponse, error)) *MockWebsitesService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithOptions provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) CreateWithOptions(ctx context.Context, req ipfs.WebsiteRequest) (*ipfs.WebsiteResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithOptions")
	}

	var r0 *ipfs.WebsiteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ipfs.WebsiteRequest) (*ipfs.WebsiteResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ipfs.WebsiteRequest) *ipfs.WebsiteResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.WebsiteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ipfs.WebsiteRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsitesService_CreateWithOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithOptions'
type MockWebsitesService_CreateWithOptions_Call struct {
	*mock.Call
}

// CreateWithOptions is a helper method to define mock.On call
//   - ctx context.Context
//   - req ipfs.WebsiteRequest
func (_e *MockWebsitesService_Expecter) CreateWithOptions(ctx any, req any) *MockWebsitesService_CreateWithOptions_Call {
	return &MockWebsitesService_CreateWithOptions_Call{Call: _e.mock.On("CreateWithOptions", ctx, req)}
}

func (_c *MockWebsitesService_CreateWithOptions_Call) Run(run func(ctx context.Context, req ipfs.WebsiteRequest)) *MockWebsitesService_CreateWithOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ipfs.WebsiteRequest
		if args[1] != nil {
			arg1 = args[1].(ipfs.WebsiteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebsitesService_CreateWithOptions_Call) Return(v *ipfs.WebsiteResponse, err error) *MockWebsitesService_CreateWithOptions_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockWebsitesService_CreateWithOptions_Call) RunAndReturn(run func(ctx context.Context, req ipfs.WebsiteRequest) (*ipfs.WebsiteResponse, error)) *MockWebsitesService_CreateWithOptions_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWebsitesService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWebsitesService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockWebsitesService_Expecter) Delete(ctx any, id any) *MockWebsitesService_Delete_Call {
	return &MockWebsitesService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockWebsitesService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockWebsitesService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebsitesService_Delete_Call) Return(err error) *MockWebsitesService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWebsitesService_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockWebsitesService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) Get(ctx context.Context, id string) (*ipfs.WebsiteResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *ipfs.WebsiteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ipfs.WebsiteResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ipfs.WebsiteResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.WebsiteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsitesService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockWebsitesService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockWebsitesService_Expecter) Get(ctx any, id any) *MockWebsitesService_Get_Call {
	return &MockWebsitesService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockWebsitesService_Get_Call) Run(run func(ctx context.Context, id string)) *MockWebsitesService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebsitesService_Get_Call) Return(v *ipfs.WebsiteResponse, err error) *MockWebsitesService_Get_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockWebsitesService_Get_Call) RunAndReturn(run func(ctx context.Context, id string) (*ipfs.WebsiteResponse, error)) *MockWebsitesService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfig provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) GetConfig(ctx context.Context) (*ipfs.WebsiteConfigResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 *ipfs.WebsiteConfigResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*ipfs.WebsiteConfigResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *ipfs.WebsiteConfigResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.WebsiteConfigResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsitesService_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type MockWebsitesService_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWebsitesService_Expecter) GetConfig(ctx any) *MockWebsitesService_GetConfig_Call {
	return &MockWebsitesService_GetConfig_Call{Call: _e.mock.On("GetConfig", ctx)}
}

func (_c *MockWebsitesService_GetConfig_Call) Run(run func(ctx context.Context)) *MockWebsitesService_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWebsitesService_GetConfig_Call) Return(v *ipfs.WebsiteConfigResponse, err error) *MockWebsitesService_GetConfig_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockWebsitesService_GetConfig_Call) RunAndReturn(run func(ctx context.Context) (*ipfs.WebsiteConfigResponse, error)) *MockWebsitesService_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetDomainDNSRequirements provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) GetDomainDNSRequirements(ctx context.Context, websiteID string, domainID string) (*ipfs.DomainResponse, error) {
	ret := _mock.Called(ctx, websiteID, domainID)

	if len(ret) == 0 {
		panic("no return value specified for GetDomainDNSRequirements")
	}

	var r0 *ipfs.DomainResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*ipfs.DomainResponse, error)); ok {
		return returnFunc(ctx, websiteID, domainID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *ipfs.DomainResponse); ok {
		r0 = returnFunc(ctx, websiteID, domainID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.DomainResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, websiteID, domainID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsitesService_GetDomainDNSRequirements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDomainDNSRequirements'
type MockWebsitesService_GetDomainDNSRequirements_Call struct {
	*mock.Call
}

// GetDomainDNSRequirements is a helper method to define mock.On call
//   - ctx context.Context
//   - websiteID string
//   - domainID string
func (_e *MockWebsitesService_Expecter) GetDomainDNSRequirements(ctx any, websiteID any, domainID any) *MockWebsitesService_GetDomainDNSRequirements_Call {
	return &MockWebsitesService_GetDomainDNSRequirements_Call{Call: _e.mock.On("GetDomainDNSRequirements", ctx, websiteID, domainID)}
}

func (_c *MockWebsitesService_GetDomainDNSRequirements_Call) Run(run func(ctx context.Context, websiteID string, domainID string)) *MockWebsitesService_GetDomainDNSRequirements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWebsitesService_GetDomainDNSRequirements_Call) Return(v *ipfs.DomainResponse, err error) *MockWebsitesService_GetDomainDNSRequirements_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockWebsitesService_GetDomainDNSRequirements_Call) RunAndReturn(run func(ctx context.Context, websiteID string, domainID string) (*ipfs.DomainResponse, error)) *MockWebsitesService_GetDomainDNSRequirements_Call {
	_c.Call.Return(run)
	return _c
}

// GetGatewayWebsite provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) GetGatewayWebsite(ctx context.Context, domain string) (*ipfs.GatewayWebsiteResponse, error) {
	ret := _mock.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for GetGatewayWebsite")
	}

	var r0 *ipfs.GatewayWebsiteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ipfs.GatewayWebsiteResponse, error)); ok {
		return returnFunc(ctx, domain)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ipfs.GatewayWebsiteResponse); ok {
		r0 = returnFunc(ctx, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.GatewayWebsiteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsitesService_GetGatewayWebsite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGatewayWebsite'
type MockWebsitesService_GetGatewayWebsite_Call struct {
	*mock.Call
}

// GetGatewayWebsite is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
func (_e *MockWebsitesService_Expecter) GetGatewayWebsite(ctx any, domain any) *MockWebsitesService_GetGatewayWebsite_Call {
	return &MockWebsitesService_GetGatewayWebsite_Call{Call: _e.mock.On("GetGatewayWebsite", ctx, domain)}
}

func (_c *MockWebsitesService_GetGatewayWebsite_Call) Run(run func(ctx context.Context, domain string)) *MockWebsitesService_GetGatewayWebsite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebsitesService_GetGatewayWebsite_Call) Return(v *ipfs.GatewayWebsiteResponse, err error) *MockWebsitesService_GetGatewayWebsite_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockWebsitesService_GetGatewayWebsite_Call) RunAndReturn(run func(ctx context.Context, domain string) (*ipfs.GatewayWebsiteResponse, error)) *MockWebsitesService_GetGatewayWebsite_Call {
	_c.Call.Return(run)
	return _c
}

// GetGatewayWebsiteStatus provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) GetGatewayWebsiteStatus(ctx context.Context, domain string) (*ipfs.GatewayWebsiteStatusResponse, error) {
	ret := _mock.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for GetGatewayWebsiteStatus")
	}

	var r0 *ipfs.GatewayWebsiteStatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ipfs.GatewayWebsiteStatusResponse, error)); ok {
		return returnFunc(ctx, domain)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ipfs.GatewayWebsiteStatusResponse); ok {
		r0 = returnFunc(ctx, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.GatewayWebsiteStatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsitesService_GetGatewayWebsiteStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGatewayWebsiteStatus'
type MockWebsitesService_GetGatewayWebsiteStatus_Call struct {
	*mock.Call
}

// GetGatewayWebsiteStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
func (_e *MockWebsitesService_Expecter) GetGatewayWebsiteStatus(ctx any, domain any) *MockWebsitesService_GetGatewayWebsiteStatus_Call {
	return &MockWebsitesService_GetGatewayWebsiteStatus_Call{Call: _e.mock.On("GetGatewayWebsiteStatus", ctx, domain)}
}

func (_c *MockWebsitesService_GetGatewayWebsiteStatus_Call) Run(run func(ctx context.Context, domain string)) *MockWebsitesService_GetGatewayWebsiteStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebsitesService_GetGatewayWebsiteStatus_Call) Return(v *ipfs.GatewayWebsiteStatusResponse, err error) *MockWebsitesService_GetGatewayWebsiteStatus_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockWebsitesService_GetGatewayWebsiteStatus_Call) RunAndReturn(run func(ctx context.Context, domain string) (*ipfs.GatewayWebsiteStatusResponse, error)) *MockWebsitesService_GetGatewayWebsiteStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetSSLStatus provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) GetSSLStatus(ctx context.Context, domain string) (*ipfs.WebsiteResponse, error) {
	ret := _mock.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for GetSSLStatus")
	}

	var r0 *ipfs.WebsiteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ipfs.WebsiteResponse, error)); ok {
		return returnFunc(ctx, domain)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ipfs.WebsiteResponse); ok {
		r0 = returnFunc(ctx, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.WebsiteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsitesService_GetSSLStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSSLStatus'
type MockWebsitesService_GetSSLStatus_Call struct {
	*mock.Call
}

// GetSSLStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
func (_e *MockWebsitesService_Expecter) GetSSLStatus(ctx any, domain any) *MockWebsitesService_GetSSLStatus_Call {
	return &MockWebsitesService_GetSSLStatus_Call{Call: _e.mock.On("GetSSLStatus", ctx, domain)}
}

func (_c *MockWebsitesService_GetSSLStatus_Call) Run(run func(ctx context.Context, domain string)) *MockWebsitesService_GetSSLStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebsitesService_GetSSLStatus_Call) Return(v *ipfs.WebsiteResponse, err error) *MockWebsitesService_GetSSLStatus_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockWebsitesService_GetSSLStatus_Call) RunAndReturn(run func(ctx context.Context, domain string) (*ipfs.WebsiteResponse, error)) *MockWebsitesService_GetSSLStatus_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) List(ctx context.Context) ([]ipfs.WebsiteItem, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []ipfs.WebsiteItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ipfs.WebsiteItem, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ipfs.WebsiteItem); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ipfs.WebsiteItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsitesService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWebsitesService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWebsitesService_Expecter) List(ctx any) *MockWebsitesService_List_Call {
	return &MockWebsitesService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockWebsitesService_List_Call) Run(run func(ctx context.Context)) *MockWebsitesService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWebsitesService_List_Call) Return(vs []ipfs.WebsiteItem, err error) *MockWebsitesService_List_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockWebsitesService_List_Call) RunAndReturn(run func(ctx context.Context) ([]ipfs.WebsiteItem, error)) *MockWebsitesService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListDomains provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) ListDomains(ctx context.Context, websiteID string) ([]ipfs.DomainResponse, error) {
	ret := _mock.Called(ctx, websiteID)

	if len(ret) == 0 {
		panic("no return value specified for ListDomains")
	}

	var r0 []ipfs.DomainResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]ipfs.DomainResponse, error)); ok {
		return returnFunc(ctx, websiteID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []ipfs.DomainResponse); ok {
		r0 = returnFunc(ctx, websiteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ipfs.DomainResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, websiteID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsitesService_ListDomains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDomains'
type MockWebsitesService_ListDomains_Call struct {
	*mock.Call
}

// ListDomains is a helper method to define mock.On call
//   - ctx context.Context
//   - websiteID string
func (_e *MockWebsitesService_Expecter) ListDomains(ctx any, websiteID any) *MockWebsitesService_ListDomains_Call {
	return &MockWebsitesService_ListDomains_Call{Call: _e.mock.On("ListDomains", ctx, websiteID)}
}

func (_c *MockWebsitesService_ListDomains_Call) Run(run func(ctx context.Context, websiteID string)) *MockWebsitesService_ListDomains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebsitesService_ListDomains_Call) Return(vs []ipfs.DomainResponse, err error) *MockWebsitesService_ListDomains_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockWebsitesService_ListDomains_Call) RunAndReturn(run func(ctx context.Context, websiteID string) ([]ipfs.DomainResponse, error)) *MockWebsitesService_ListDomains_Call {
	_c.Call.Return(run)
	return _c
}

// RepublishDANE provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) RepublishDANE(ctx context.Context, websiteID string, domainID string) (*ipfs.DomainDANERepublishResponse, error) {
	ret := _mock.Called(ctx, websiteID, domainID)

	if len(ret) == 0 {
		panic("no return value specified for RepublishDANE")
	}

	var r0 *ipfs.DomainDANERepublishResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*ipfs.DomainDANERepublishResponse, error)); ok {
		return returnFunc(ctx, websiteID, domainID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *ipfs.DomainDANERepublishResponse); ok {
		r0 = returnFunc(ctx, websiteID, domainID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.DomainDANERepublishResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, websiteID, domainID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsitesService_RepublishDANE_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RepublishDANE'
type MockWebsitesService_RepublishDANE_Call struct {
	*mock.Call
}

// RepublishDANE is a helper method to define mock.On call
//   - ctx context.Context
//   - websiteID string
//   - domainID string
func (_e *MockWebsitesService_Expecter) RepublishDANE(ctx any, websiteID any, domainID any) *MockWebsitesService_RepublishDANE_Call {
	return &MockWebsitesService_RepublishDANE_Call{Call: _e.mock.On("RepublishDANE", ctx, websiteID, domainID)}
}

func (_c *MockWebsitesService_RepublishDANE_Call) Run(run func(ctx context.Context, websiteID string, domainID string)) *MockWebsitesService_RepublishDANE_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWebsitesService_RepublishDANE_Call) Return(v *ipfs.DomainDANERepublishResponse, err error) *MockWebsitesService_RepublishDANE_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockWebsitesService_RepublishDANE_Call) RunAndReturn(run func(ctx context.Context, websiteID string, domainID string) (*ipfs.DomainDANERepublishResponse, error)) *MockWebsitesService_RepublishDANE_Call {
	_c.Call.Return(run)
	return _c
}

// UnbindDomain provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) UnbindDomain(ctx context.Context, websiteID string, domainID string) error {
	ret := _mock.Called(ctx, websiteID, domainID)

	if len(ret) == 0 {
		panic("no return value specified for UnbindDomain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, websiteID, domainID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWebsitesService_UnbindDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnbindDomain'
type MockWebsitesService_UnbindDomain_Call struct {
	*mock.Call
}

// UnbindDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - websiteID string
//   - domainID string
func (_e *MockWebsitesService_Expecter) UnbindDomain(ctx any, websiteID any, domainID any) *MockWebsitesService_UnbindDomain_Call {
	return &MockWebsitesService_UnbindDomain_Call{Call: _e.mock.On("UnbindDomain", ctx, websiteID, domainID)}
}

func (_c *MockWebsitesService_UnbindDomain_Call) Run(run func(ctx context.Context, websiteID string, domainID string)) *MockWebsitesService_UnbindDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWebsitesService_UnbindDomain_Call) Return(err error) *MockWebsitesService_UnbindDomain_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWebsitesService_UnbindDomain_Call) RunAndReturn(run func(ctx context.Context, websiteID string, domainID string) error) *MockWebsitesService_UnbindDomain_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) Update(ctx context.Context, id string, domain string, targetHash string, targetType string) (*ipfs.WebsiteResponse, error) {
	ret := _mock.Called(ctx, id, domain, targetHash, targetType)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *ipfs.WebsiteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*ipfs.WebsiteResponse, error)); ok {
		return returnFunc(ctx, id, domain, targetHash, targetType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *ipfs.WebsiteResponse); ok {
		r0 = returnFunc(ctx, id, domain, targetHash, targetType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.WebsiteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, id, domain, targetHash, targetType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsitesService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockWebsitesService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - domain string
//   - targetHash string
//   - targetType string
func (_e *MockWebsitesService_Expecter) Update(ctx any, id any, domain any, targetHash any, targetType any) *MockWebsitesService_Update_Call {
	return &MockWebsitesService_Update_Call{Call: _e.mock.On("Update", ctx, id, domain, targetHash, targetType)}
}

func (_c *MockWebsitesService_Update_Call) Run(run func(ctx context.Context, id string, domain string, targetHash string, targetType string)) *MockWebsitesService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockWebsitesService_Update_Call) Return(v *ipfs.WebsiteResponse, err error) *MockWebsitesService_Update_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockWebsitesService_Update_Call) RunAndReturn(run func(ctx context.Context, id string, domain string, targetHash string, targetType string) (*ipfs.WebsiteResponse, error)) *MockWebsitesService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDomain provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) UpdateDomain(ctx context.Context, websiteID string, domainID string, req ipfs.DomainUpdateRequest) (*ipfs.DomainResponse, error) {
	ret := _mock.Called(ctx, websiteID, domainID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDomain")
	}

	var r0 *ipfs.DomainResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ipfs.DomainUpdateRequest) (*ipfs.DomainResponse, error)); ok {
		return returnFunc(ctx, websiteID, domainID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ipfs.DomainUpdateRequest) *ipfs.DomainResponse); ok {
		r0 = returnFunc(ctx, websiteID, domainID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.DomainResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, ipfs.DomainUpdateRequest) error); ok {
		r1 = returnFunc(ctx, websiteID, domainID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsitesService_UpdateDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDomain'
type MockWebsitesService_UpdateDomain_Call struct {
	*mock.Call
}

// UpdateDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - websiteID string
//   - domainID string
//   - req ipfs.DomainUpdateRequest
func (_e *MockWebsitesService_Expecter) UpdateDomain(ctx any, websiteID any, domainID any, req any) *MockWebsitesService_UpdateDomain_Call {
	return &MockWebsitesService_UpdateDomain_Call{Call: _e.mock.On("UpdateDomain", ctx, websiteID, domainID, req)}
}

func (_c *MockWebsitesService_UpdateDomain_Call) Run(run func(ctx context.Context, websiteID string, domainID string, req ipfs.DomainUpdateRequest)) *MockWebsitesService_UpdateDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 ipfs.DomainUpdateRequest
		if args[3] != nil {
			arg3 = args[3].(ipfs.DomainUpdateRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWebsitesService_UpdateDomain_Call) Return(v *ipfs.DomainResponse, err error) *MockWebsitesService_UpdateDomain_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockWebsitesService_UpdateDomain_Call) RunAndReturn(run func(ctx context.Context, websiteID string, domainID string, req ipfs.DomainUpdateRequest) (*ipfs.DomainResponse, error)) *MockWebsitesService_UpdateDomain_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSSLStatusInternal provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) UpdateSSLStatusInternal(ctx context.Context, domain string, sslStatus ipfs.SSLStatusUpdateRequest) error {
	ret := _mock.Called(ctx, domain, sslStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSSLStatusInternal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ipfs.SSLStatusUpdateRequest) error); ok {
		r0 = returnFunc(ctx, domain, sslStatus)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWebsitesService_UpdateSSLStatusInternal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSSLStatusInternal'
type MockWebsitesService_UpdateSSLStatusInternal_Call struct {
	*mock.Call
}

// UpdateSSLStatusInternal is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - sslStatus ipfs.SSLStatusUpdateRequest
func (_e *MockWebsitesService_Expecter) UpdateSSLStatusInternal(ctx any, domain any, sslStatus any) *MockWebsitesService_UpdateSSLStatusInternal_Call {
	return &MockWebsitesService_UpdateSSLStatusInternal_Call{Call: _e.mock.On("UpdateSSLStatusInternal", ctx, domain, sslStatus)}
}

func (_c *MockWebsitesService_UpdateSSLStatusInternal_Call) Run(run func(ctx context.Context, domain string, sslStatus ipfs.SSLStatusUpdateRequest)) *MockWebsitesService_UpdateSSLStatusInternal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 ipfs.SSLStatusUpdateRequest
		if args[2] != nil {
			arg2 = args[2].(ipfs.SSLStatusUpdateRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWebsitesService_UpdateSSLStatusInternal_Call) Return(err error) *MockWebsitesService_UpdateSSLStatusInternal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWebsitesService_UpdateSSLStatusInternal_Call) RunAndReturn(run func(ctx context.Context, domain string, sslStatus ipfs.SSLStatusUpdateRequest) error) *MockWebsitesService_UpdateSSLStatusInternal_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithOptions provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) UpdateWithOptions(ctx context.Context, id string, req ipfs.WebsiteUpdateRequest) (*ipfs.WebsiteResponse, error) {
	ret := _mock.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithOptions")
	}

	var r0 *ipfs.WebsiteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ipfs.WebsiteUpdateRequest) (*ipfs.WebsiteResponse, error)); ok {
		return returnFunc(ctx, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ipfs.WebsiteUpdateRequest) *ipfs.WebsiteResponse); ok {
		r0 = returnFunc(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.WebsiteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ipfs.WebsiteUpdateRequest) error); ok {
		r1 = returnFunc(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsitesService_UpdateWithOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithOptions'
type MockWebsitesService_UpdateWithOptions_Call struct {
	*mock.Call
}

// UpdateWithOptions is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req ipfs.WebsiteUpdateRequest
func (_e *MockWebsitesService_Expecter) UpdateWithOptions(ctx any, id any, req any) *MockWebsitesService_UpdateWithOptions_Call {
	return &MockWebsitesService_UpdateWithOptions_Call{Call: _e.mock.On("UpdateWithOptions", ctx, id, req)}
}

func (_c *MockWebsitesService_UpdateWithOptions_Call) Run(run func(ctx context.Context, id string, req ipfs.WebsiteUpdateRequest)) *MockWebsitesService_UpdateWithOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 ipfs.WebsiteUpdateRequest
		if args[2] != nil {
			arg2 = args[2].(ipfs.WebsiteUpdateRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWebsitesService_UpdateWithOptions_Call) Return(v *ipfs.WebsiteResponse, err error) *MockWebsitesService_UpdateWithOptions_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockWebsitesService_UpdateWithOptions_Call) RunAndReturn(run func(ctx context.Context, id string, req ipfs.WebsiteUpdateRequest) (*ipfs.WebsiteResponse, error)) *MockWebsitesService_UpdateWithOptions_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateDNS provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) ValidateDNS(ctx context.Context, id string) (*ipfs.WebsiteValidateResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ValidateDNS")
	}

	var r0 *ipfs.WebsiteValidateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ipfs.WebsiteValidateResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ipfs.WebsiteValidateResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.WebsiteValidateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsitesService_ValidateDNS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateDNS'
type MockWebsitesService_ValidateDNS_Call struct {
	*mock.Call
}

// ValidateDNS is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockWebsitesService_Expecter) ValidateDNS(ctx any, id any) *MockWebsitesService_ValidateDNS_Call {
	return &MockWebsitesService_ValidateDNS_Call{Call: _e.mock.On("ValidateDNS", ctx, id)}
}

func (_c *MockWebsitesService_ValidateDNS_Call) Run(run func(ctx context.Context, id string)) *MockWebsitesService_ValidateDNS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebsitesService_ValidateDNS_Call) Return(v *ipfs.WebsiteValidateResponse, err error) *MockWebsitesService_ValidateDNS_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockWebsitesService_ValidateDNS_Call) RunAndReturn(run func(ctx context.Context, id string) (*ipfs.WebsiteValidateResponse, error)) *MockWebsitesService_ValidateDNS_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyDomain provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) VerifyDomain(ctx context.Context, websiteID string, domainID string) (*ipfs.DomainResponse, error) {
	ret := _mock.Called(ctx, websiteID, domainID)

	if len(ret) == 0 {
		panic("no return value specified for VerifyDomain")
	}

	var r0 *ipfs.DomainResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*ipfs.DomainResponse, error)); ok {
		return returnFunc(ctx, websiteID, domainID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *ipfs.DomainResponse); ok {
		r0 = returnFunc(ctx, websiteID, domainID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.DomainResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, websiteID, domainID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsitesService_VerifyDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyDomain'
type MockWebsitesService_VerifyDomain_Call struct {
	*mock.Call
}

// VerifyDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - websiteID string
//   - domainID string
func (_e *MockWebsitesService_Expecter) VerifyDomain(ctx any, websiteID any, domainID any) *MockWebsitesService_VerifyDomain_Call {
	return &MockWebsitesService_VerifyDomain_Call{Call: _e.mock.On("VerifyDomain", ctx, websiteID, domainID)}
}

func (_c *MockWebsitesService_VerifyDomain_Call) Run(run func(ctx context.Context, websiteID string, domainID string)) *MockWebsitesService_VerifyDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWebsitesService_VerifyDomain_Call) Return(v *ipfs.DomainResponse, err error) *MockWebsitesService_VerifyDomain_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockWebsitesService_VerifyDomain_Call) RunAndReturn(run func(ctx context.Context, websiteID string, domainID string) (*ipfs.DomainResponse, error)) *MockWebsitesService_VerifyDomain_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForDNSValidation provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) WaitForDNSValidation(ctx context.Context, id string, opts ...ipfs.PollOption) error {
	// ipfs.PollOption
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WaitForDNSValidation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...ipfs.PollOption) error); ok {
		r0 = returnFunc(ctx, id, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWebsitesService_WaitForDNSValidation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForDNSValidation'
type MockWebsitesService_WaitForDNSValidation_Call struct {
	*mock.Call
}

// WaitForDNSValidation is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - opts ...ipfs.PollOption
func (_e *MockWebsitesService_Expecter) WaitForDNSValidation(ctx any, id any, opts ...any) *MockWebsitesService_WaitForDNSValidation_Call {
	return &MockWebsitesService_WaitForDNSValidation_Call{Call: _e.mock.On("WaitForDNSValidation",
		append([]any{ctx, id}, opts...)...)}
}

func (_c *MockWebsitesService_WaitForDNSValidation_Call) Run(run func(ctx context.Context, id string, opts ...ipfs.PollOption)) *MockWebsitesService_WaitForDNSValidation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []ipfs.PollOption
		variadicArgs := make([]ipfs.PollOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(ipfs.PollOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockWebsitesService_WaitForDNSValidation_Call) Return(err error) *MockWebsitesService_WaitForDNSValidation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWebsitesService_WaitForDNSValidation_Call) RunAndReturn(run func(ctx context.Context, id string, opts ...ipfs.PollOption) error) *MockWebsitesService_WaitForDNSValidation_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForSSLStatusReady provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) WaitForSSLStatusReady(ctx context.Context, domain string, opts ...ipfs.PollOption) (string, error) {
	// ipfs.PollOption
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, domain)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WaitForSSLStatusReady")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...ipfs.PollOption) (string, error)); ok {
		return returnFunc(ctx, domain, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...ipfs.PollOption) string); ok {
		r0 = returnFunc(ctx, domain, opts...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...ipfs.PollOption) error); ok {
		r1 = returnFunc(ctx, domain, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsitesService_WaitForSSLStatusReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForSSLStatusReady'
type MockWebsitesService_WaitForSSLStatusReady_Call struct {
	*mock.Call
}

// WaitForSSLStatusReady is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - opts ...ipfs.PollOption
func (_e *MockWebsitesService_Expecter) WaitForSSLStatusReady(ctx any, domain any, opts ...any) *MockWebsitesService_WaitForSSLStatusReady_Call {
	return &MockWebsitesService_WaitForSSLStatusReady_Call{Call: _e.mock.On("WaitForSSLStatusReady",
		append([]any{ctx, domain}, opts...)...)}
}

func (_c *MockWebsitesService_WaitForSSLStatusReady_Call) Run(run func(ctx context.Context, domain string, opts ...ipfs.PollOption)) *MockWebsitesService_WaitForSSLStatusReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []ipfs.PollOption
		variadicArgs := make([]ipfs.PollOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(ipfs.PollOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockWebsitesService_WaitForSSLStatusReady_Call) Return(s string, err error) *MockWebsitesService_WaitForSSLStatusReady_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockWebsitesService_WaitForSSLStatusReady_Call) RunAndReturn(run func(ctx context.Context, domain string, opts ...ipfs.PollOption) (string, error)) *MockWebsitesService_WaitForSSLStatusReady_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForWebsiteStatus provides a mock function for the type MockWebsitesService
func (_mock *MockWebsitesService) WaitForWebsiteStatus(ctx context.Context, id string, expectedStatus string, opts ...ipfs.PollOption) error {
	// ipfs.PollOption
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, id, expectedStatus)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WaitForWebsiteStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...ipfs.PollOption) error); ok {
		r0 = returnFunc(ctx, id, expectedStatus, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWebsitesService_WaitForWebsiteStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForWebsiteStatus'
type MockWebsitesService_WaitForWebsiteStatus_Call struct {
	*mock.Call
}

// WaitForWebsiteStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - expectedStatus string
//   - opts ...ipfs.PollOption
func (_e *MockWebsitesService_Expecter) WaitForWebsiteStatus(ctx any, id any, expectedStatus any, opts ...any) *MockWebsitesService_WaitForWebsiteStatus_Call {
	return &MockWebsitesService_WaitForWebsiteStatus_Call{Call: _e.mock.On("WaitForWebsiteStatus",
		append([]any{ctx, id, expectedStatus}, opts...)...)}
}

func (_c *MockWebsitesService_WaitForWebsiteStatus_Call) Run(run func(ctx context.Context, id string, expectedStatus string, opts ...ipfs.PollOption)) *MockWebsitesService_WaitForWebsiteStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []ipfs.PollOption
		variadicArgs := make([]ipfs.PollOption, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(ipfs.PollOption)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockWebsitesService_WaitForWebsiteStatus_Call) Return(err error) *MockWebsitesService_WaitForWebsiteStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWebsitesService_WaitForWebsiteStatus_Call) RunAndReturn(run func(ctx context.Context, id string, expectedStatus string, opts ...ipfs.PollOption) error) *MockWebsitesService_WaitForWebsiteStatus_Call {
	_c.Call.Return(run)
	return _c
}
