// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	cid "github.com/ipfs/go-cid"

	files "github.com/ipfs/boxo/files"

	gateway "github.com/ipfs/boxo/gateway"

	io "io"

	mock "github.com/stretchr/testify/mock"

	path "github.com/ipfs/boxo/path"

	time "time"
)

// MockBackend is an autogenerated mock type for the Backend type
type MockBackend struct {
	mock.Mock
}

type MockBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackend) EXPECT() *MockBackend_Expecter {
	return &MockBackend_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockBackend) Get(_a0 context.Context, _a1 path.ImmutablePath, _a2 ...gateway.ByteRange) (gateway.ContentPathMetadata, *gateway.GetResponse, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 gateway.ContentPathMetadata
	var r1 *gateway.GetResponse
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, path.ImmutablePath, ...gateway.ByteRange) (gateway.ContentPathMetadata, *gateway.GetResponse, error)); ok {
		return rf(_a0, _a1, _a2...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, path.ImmutablePath, ...gateway.ByteRange) gateway.ContentPathMetadata); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		r0 = ret.Get(0).(gateway.ContentPathMetadata)
	}

	if rf, ok := ret.Get(1).(func(context.Context, path.ImmutablePath, ...gateway.ByteRange) *gateway.GetResponse); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gateway.GetResponse)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, path.ImmutablePath, ...gateway.ByteRange) error); ok {
		r2 = rf(_a0, _a1, _a2...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockBackend_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBackend_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 path.ImmutablePath
//   - _a2 ...gateway.ByteRange
func (_e *MockBackend_Expecter) Get(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *MockBackend_Get_Call {
	return &MockBackend_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *MockBackend_Get_Call) Run(run func(_a0 context.Context, _a1 path.ImmutablePath, _a2 ...gateway.ByteRange)) *MockBackend_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]gateway.ByteRange, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(gateway.ByteRange)
			}
		}
		run(args[0].(context.Context), args[1].(path.ImmutablePath), variadicArgs...)
	})
	return _c
}

func (_c *MockBackend_Get_Call) Return(_a0 gateway.ContentPathMetadata, _a1 *gateway.GetResponse, _a2 error) *MockBackend_Get_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockBackend_Get_Call) RunAndReturn(run func(context.Context, path.ImmutablePath, ...gateway.ByteRange) (gateway.ContentPathMetadata, *gateway.GetResponse, error)) *MockBackend_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: _a0, _a1
func (_m *MockBackend) GetAll(_a0 context.Context, _a1 path.ImmutablePath) (gateway.ContentPathMetadata, files.Node, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 gateway.ContentPathMetadata
	var r1 files.Node
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, path.ImmutablePath) (gateway.ContentPathMetadata, files.Node, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, path.ImmutablePath) gateway.ContentPathMetadata); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(gateway.ContentPathMetadata)
	}

	if rf, ok := ret.Get(1).(func(context.Context, path.ImmutablePath) files.Node); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(files.Node)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, path.ImmutablePath) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockBackend_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockBackend_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 path.ImmutablePath
func (_e *MockBackend_Expecter) GetAll(_a0 interface{}, _a1 interface{}) *MockBackend_GetAll_Call {
	return &MockBackend_GetAll_Call{Call: _e.mock.On("GetAll", _a0, _a1)}
}

func (_c *MockBackend_GetAll_Call) Run(run func(_a0 context.Context, _a1 path.ImmutablePath)) *MockBackend_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(path.ImmutablePath))
	})
	return _c
}

func (_c *MockBackend_GetAll_Call) Return(_a0 gateway.ContentPathMetadata, _a1 files.Node, _a2 error) *MockBackend_GetAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockBackend_GetAll_Call) RunAndReturn(run func(context.Context, path.ImmutablePath) (gateway.ContentPathMetadata, files.Node, error)) *MockBackend_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlock provides a mock function with given fields: _a0, _a1
func (_m *MockBackend) GetBlock(_a0 context.Context, _a1 path.ImmutablePath) (gateway.ContentPathMetadata, files.File, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetBlock")
	}

	var r0 gateway.ContentPathMetadata
	var r1 files.File
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, path.ImmutablePath) (gateway.ContentPathMetadata, files.File, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, path.ImmutablePath) gateway.ContentPathMetadata); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(gateway.ContentPathMetadata)
	}

	if rf, ok := ret.Get(1).(func(context.Context, path.ImmutablePath) files.File); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(files.File)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, path.ImmutablePath) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockBackend_GetBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlock'
type MockBackend_GetBlock_Call struct {
	*mock.Call
}

// GetBlock is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 path.ImmutablePath
func (_e *MockBackend_Expecter) GetBlock(_a0 interface{}, _a1 interface{}) *MockBackend_GetBlock_Call {
	return &MockBackend_GetBlock_Call{Call: _e.mock.On("GetBlock", _a0, _a1)}
}

func (_c *MockBackend_GetBlock_Call) Run(run func(_a0 context.Context, _a1 path.ImmutablePath)) *MockBackend_GetBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(path.ImmutablePath))
	})
	return _c
}

func (_c *MockBackend_GetBlock_Call) Return(_a0 gateway.ContentPathMetadata, _a1 files.File, _a2 error) *MockBackend_GetBlock_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockBackend_GetBlock_Call) RunAndReturn(run func(context.Context, path.ImmutablePath) (gateway.ContentPathMetadata, files.File, error)) *MockBackend_GetBlock_Call {
	_c.Call.Return(run)
	return _c
}

// GetCAR provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockBackend) GetCAR(_a0 context.Context, _a1 path.ImmutablePath, _a2 gateway.CarParams) (gateway.ContentPathMetadata, io.ReadCloser, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetCAR")
	}

	var r0 gateway.ContentPathMetadata
	var r1 io.ReadCloser
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, path.ImmutablePath, gateway.CarParams) (gateway.ContentPathMetadata, io.ReadCloser, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, path.ImmutablePath, gateway.CarParams) gateway.ContentPathMetadata); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(gateway.ContentPathMetadata)
	}

	if rf, ok := ret.Get(1).(func(context.Context, path.ImmutablePath, gateway.CarParams) io.ReadCloser); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, path.ImmutablePath, gateway.CarParams) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockBackend_GetCAR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCAR'
type MockBackend_GetCAR_Call struct {
	*mock.Call
}

// GetCAR is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 path.ImmutablePath
//   - _a2 gateway.CarParams
func (_e *MockBackend_Expecter) GetCAR(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockBackend_GetCAR_Call {
	return &MockBackend_GetCAR_Call{Call: _e.mock.On("GetCAR", _a0, _a1, _a2)}
}

func (_c *MockBackend_GetCAR_Call) Run(run func(_a0 context.Context, _a1 path.ImmutablePath, _a2 gateway.CarParams)) *MockBackend_GetCAR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(path.ImmutablePath), args[2].(gateway.CarParams))
	})
	return _c
}

func (_c *MockBackend_GetCAR_Call) Return(_a0 gateway.ContentPathMetadata, _a1 io.ReadCloser, _a2 error) *MockBackend_GetCAR_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockBackend_GetCAR_Call) RunAndReturn(run func(context.Context, path.ImmutablePath, gateway.CarParams) (gateway.ContentPathMetadata, io.ReadCloser, error)) *MockBackend_GetCAR_Call {
	_c.Call.Return(run)
	return _c
}

// GetDNSLinkRecord provides a mock function with given fields: _a0, _a1
func (_m *MockBackend) GetDNSLinkRecord(_a0 context.Context, _a1 string) (path.Path, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetDNSLinkRecord")
	}

	var r0 path.Path
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (path.Path, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) path.Path); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(path.Path)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBackend_GetDNSLinkRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDNSLinkRecord'
type MockBackend_GetDNSLinkRecord_Call struct {
	*mock.Call
}

// GetDNSLinkRecord is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockBackend_Expecter) GetDNSLinkRecord(_a0 interface{}, _a1 interface{}) *MockBackend_GetDNSLinkRecord_Call {
	return &MockBackend_GetDNSLinkRecord_Call{Call: _e.mock.On("GetDNSLinkRecord", _a0, _a1)}
}

func (_c *MockBackend_GetDNSLinkRecord_Call) Run(run func(_a0 context.Context, _a1 string)) *MockBackend_GetDNSLinkRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBackend_GetDNSLinkRecord_Call) Return(_a0 path.Path, _a1 error) *MockBackend_GetDNSLinkRecord_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBackend_GetDNSLinkRecord_Call) RunAndReturn(run func(context.Context, string) (path.Path, error)) *MockBackend_GetDNSLinkRecord_Call {
	_c.Call.Return(run)
	return _c
}

// GetIPNSRecord provides a mock function with given fields: _a0, _a1
func (_m *MockBackend) GetIPNSRecord(_a0 context.Context, _a1 cid.Cid) ([]byte, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetIPNSRecord")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, cid.Cid) ([]byte, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, cid.Cid) []byte); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, cid.Cid) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBackend_GetIPNSRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIPNSRecord'
type MockBackend_GetIPNSRecord_Call struct {
	*mock.Call
}

// GetIPNSRecord is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 cid.Cid
func (_e *MockBackend_Expecter) GetIPNSRecord(_a0 interface{}, _a1 interface{}) *MockBackend_GetIPNSRecord_Call {
	return &MockBackend_GetIPNSRecord_Call{Call: _e.mock.On("GetIPNSRecord", _a0, _a1)}
}

func (_c *MockBackend_GetIPNSRecord_Call) Run(run func(_a0 context.Context, _a1 cid.Cid)) *MockBackend_GetIPNSRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(cid.Cid))
	})
	return _c
}

func (_c *MockBackend_GetIPNSRecord_Call) Return(_a0 []byte, _a1 error) *MockBackend_GetIPNSRecord_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBackend_GetIPNSRecord_Call) RunAndReturn(run func(context.Context, cid.Cid) ([]byte, error)) *MockBackend_GetIPNSRecord_Call {
	_c.Call.Return(run)
	return _c
}

// Head provides a mock function with given fields: _a0, _a1
func (_m *MockBackend) Head(_a0 context.Context, _a1 path.ImmutablePath) (gateway.ContentPathMetadata, *gateway.HeadResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Head")
	}

	var r0 gateway.ContentPathMetadata
	var r1 *gateway.HeadResponse
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, path.ImmutablePath) (gateway.ContentPathMetadata, *gateway.HeadResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, path.ImmutablePath) gateway.ContentPathMetadata); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(gateway.ContentPathMetadata)
	}

	if rf, ok := ret.Get(1).(func(context.Context, path.ImmutablePath) *gateway.HeadResponse); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gateway.HeadResponse)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, path.ImmutablePath) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockBackend_Head_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Head'
type MockBackend_Head_Call struct {
	*mock.Call
}

// Head is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 path.ImmutablePath
func (_e *MockBackend_Expecter) Head(_a0 interface{}, _a1 interface{}) *MockBackend_Head_Call {
	return &MockBackend_Head_Call{Call: _e.mock.On("Head", _a0, _a1)}
}

func (_c *MockBackend_Head_Call) Run(run func(_a0 context.Context, _a1 path.ImmutablePath)) *MockBackend_Head_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(path.ImmutablePath))
	})
	return _c
}

func (_c *MockBackend_Head_Call) Return(_a0 gateway.ContentPathMetadata, _a1 *gateway.HeadResponse, _a2 error) *MockBackend_Head_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockBackend_Head_Call) RunAndReturn(run func(context.Context, path.ImmutablePath) (gateway.ContentPathMetadata, *gateway.HeadResponse, error)) *MockBackend_Head_Call {
	_c.Call.Return(run)
	return _c
}

// IsCached provides a mock function with given fields: _a0, _a1
func (_m *MockBackend) IsCached(_a0 context.Context, _a1 path.Path) bool {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for IsCached")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, path.Path) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockBackend_IsCached_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsCached'
type MockBackend_IsCached_Call struct {
	*mock.Call
}

// IsCached is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 path.Path
func (_e *MockBackend_Expecter) IsCached(_a0 interface{}, _a1 interface{}) *MockBackend_IsCached_Call {
	return &MockBackend_IsCached_Call{Call: _e.mock.On("IsCached", _a0, _a1)}
}

func (_c *MockBackend_IsCached_Call) Run(run func(_a0 context.Context, _a1 path.Path)) *MockBackend_IsCached_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(path.Path))
	})
	return _c
}

func (_c *MockBackend_IsCached_Call) Return(_a0 bool) *MockBackend_IsCached_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBackend_IsCached_Call) RunAndReturn(run func(context.Context, path.Path) bool) *MockBackend_IsCached_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveMutable provides a mock function with given fields: _a0, _a1
func (_m *MockBackend) ResolveMutable(_a0 context.Context, _a1 path.Path) (path.ImmutablePath, time.Duration, time.Time, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ResolveMutable")
	}

	var r0 path.ImmutablePath
	var r1 time.Duration
	var r2 time.Time
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, path.Path) (path.ImmutablePath, time.Duration, time.Time, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, path.Path) path.ImmutablePath); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(path.ImmutablePath)
	}

	if rf, ok := ret.Get(1).(func(context.Context, path.Path) time.Duration); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(time.Duration)
	}

	if rf, ok := ret.Get(2).(func(context.Context, path.Path) time.Time); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Get(2).(time.Time)
	}

	if rf, ok := ret.Get(3).(func(context.Context, path.Path) error); ok {
		r3 = rf(_a0, _a1)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockBackend_ResolveMutable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveMutable'
type MockBackend_ResolveMutable_Call struct {
	*mock.Call
}

// ResolveMutable is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 path.Path
func (_e *MockBackend_Expecter) ResolveMutable(_a0 interface{}, _a1 interface{}) *MockBackend_ResolveMutable_Call {
	return &MockBackend_ResolveMutable_Call{Call: _e.mock.On("ResolveMutable", _a0, _a1)}
}

func (_c *MockBackend_ResolveMutable_Call) Run(run func(_a0 context.Context, _a1 path.Path)) *MockBackend_ResolveMutable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(path.Path))
	})
	return _c
}

func (_c *MockBackend_ResolveMutable_Call) Return(_a0 path.ImmutablePath, _a1 time.Duration, _a2 time.Time, _a3 error) *MockBackend_ResolveMutable_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockBackend_ResolveMutable_Call) RunAndReturn(run func(context.Context, path.Path) (path.ImmutablePath, time.Duration, time.Time, error)) *MockBackend_ResolveMutable_Call {
	_c.Call.Return(run)
	return _c
}

// ResolvePath provides a mock function with given fields: _a0, _a1
func (_m *MockBackend) ResolvePath(_a0 context.Context, _a1 path.ImmutablePath) (gateway.ContentPathMetadata, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ResolvePath")
	}

	var r0 gateway.ContentPathMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, path.ImmutablePath) (gateway.ContentPathMetadata, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, path.ImmutablePath) gateway.ContentPathMetadata); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(gateway.ContentPathMetadata)
	}

	if rf, ok := ret.Get(1).(func(context.Context, path.ImmutablePath) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBackend_ResolvePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolvePath'
type MockBackend_ResolvePath_Call struct {
	*mock.Call
}

// ResolvePath is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 path.ImmutablePath
func (_e *MockBackend_Expecter) ResolvePath(_a0 interface{}, _a1 interface{}) *MockBackend_ResolvePath_Call {
	return &MockBackend_ResolvePath_Call{Call: _e.mock.On("ResolvePath", _a0, _a1)}
}

func (_c *MockBackend_ResolvePath_Call) Run(run func(_a0 context.Context, _a1 path.ImmutablePath)) *MockBackend_ResolvePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(path.ImmutablePath))
	})
	return _c
}

func (_c *MockBackend_ResolvePath_Call) Return(_a0 gateway.ContentPathMetadata, _a1 error) *MockBackend_ResolvePath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBackend_ResolvePath_Call) RunAndReturn(run func(context.Context, path.ImmutablePath) (gateway.ContentPathMetadata, error)) *MockBackend_ResolvePath_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBackend creates a new instance of MockBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackend {
	mock := &MockBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
