// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	client "go.lumeweb.com/ipfs-sdk/internal/client"

	mock "github.com/stretchr/testify/mock"
)

// MockDAGClientWithResponsesInterface is an autogenerated mock type for the DAGClientWithResponsesInterface type
type MockDAGClientWithResponsesInterface struct {
	mock.Mock
}

type MockDAGClientWithResponsesInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDAGClientWithResponsesInterface) EXPECT() *MockDAGClientWithResponsesInterface_Expecter {
	return &MockDAGClientWithResponsesInterface_Expecter{mock: &_m.Mock}
}

// GetApiDagCidWithResponse provides a mock function with given fields: ctx, cid, reqEditors
func (_m *MockDAGClientWithResponsesInterface) GetApiDagCidWithResponse(ctx context.Context, cid string, reqEditors ...client.RequestEditorFn) (*client.GetApiDagCidResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, cid)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiDagCidWithResponse")
	}

	var r0 *client.GetApiDagCidResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) (*client.GetApiDagCidResponse, error)); ok {
		return rf(ctx, cid, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) *client.GetApiDagCidResponse); ok {
		r0 = rf(ctx, cid, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetApiDagCidResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, cid, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDAGClientWithResponsesInterface_GetApiDagCidWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiDagCidWithResponse'
type MockDAGClientWithResponsesInterface_GetApiDagCidWithResponse_Call struct {
	*mock.Call
}

// GetApiDagCidWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - cid string
//   - reqEditors ...client.RequestEditorFn
func (_e *MockDAGClientWithResponsesInterface_Expecter) GetApiDagCidWithResponse(ctx interface{}, cid interface{}, reqEditors ...interface{}) *MockDAGClientWithResponsesInterface_GetApiDagCidWithResponse_Call {
	return &MockDAGClientWithResponsesInterface_GetApiDagCidWithResponse_Call{Call: _e.mock.On("GetApiDagCidWithResponse",
		append([]interface{}{ctx, cid}, reqEditors...)...)}
}

func (_c *MockDAGClientWithResponsesInterface_GetApiDagCidWithResponse_Call) Run(run func(ctx context.Context, cid string, reqEditors ...client.RequestEditorFn)) *MockDAGClientWithResponsesInterface_GetApiDagCidWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockDAGClientWithResponsesInterface_GetApiDagCidWithResponse_Call) Return(_a0 *client.GetApiDagCidResponse, _a1 error) *MockDAGClientWithResponsesInterface_GetApiDagCidWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDAGClientWithResponsesInterface_GetApiDagCidWithResponse_Call) RunAndReturn(run func(context.Context, string, ...client.RequestEditorFn) (*client.GetApiDagCidResponse, error)) *MockDAGClientWithResponsesInterface_GetApiDagCidWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDAGClientWithResponsesInterface creates a new instance of MockDAGClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDAGClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDAGClientWithResponsesInterface {
	mock := &MockDAGClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
