// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"os"
	"time"

	"github.com/ipfs/boxo/files"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDirectory creates a new instance of MockDirectory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDirectory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDirectory {
	mock := &MockDirectory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDirectory is an autogenerated mock type for the Directory type
type MockDirectory struct {
	mock.Mock
}

type MockDirectory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDirectory) EXPECT() *MockDirectory_Expecter {
	return &MockDirectory_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockDirectory
func (_mock *MockDirectory) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDirectory_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDirectory_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDirectory_Expecter) Close() *MockDirectory_Close_Call {
	return &MockDirectory_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDirectory_Close_Call) Run(run func()) *MockDirectory_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDirectory_Close_Call) Return(err error) *MockDirectory_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDirectory_Close_Call) RunAndReturn(run func() error) *MockDirectory_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Entries provides a mock function for the type MockDirectory
func (_mock *MockDirectory) Entries() files.DirIterator {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Entries")
	}

	var r0 files.DirIterator
	if returnFunc, ok := ret.Get(0).(func() files.DirIterator); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(files.DirIterator)
		}
	}
	return r0
}

// MockDirectory_Entries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Entries'
type MockDirectory_Entries_Call struct {
	*mock.Call
}

// Entries is a helper method to define mock.On call
func (_e *MockDirectory_Expecter) Entries() *MockDirectory_Entries_Call {
	return &MockDirectory_Entries_Call{Call: _e.mock.On("Entries")}
}

func (_c *MockDirectory_Entries_Call) Run(run func()) *MockDirectory_Entries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDirectory_Entries_Call) Return(dirIterator files.DirIterator) *MockDirectory_Entries_Call {
	_c.Call.Return(dirIterator)
	return _c
}

func (_c *MockDirectory_Entries_Call) RunAndReturn(run func() files.DirIterator) *MockDirectory_Entries_Call {
	_c.Call.Return(run)
	return _c
}

// ModTime provides a mock function for the type MockDirectory
func (_mock *MockDirectory) ModTime() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ModTime")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockDirectory_ModTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModTime'
type MockDirectory_ModTime_Call struct {
	*mock.Call
}

// ModTime is a helper method to define mock.On call
func (_e *MockDirectory_Expecter) ModTime() *MockDirectory_ModTime_Call {
	return &MockDirectory_ModTime_Call{Call: _e.mock.On("ModTime")}
}

func (_c *MockDirectory_ModTime_Call) Run(run func()) *MockDirectory_ModTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDirectory_ModTime_Call) Return(mtime time.Time) *MockDirectory_ModTime_Call {
	_c.Call.Return(mtime)
	return _c
}

func (_c *MockDirectory_ModTime_Call) RunAndReturn(run func() time.Time) *MockDirectory_ModTime_Call {
	_c.Call.Return(run)
	return _c
}

// Mode provides a mock function for the type MockDirectory
func (_mock *MockDirectory) Mode() os.FileMode {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Mode")
	}

	var r0 os.FileMode
	if returnFunc, ok := ret.Get(0).(func() os.FileMode); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(os.FileMode)
	}
	return r0
}

// MockDirectory_Mode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mode'
type MockDirectory_Mode_Call struct {
	*mock.Call
}

// Mode is a helper method to define mock.On call
func (_e *MockDirectory_Expecter) Mode() *MockDirectory_Mode_Call {
	return &MockDirectory_Mode_Call{Call: _e.mock.On("Mode")}
}

func (_c *MockDirectory_Mode_Call) Run(run func()) *MockDirectory_Mode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDirectory_Mode_Call) Return(v os.FileMode) *MockDirectory_Mode_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockDirectory_Mode_Call) RunAndReturn(run func() os.FileMode) *MockDirectory_Mode_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function for the type MockDirectory
func (_mock *MockDirectory) Size() (int64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDirectory_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockDirectory_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockDirectory_Expecter) Size() *MockDirectory_Size_Call {
	return &MockDirectory_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *MockDirectory_Size_Call) Run(run func()) *MockDirectory_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDirectory_Size_Call) Return(n int64, err error) *MockDirectory_Size_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockDirectory_Size_Call) RunAndReturn(run func() (int64, error)) *MockDirectory_Size_Call {
	_c.Call.Return(run)
	return _c
}
