// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ipfs/boxo/files"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDirEntry creates a new instance of MockDirEntry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDirEntry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDirEntry {
	mock := &MockDirEntry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDirEntry is an autogenerated mock type for the DirEntry type
type MockDirEntry struct {
	mock.Mock
}

type MockDirEntry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDirEntry) EXPECT() *MockDirEntry_Expecter {
	return &MockDirEntry_Expecter{mock: &_m.Mock}
}

// Name provides a mock function for the type MockDirEntry
func (_mock *MockDirEntry) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDirEntry_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockDirEntry_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockDirEntry_Expecter) Name() *MockDirEntry_Name_Call {
	return &MockDirEntry_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockDirEntry_Name_Call) Run(run func()) *MockDirEntry_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDirEntry_Name_Call) Return(s string) *MockDirEntry_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDirEntry_Name_Call) RunAndReturn(run func() string) *MockDirEntry_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Node provides a mock function for the type MockDirEntry
func (_mock *MockDirEntry) Node() files.Node {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Node")
	}

	var r0 files.Node
	if returnFunc, ok := ret.Get(0).(func() files.Node); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(files.Node)
		}
	}
	return r0
}

// MockDirEntry_Node_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Node'
type MockDirEntry_Node_Call struct {
	*mock.Call
}

// Node is a helper method to define mock.On call
func (_e *MockDirEntry_Expecter) Node() *MockDirEntry_Node_Call {
	return &MockDirEntry_Node_Call{Call: _e.mock.On("Node")}
}

func (_c *MockDirEntry_Node_Call) Run(run func()) *MockDirEntry_Node_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDirEntry_Node_Call) Return(node files.Node) *MockDirEntry_Node_Call {
	_c.Call.Return(node)
	return _c
}

func (_c *MockDirEntry_Node_Call) RunAndReturn(run func() files.Node) *MockDirEntry_Node_Call {
	_c.Call.Return(run)
	return _c
}
