// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ipfs/boxo/files"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDirIterator creates a new instance of MockDirIterator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDirIterator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDirIterator {
	mock := &MockDirIterator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDirIterator is an autogenerated mock type for the DirIterator type
type MockDirIterator struct {
	mock.Mock
}

type MockDirIterator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDirIterator) EXPECT() *MockDirIterator_Expecter {
	return &MockDirIterator_Expecter{mock: &_m.Mock}
}

// Err provides a mock function for the type MockDirIterator
func (_mock *MockDirIterator) Err() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDirIterator_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type MockDirIterator_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *MockDirIterator_Expecter) Err() *MockDirIterator_Err_Call {
	return &MockDirIterator_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *MockDirIterator_Err_Call) Run(run func()) *MockDirIterator_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDirIterator_Err_Call) Return(err error) *MockDirIterator_Err_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDirIterator_Err_Call) RunAndReturn(run func() error) *MockDirIterator_Err_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockDirIterator
func (_mock *MockDirIterator) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDirIterator_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockDirIterator_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockDirIterator_Expecter) Name() *MockDirIterator_Name_Call {
	return &MockDirIterator_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockDirIterator_Name_Call) Run(run func()) *MockDirIterator_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDirIterator_Name_Call) Return(s string) *MockDirIterator_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDirIterator_Name_Call) RunAndReturn(run func() string) *MockDirIterator_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function for the type MockDirIterator
func (_mock *MockDirIterator) Next() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockDirIterator_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockDirIterator_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *MockDirIterator_Expecter) Next() *MockDirIterator_Next_Call {
	return &MockDirIterator_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *MockDirIterator_Next_Call) Run(run func()) *MockDirIterator_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDirIterator_Next_Call) Return(b bool) *MockDirIterator_Next_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockDirIterator_Next_Call) RunAndReturn(run func() bool) *MockDirIterator_Next_Call {
	_c.Call.Return(run)
	return _c
}

// Node provides a mock function for the type MockDirIterator
func (_mock *MockDirIterator) Node() files.Node {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Node")
	}

	var r0 files.Node
	if returnFunc, ok := ret.Get(0).(func() files.Node); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(files.Node)
		}
	}
	return r0
}

// MockDirIterator_Node_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Node'
type MockDirIterator_Node_Call struct {
	*mock.Call
}

// Node is a helper method to define mock.On call
func (_e *MockDirIterator_Expecter) Node() *MockDirIterator_Node_Call {
	return &MockDirIterator_Node_Call{Call: _e.mock.On("Node")}
}

func (_c *MockDirIterator_Node_Call) Run(run func()) *MockDirIterator_Node_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDirIterator_Node_Call) Return(node files.Node) *MockDirIterator_Node_Call {
	_c.Call.Return(node)
	return _c
}

func (_c *MockDirIterator_Node_Call) RunAndReturn(run func() files.Node) *MockDirIterator_Node_Call {
	_c.Call.Return(run)
	return _c
}
