// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	iofs "io/fs"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockFileInfo is an autogenerated mock type for the FileInfo type
type MockFileInfo struct {
	mock.Mock
}

type MockFileInfo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileInfo) EXPECT() *MockFileInfo_Expecter {
	return &MockFileInfo_Expecter{mock: &_m.Mock}
}

// AbsPath provides a mock function with no fields
func (_m *MockFileInfo) AbsPath() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AbsPath")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockFileInfo_AbsPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbsPath'
type MockFileInfo_AbsPath_Call struct {
	*mock.Call
}

// AbsPath is a helper method to define mock.On call
func (_e *MockFileInfo_Expecter) AbsPath() *MockFileInfo_AbsPath_Call {
	return &MockFileInfo_AbsPath_Call{Call: _e.mock.On("AbsPath")}
}

func (_c *MockFileInfo_AbsPath_Call) Run(run func()) *MockFileInfo_AbsPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileInfo_AbsPath_Call) Return(_a0 string) *MockFileInfo_AbsPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFileInfo_AbsPath_Call) RunAndReturn(run func() string) *MockFileInfo_AbsPath_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockFileInfo) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFileInfo_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockFileInfo_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockFileInfo_Expecter) Close() *MockFileInfo_Close_Call {
	return &MockFileInfo_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockFileInfo_Close_Call) Run(run func()) *MockFileInfo_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileInfo_Close_Call) Return(_a0 error) *MockFileInfo_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFileInfo_Close_Call) RunAndReturn(run func() error) *MockFileInfo_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ModTime provides a mock function with no fields
func (_m *MockFileInfo) ModTime() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ModTime")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// MockFileInfo_ModTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModTime'
type MockFileInfo_ModTime_Call struct {
	*mock.Call
}

// ModTime is a helper method to define mock.On call
func (_e *MockFileInfo_Expecter) ModTime() *MockFileInfo_ModTime_Call {
	return &MockFileInfo_ModTime_Call{Call: _e.mock.On("ModTime")}
}

func (_c *MockFileInfo_ModTime_Call) Run(run func()) *MockFileInfo_ModTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileInfo_ModTime_Call) Return(mtime time.Time) *MockFileInfo_ModTime_Call {
	_c.Call.Return(mtime)
	return _c
}

func (_c *MockFileInfo_ModTime_Call) RunAndReturn(run func() time.Time) *MockFileInfo_ModTime_Call {
	_c.Call.Return(run)
	return _c
}

// Mode provides a mock function with no fields
func (_m *MockFileInfo) Mode() iofs.FileMode {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Mode")
	}

	var r0 iofs.FileMode
	if rf, ok := ret.Get(0).(func() iofs.FileMode); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(iofs.FileMode)
	}

	return r0
}

// MockFileInfo_Mode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mode'
type MockFileInfo_Mode_Call struct {
	*mock.Call
}

// Mode is a helper method to define mock.On call
func (_e *MockFileInfo_Expecter) Mode() *MockFileInfo_Mode_Call {
	return &MockFileInfo_Mode_Call{Call: _e.mock.On("Mode")}
}

func (_c *MockFileInfo_Mode_Call) Run(run func()) *MockFileInfo_Mode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileInfo_Mode_Call) Return(_a0 iofs.FileMode) *MockFileInfo_Mode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFileInfo_Mode_Call) RunAndReturn(run func() iofs.FileMode) *MockFileInfo_Mode_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function with no fields
func (_m *MockFileInfo) Size() (int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileInfo_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockFileInfo_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockFileInfo_Expecter) Size() *MockFileInfo_Size_Call {
	return &MockFileInfo_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *MockFileInfo_Size_Call) Run(run func()) *MockFileInfo_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileInfo_Size_Call) Return(_a0 int64, _a1 error) *MockFileInfo_Size_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileInfo_Size_Call) RunAndReturn(run func() (int64, error)) *MockFileInfo_Size_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function with no fields
func (_m *MockFileInfo) Stat() iofs.FileInfo {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 iofs.FileInfo
	if rf, ok := ret.Get(0).(func() iofs.FileInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iofs.FileInfo)
		}
	}

	return r0
}

// MockFileInfo_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockFileInfo_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
func (_e *MockFileInfo_Expecter) Stat() *MockFileInfo_Stat_Call {
	return &MockFileInfo_Stat_Call{Call: _e.mock.On("Stat")}
}

func (_c *MockFileInfo_Stat_Call) Run(run func()) *MockFileInfo_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileInfo_Stat_Call) Return(_a0 iofs.FileInfo) *MockFileInfo_Stat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFileInfo_Stat_Call) RunAndReturn(run func() iofs.FileInfo) *MockFileInfo_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileInfo creates a new instance of MockFileInfo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileInfo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileInfo {
	mock := &MockFileInfo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
