// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	iofs "io/fs"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockFile is an autogenerated mock type for the File type
type MockFile struct {
	mock.Mock
}

type MockFile_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFile) EXPECT() *MockFile_Expecter {
	return &MockFile_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockFile) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFile_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockFile_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockFile_Expecter) Close() *MockFile_Close_Call {
	return &MockFile_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockFile_Close_Call) Run(run func()) *MockFile_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFile_Close_Call) Return(_a0 error) *MockFile_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFile_Close_Call) RunAndReturn(run func() error) *MockFile_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ModTime provides a mock function with no fields
func (_m *MockFile) ModTime() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ModTime")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// MockFile_ModTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModTime'
type MockFile_ModTime_Call struct {
	*mock.Call
}

// ModTime is a helper method to define mock.On call
func (_e *MockFile_Expecter) ModTime() *MockFile_ModTime_Call {
	return &MockFile_ModTime_Call{Call: _e.mock.On("ModTime")}
}

func (_c *MockFile_ModTime_Call) Run(run func()) *MockFile_ModTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFile_ModTime_Call) Return(mtime time.Time) *MockFile_ModTime_Call {
	_c.Call.Return(mtime)
	return _c
}

func (_c *MockFile_ModTime_Call) RunAndReturn(run func() time.Time) *MockFile_ModTime_Call {
	_c.Call.Return(run)
	return _c
}

// Mode provides a mock function with no fields
func (_m *MockFile) Mode() iofs.FileMode {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Mode")
	}

	var r0 iofs.FileMode
	if rf, ok := ret.Get(0).(func() iofs.FileMode); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(iofs.FileMode)
	}

	return r0
}

// MockFile_Mode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mode'
type MockFile_Mode_Call struct {
	*mock.Call
}

// Mode is a helper method to define mock.On call
func (_e *MockFile_Expecter) Mode() *MockFile_Mode_Call {
	return &MockFile_Mode_Call{Call: _e.mock.On("Mode")}
}

func (_c *MockFile_Mode_Call) Run(run func()) *MockFile_Mode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFile_Mode_Call) Return(_a0 iofs.FileMode) *MockFile_Mode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFile_Mode_Call) RunAndReturn(run func() iofs.FileMode) *MockFile_Mode_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: p
func (_m *MockFile) Read(p []byte) (int, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFile_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockFile_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - p []byte
func (_e *MockFile_Expecter) Read(p interface{}) *MockFile_Read_Call {
	return &MockFile_Read_Call{Call: _e.mock.On("Read", p)}
}

func (_c *MockFile_Read_Call) Run(run func(p []byte)) *MockFile_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockFile_Read_Call) Return(n int, err error) *MockFile_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockFile_Read_Call) RunAndReturn(run func([]byte) (int, error)) *MockFile_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Seek provides a mock function with given fields: offset, whence
func (_m *MockFile) Seek(offset int64, whence int) (int64, error) {
	ret := _m.Called(offset, whence)

	if len(ret) == 0 {
		panic("no return value specified for Seek")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int) (int64, error)); ok {
		return rf(offset, whence)
	}
	if rf, ok := ret.Get(0).(func(int64, int) int64); ok {
		r0 = rf(offset, whence)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int64, int) error); ok {
		r1 = rf(offset, whence)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFile_Seek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seek'
type MockFile_Seek_Call struct {
	*mock.Call
}

// Seek is a helper method to define mock.On call
//   - offset int64
//   - whence int
func (_e *MockFile_Expecter) Seek(offset interface{}, whence interface{}) *MockFile_Seek_Call {
	return &MockFile_Seek_Call{Call: _e.mock.On("Seek", offset, whence)}
}

func (_c *MockFile_Seek_Call) Run(run func(offset int64, whence int)) *MockFile_Seek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int))
	})
	return _c
}

func (_c *MockFile_Seek_Call) Return(_a0 int64, _a1 error) *MockFile_Seek_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFile_Seek_Call) RunAndReturn(run func(int64, int) (int64, error)) *MockFile_Seek_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function with no fields
func (_m *MockFile) Size() (int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFile_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockFile_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockFile_Expecter) Size() *MockFile_Size_Call {
	return &MockFile_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *MockFile_Size_Call) Run(run func()) *MockFile_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFile_Size_Call) Return(_a0 int64, _a1 error) *MockFile_Size_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFile_Size_Call) RunAndReturn(run func() (int64, error)) *MockFile_Size_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFile creates a new instance of MockFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFile {
	mock := &MockFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
