// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"os"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFile creates a new instance of MockFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFile {
	mock := &MockFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFile is an autogenerated mock type for the File type
type MockFile struct {
	mock.Mock
}

type MockFile_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFile) EXPECT() *MockFile_Expecter {
	return &MockFile_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockFile
func (_mock *MockFile) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFile_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockFile_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockFile_Expecter) Close() *MockFile_Close_Call {
	return &MockFile_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockFile_Close_Call) Run(run func()) *MockFile_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFile_Close_Call) Return(err error) *MockFile_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFile_Close_Call) RunAndReturn(run func() error) *MockFile_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ModTime provides a mock function for the type MockFile
func (_mock *MockFile) ModTime() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ModTime")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockFile_ModTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModTime'
type MockFile_ModTime_Call struct {
	*mock.Call
}

// ModTime is a helper method to define mock.On call
func (_e *MockFile_Expecter) ModTime() *MockFile_ModTime_Call {
	return &MockFile_ModTime_Call{Call: _e.mock.On("ModTime")}
}

func (_c *MockFile_ModTime_Call) Run(run func()) *MockFile_ModTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFile_ModTime_Call) Return(mtime time.Time) *MockFile_ModTime_Call {
	_c.Call.Return(mtime)
	return _c
}

func (_c *MockFile_ModTime_Call) RunAndReturn(run func() time.Time) *MockFile_ModTime_Call {
	_c.Call.Return(run)
	return _c
}

// Mode provides a mock function for the type MockFile
func (_mock *MockFile) Mode() os.FileMode {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Mode")
	}

	var r0 os.FileMode
	if returnFunc, ok := ret.Get(0).(func() os.FileMode); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(os.FileMode)
	}
	return r0
}

// MockFile_Mode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mode'
type MockFile_Mode_Call struct {
	*mock.Call
}

// Mode is a helper method to define mock.On call
func (_e *MockFile_Expecter) Mode() *MockFile_Mode_Call {
	return &MockFile_Mode_Call{Call: _e.mock.On("Mode")}
}

func (_c *MockFile_Mode_Call) Run(run func()) *MockFile_Mode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFile_Mode_Call) Return(v os.FileMode) *MockFile_Mode_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockFile_Mode_Call) RunAndReturn(run func() os.FileMode) *MockFile_Mode_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockFile
func (_mock *MockFile) Read(p []byte) (int, error) {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(p)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFile_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockFile_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - p []byte
func (_e *MockFile_Expecter) Read(p any) *MockFile_Read_Call {
	return &MockFile_Read_Call{Call: _e.mock.On("Read", p)}
}

func (_c *MockFile_Read_Call) Run(run func(p []byte)) *MockFile_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFile_Read_Call) Return(n int, err error) *MockFile_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockFile_Read_Call) RunAndReturn(run func(p []byte) (int, error)) *MockFile_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Seek provides a mock function for the type MockFile
func (_mock *MockFile) Seek(offset int64, whence int) (int64, error) {
	ret := _mock.Called(offset, whence)

	if len(ret) == 0 {
		panic("no return value specified for Seek")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, int) (int64, error)); ok {
		return returnFunc(offset, whence)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, int) int64); ok {
		r0 = returnFunc(offset, whence)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(int64, int) error); ok {
		r1 = returnFunc(offset, whence)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFile_Seek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seek'
type MockFile_Seek_Call struct {
	*mock.Call
}

// Seek is a helper method to define mock.On call
//   - offset int64
//   - whence int
func (_e *MockFile_Expecter) Seek(offset any, whence any) *MockFile_Seek_Call {
	return &MockFile_Seek_Call{Call: _e.mock.On("Seek", offset, whence)}
}

func (_c *MockFile_Seek_Call) Run(run func(offset int64, whence int)) *MockFile_Seek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFile_Seek_Call) Return(n int64, err error) *MockFile_Seek_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockFile_Seek_Call) RunAndReturn(run func(offset int64, whence int) (int64, error)) *MockFile_Seek_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function for the type MockFile
func (_mock *MockFile) Size() (int64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFile_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockFile_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockFile_Expecter) Size() *MockFile_Size_Call {
	return &MockFile_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *MockFile_Size_Call) Run(run func()) *MockFile_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFile_Size_Call) Return(n int64, err error) *MockFile_Size_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockFile_Size_Call) RunAndReturn(run func() (int64, error)) *MockFile_Size_Call {
	_c.Call.Return(run)
	return _c
}
