// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/ipfs-sdk/internal/client"
)

// NewMockIPNSClientWithResponsesInterface creates a new instance of MockIPNSClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPNSClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPNSClientWithResponsesInterface {
	mock := &MockIPNSClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPNSClientWithResponsesInterface is an autogenerated mock type for the IPNSClientWithResponsesInterface type
type MockIPNSClientWithResponsesInterface struct {
	mock.Mock
}

type MockIPNSClientWithResponsesInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPNSClientWithResponsesInterface) EXPECT() *MockIPNSClientWithResponsesInterface_Expecter {
	return &MockIPNSClientWithResponsesInterface_Expecter{mock: &_m.Mock}
}

// DeleteApiIpnsKeysIdWithResponse provides a mock function for the type MockIPNSClientWithResponsesInterface
func (_mock *MockIPNSClientWithResponsesInterface) DeleteApiIpnsKeysIdWithResponse(ctx context.Context, id string, reqEditors ...client.RequestEditorFn) (*client.DeleteApiIpnsKeysIdResponse, error) {
	// client.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteApiIpnsKeysIdWithResponse")
	}

	var r0 *client.DeleteApiIpnsKeysIdResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) (*client.DeleteApiIpnsKeysIdResponse, error)); ok {
		return returnFunc(ctx, id, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) *client.DeleteApiIpnsKeysIdResponse); ok {
		r0 = returnFunc(ctx, id, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.DeleteApiIpnsKeysIdResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...client.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, id, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSClientWithResponsesInterface_DeleteApiIpnsKeysIdWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteApiIpnsKeysIdWithResponse'
type MockIPNSClientWithResponsesInterface_DeleteApiIpnsKeysIdWithResponse_Call struct {
	*mock.Call
}

// DeleteApiIpnsKeysIdWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reqEditors ...client.RequestEditorFn
func (_e *MockIPNSClientWithResponsesInterface_Expecter) DeleteApiIpnsKeysIdWithResponse(ctx interface{}, id interface{}, reqEditors ...interface{}) *MockIPNSClientWithResponsesInterface_DeleteApiIpnsKeysIdWithResponse_Call {
	return &MockIPNSClientWithResponsesInterface_DeleteApiIpnsKeysIdWithResponse_Call{Call: _e.mock.On("DeleteApiIpnsKeysIdWithResponse",
		append([]interface{}{ctx, id}, reqEditors...)...)}
}

func (_c *MockIPNSClientWithResponsesInterface_DeleteApiIpnsKeysIdWithResponse_Call) Run(run func(ctx context.Context, id string, reqEditors ...client.RequestEditorFn)) *MockIPNSClientWithResponsesInterface_DeleteApiIpnsKeysIdWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []client.RequestEditorFn
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockIPNSClientWithResponsesInterface_DeleteApiIpnsKeysIdWithResponse_Call) Return(deleteApiIpnsKeysIdResponse *client.DeleteApiIpnsKeysIdResponse, err error) *MockIPNSClientWithResponsesInterface_DeleteApiIpnsKeysIdWithResponse_Call {
	_c.Call.Return(deleteApiIpnsKeysIdResponse, err)
	return _c
}

func (_c *MockIPNSClientWithResponsesInterface_DeleteApiIpnsKeysIdWithResponse_Call) RunAndReturn(run func(ctx context.Context, id string, reqEditors ...client.RequestEditorFn) (*client.DeleteApiIpnsKeysIdResponse, error)) *MockIPNSClientWithResponsesInterface_DeleteApiIpnsKeysIdWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiIpnsKeysIdWithResponse provides a mock function for the type MockIPNSClientWithResponsesInterface
func (_mock *MockIPNSClientWithResponsesInterface) GetApiIpnsKeysIdWithResponse(ctx context.Context, id string, reqEditors ...client.RequestEditorFn) (*client.GetApiIpnsKeysIdResponse, error) {
	// client.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiIpnsKeysIdWithResponse")
	}

	var r0 *client.GetApiIpnsKeysIdResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) (*client.GetApiIpnsKeysIdResponse, error)); ok {
		return returnFunc(ctx, id, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) *client.GetApiIpnsKeysIdResponse); ok {
		r0 = returnFunc(ctx, id, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetApiIpnsKeysIdResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...client.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, id, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSClientWithResponsesInterface_GetApiIpnsKeysIdWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiIpnsKeysIdWithResponse'
type MockIPNSClientWithResponsesInterface_GetApiIpnsKeysIdWithResponse_Call struct {
	*mock.Call
}

// GetApiIpnsKeysIdWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reqEditors ...client.RequestEditorFn
func (_e *MockIPNSClientWithResponsesInterface_Expecter) GetApiIpnsKeysIdWithResponse(ctx interface{}, id interface{}, reqEditors ...interface{}) *MockIPNSClientWithResponsesInterface_GetApiIpnsKeysIdWithResponse_Call {
	return &MockIPNSClientWithResponsesInterface_GetApiIpnsKeysIdWithResponse_Call{Call: _e.mock.On("GetApiIpnsKeysIdWithResponse",
		append([]interface{}{ctx, id}, reqEditors...)...)}
}

func (_c *MockIPNSClientWithResponsesInterface_GetApiIpnsKeysIdWithResponse_Call) Run(run func(ctx context.Context, id string, reqEditors ...client.RequestEditorFn)) *MockIPNSClientWithResponsesInterface_GetApiIpnsKeysIdWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []client.RequestEditorFn
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockIPNSClientWithResponsesInterface_GetApiIpnsKeysIdWithResponse_Call) Return(getApiIpnsKeysIdResponse *client.GetApiIpnsKeysIdResponse, err error) *MockIPNSClientWithResponsesInterface_GetApiIpnsKeysIdWithResponse_Call {
	_c.Call.Return(getApiIpnsKeysIdResponse, err)
	return _c
}

func (_c *MockIPNSClientWithResponsesInterface_GetApiIpnsKeysIdWithResponse_Call) RunAndReturn(run func(ctx context.Context, id string, reqEditors ...client.RequestEditorFn) (*client.GetApiIpnsKeysIdResponse, error)) *MockIPNSClientWithResponsesInterface_GetApiIpnsKeysIdWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiIpnsKeysWithResponse provides a mock function for the type MockIPNSClientWithResponsesInterface
func (_mock *MockIPNSClientWithResponsesInterface) GetApiIpnsKeysWithResponse(ctx context.Context, reqEditors ...client.RequestEditorFn) (*client.GetApiIpnsKeysResponse, error) {
	// client.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiIpnsKeysWithResponse")
	}

	var r0 *client.GetApiIpnsKeysResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...client.RequestEditorFn) (*client.GetApiIpnsKeysResponse, error)); ok {
		return returnFunc(ctx, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...client.RequestEditorFn) *client.GetApiIpnsKeysResponse); ok {
		r0 = returnFunc(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetApiIpnsKeysResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...client.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSClientWithResponsesInterface_GetApiIpnsKeysWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiIpnsKeysWithResponse'
type MockIPNSClientWithResponsesInterface_GetApiIpnsKeysWithResponse_Call struct {
	*mock.Call
}

// GetApiIpnsKeysWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...client.RequestEditorFn
func (_e *MockIPNSClientWithResponsesInterface_Expecter) GetApiIpnsKeysWithResponse(ctx interface{}, reqEditors ...interface{}) *MockIPNSClientWithResponsesInterface_GetApiIpnsKeysWithResponse_Call {
	return &MockIPNSClientWithResponsesInterface_GetApiIpnsKeysWithResponse_Call{Call: _e.mock.On("GetApiIpnsKeysWithResponse",
		append([]interface{}{ctx}, reqEditors...)...)}
}

func (_c *MockIPNSClientWithResponsesInterface_GetApiIpnsKeysWithResponse_Call) Run(run func(ctx context.Context, reqEditors ...client.RequestEditorFn)) *MockIPNSClientWithResponsesInterface_GetApiIpnsKeysWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []client.RequestEditorFn
		variadicArgs := make([]client.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockIPNSClientWithResponsesInterface_GetApiIpnsKeysWithResponse_Call) Return(getApiIpnsKeysResponse *client.GetApiIpnsKeysResponse, err error) *MockIPNSClientWithResponsesInterface_GetApiIpnsKeysWithResponse_Call {
	_c.Call.Return(getApiIpnsKeysResponse, err)
	return _c
}

func (_c *MockIPNSClientWithResponsesInterface_GetApiIpnsKeysWithResponse_Call) RunAndReturn(run func(ctx context.Context, reqEditors ...client.RequestEditorFn) (*client.GetApiIpnsKeysResponse, error)) *MockIPNSClientWithResponsesInterface_GetApiIpnsKeysWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiIpnsResolveNameWithResponse provides a mock function for the type MockIPNSClientWithResponsesInterface
func (_mock *MockIPNSClientWithResponsesInterface) GetApiIpnsResolveNameWithResponse(ctx context.Context, name string, params *client.GetApiIpnsResolveNameParams, reqEditors ...client.RequestEditorFn) (*client.GetApiIpnsResolveNameResponse, error) {
	// client.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiIpnsResolveNameWithResponse")
	}

	var r0 *client.GetApiIpnsResolveNameResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *client.GetApiIpnsResolveNameParams, ...client.RequestEditorFn) (*client.GetApiIpnsResolveNameResponse, error)); ok {
		return returnFunc(ctx, name, params, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *client.GetApiIpnsResolveNameParams, ...client.RequestEditorFn) *client.GetApiIpnsResolveNameResponse); ok {
		r0 = returnFunc(ctx, name, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetApiIpnsResolveNameResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *client.GetApiIpnsResolveNameParams, ...client.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, name, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSClientWithResponsesInterface_GetApiIpnsResolveNameWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiIpnsResolveNameWithResponse'
type MockIPNSClientWithResponsesInterface_GetApiIpnsResolveNameWithResponse_Call struct {
	*mock.Call
}

// GetApiIpnsResolveNameWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - params *client.GetApiIpnsResolveNameParams
//   - reqEditors ...client.RequestEditorFn
func (_e *MockIPNSClientWithResponsesInterface_Expecter) GetApiIpnsResolveNameWithResponse(ctx interface{}, name interface{}, params interface{}, reqEditors ...interface{}) *MockIPNSClientWithResponsesInterface_GetApiIpnsResolveNameWithResponse_Call {
	return &MockIPNSClientWithResponsesInterface_GetApiIpnsResolveNameWithResponse_Call{Call: _e.mock.On("GetApiIpnsResolveNameWithResponse",
		append([]interface{}{ctx, name, params}, reqEditors...)...)}
}

func (_c *MockIPNSClientWithResponsesInterface_GetApiIpnsResolveNameWithResponse_Call) Run(run func(ctx context.Context, name string, params *client.GetApiIpnsResolveNameParams, reqEditors ...client.RequestEditorFn)) *MockIPNSClientWithResponsesInterface_GetApiIpnsResolveNameWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *client.GetApiIpnsResolveNameParams
		if args[2] != nil {
			arg2 = args[2].(*client.GetApiIpnsResolveNameParams)
		}
		var arg3 []client.RequestEditorFn
		variadicArgs := make([]client.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockIPNSClientWithResponsesInterface_GetApiIpnsResolveNameWithResponse_Call) Return(getApiIpnsResolveNameResponse *client.GetApiIpnsResolveNameResponse, err error) *MockIPNSClientWithResponsesInterface_GetApiIpnsResolveNameWithResponse_Call {
	_c.Call.Return(getApiIpnsResolveNameResponse, err)
	return _c
}

func (_c *MockIPNSClientWithResponsesInterface_GetApiIpnsResolveNameWithResponse_Call) RunAndReturn(run func(ctx context.Context, name string, params *client.GetApiIpnsResolveNameParams, reqEditors ...client.RequestEditorFn) (*client.GetApiIpnsResolveNameResponse, error)) *MockIPNSClientWithResponsesInterface_GetApiIpnsResolveNameWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostApiIpnsKeysIdRepublishWithResponse provides a mock function for the type MockIPNSClientWithResponsesInterface
func (_mock *MockIPNSClientWithResponsesInterface) PostApiIpnsKeysIdRepublishWithResponse(ctx context.Context, id string, reqEditors ...client.RequestEditorFn) (*client.PostApiIpnsKeysIdRepublishResponse, error) {
	// client.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostApiIpnsKeysIdRepublishWithResponse")
	}

	var r0 *client.PostApiIpnsKeysIdRepublishResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) (*client.PostApiIpnsKeysIdRepublishResponse, error)); ok {
		return returnFunc(ctx, id, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) *client.PostApiIpnsKeysIdRepublishResponse); ok {
		r0 = returnFunc(ctx, id, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PostApiIpnsKeysIdRepublishResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...client.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, id, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSClientWithResponsesInterface_PostApiIpnsKeysIdRepublishWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostApiIpnsKeysIdRepublishWithResponse'
type MockIPNSClientWithResponsesInterface_PostApiIpnsKeysIdRepublishWithResponse_Call struct {
	*mock.Call
}

// PostApiIpnsKeysIdRepublishWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reqEditors ...client.RequestEditorFn
func (_e *MockIPNSClientWithResponsesInterface_Expecter) PostApiIpnsKeysIdRepublishWithResponse(ctx interface{}, id interface{}, reqEditors ...interface{}) *MockIPNSClientWithResponsesInterface_PostApiIpnsKeysIdRepublishWithResponse_Call {
	return &MockIPNSClientWithResponsesInterface_PostApiIpnsKeysIdRepublishWithResponse_Call{Call: _e.mock.On("PostApiIpnsKeysIdRepublishWithResponse",
		append([]interface{}{ctx, id}, reqEditors...)...)}
}

func (_c *MockIPNSClientWithResponsesInterface_PostApiIpnsKeysIdRepublishWithResponse_Call) Run(run func(ctx context.Context, id string, reqEditors ...client.RequestEditorFn)) *MockIPNSClientWithResponsesInterface_PostApiIpnsKeysIdRepublishWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []client.RequestEditorFn
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockIPNSClientWithResponsesInterface_PostApiIpnsKeysIdRepublishWithResponse_Call) Return(postApiIpnsKeysIdRepublishResponse *client.PostApiIpnsKeysIdRepublishResponse, err error) *MockIPNSClientWithResponsesInterface_PostApiIpnsKeysIdRepublishWithResponse_Call {
	_c.Call.Return(postApiIpnsKeysIdRepublishResponse, err)
	return _c
}

func (_c *MockIPNSClientWithResponsesInterface_PostApiIpnsKeysIdRepublishWithResponse_Call) RunAndReturn(run func(ctx context.Context, id string, reqEditors ...client.RequestEditorFn) (*client.PostApiIpnsKeysIdRepublishResponse, error)) *MockIPNSClientWithResponsesInterface_PostApiIpnsKeysIdRepublishWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostApiIpnsKeysWithResponse provides a mock function for the type MockIPNSClientWithResponsesInterface
func (_mock *MockIPNSClientWithResponsesInterface) PostApiIpnsKeysWithResponse(ctx context.Context, body client.IPNSKeyRequest, reqEditors ...client.RequestEditorFn) (*client.PostApiIpnsKeysResponse, error) {
	// client.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostApiIpnsKeysWithResponse")
	}

	var r0 *client.PostApiIpnsKeysResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.IPNSKeyRequest, ...client.RequestEditorFn) (*client.PostApiIpnsKeysResponse, error)); ok {
		return returnFunc(ctx, body, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.IPNSKeyRequest, ...client.RequestEditorFn) *client.PostApiIpnsKeysResponse); ok {
		r0 = returnFunc(ctx, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PostApiIpnsKeysResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.IPNSKeyRequest, ...client.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSClientWithResponsesInterface_PostApiIpnsKeysWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostApiIpnsKeysWithResponse'
type MockIPNSClientWithResponsesInterface_PostApiIpnsKeysWithResponse_Call struct {
	*mock.Call
}

// PostApiIpnsKeysWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - body client.IPNSKeyRequest
//   - reqEditors ...client.RequestEditorFn
func (_e *MockIPNSClientWithResponsesInterface_Expecter) PostApiIpnsKeysWithResponse(ctx interface{}, body interface{}, reqEditors ...interface{}) *MockIPNSClientWithResponsesInterface_PostApiIpnsKeysWithResponse_Call {
	return &MockIPNSClientWithResponsesInterface_PostApiIpnsKeysWithResponse_Call{Call: _e.mock.On("PostApiIpnsKeysWithResponse",
		append([]interface{}{ctx, body}, reqEditors...)...)}
}

func (_c *MockIPNSClientWithResponsesInterface_PostApiIpnsKeysWithResponse_Call) Run(run func(ctx context.Context, body client.IPNSKeyRequest, reqEditors ...client.RequestEditorFn)) *MockIPNSClientWithResponsesInterface_PostApiIpnsKeysWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.IPNSKeyRequest
		if args[1] != nil {
			arg1 = args[1].(client.IPNSKeyRequest)
		}
		var arg2 []client.RequestEditorFn
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockIPNSClientWithResponsesInterface_PostApiIpnsKeysWithResponse_Call) Return(postApiIpnsKeysResponse *client.PostApiIpnsKeysResponse, err error) *MockIPNSClientWithResponsesInterface_PostApiIpnsKeysWithResponse_Call {
	_c.Call.Return(postApiIpnsKeysResponse, err)
	return _c
}

func (_c *MockIPNSClientWithResponsesInterface_PostApiIpnsKeysWithResponse_Call) RunAndReturn(run func(ctx context.Context, body client.IPNSKeyRequest, reqEditors ...client.RequestEditorFn) (*client.PostApiIpnsKeysResponse, error)) *MockIPNSClientWithResponsesInterface_PostApiIpnsKeysWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostApiIpnsPublishWithResponse provides a mock function for the type MockIPNSClientWithResponsesInterface
func (_mock *MockIPNSClientWithResponsesInterface) PostApiIpnsPublishWithResponse(ctx context.Context, body client.IPNSPublishRequest, reqEditors ...client.RequestEditorFn) (*client.PostApiIpnsPublishResponse, error) {
	// client.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostApiIpnsPublishWithResponse")
	}

	var r0 *client.PostApiIpnsPublishResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.IPNSPublishRequest, ...client.RequestEditorFn) (*client.PostApiIpnsPublishResponse, error)); ok {
		return returnFunc(ctx, body, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.IPNSPublishRequest, ...client.RequestEditorFn) *client.PostApiIpnsPublishResponse); ok {
		r0 = returnFunc(ctx, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PostApiIpnsPublishResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.IPNSPublishRequest, ...client.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSClientWithResponsesInterface_PostApiIpnsPublishWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostApiIpnsPublishWithResponse'
type MockIPNSClientWithResponsesInterface_PostApiIpnsPublishWithResponse_Call struct {
	*mock.Call
}

// PostApiIpnsPublishWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - body client.IPNSPublishRequest
//   - reqEditors ...client.RequestEditorFn
func (_e *MockIPNSClientWithResponsesInterface_Expecter) PostApiIpnsPublishWithResponse(ctx interface{}, body interface{}, reqEditors ...interface{}) *MockIPNSClientWithResponsesInterface_PostApiIpnsPublishWithResponse_Call {
	return &MockIPNSClientWithResponsesInterface_PostApiIpnsPublishWithResponse_Call{Call: _e.mock.On("PostApiIpnsPublishWithResponse",
		append([]interface{}{ctx, body}, reqEditors...)...)}
}

func (_c *MockIPNSClientWithResponsesInterface_PostApiIpnsPublishWithResponse_Call) Run(run func(ctx context.Context, body client.IPNSPublishRequest, reqEditors ...client.RequestEditorFn)) *MockIPNSClientWithResponsesInterface_PostApiIpnsPublishWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.IPNSPublishRequest
		if args[1] != nil {
			arg1 = args[1].(client.IPNSPublishRequest)
		}
		var arg2 []client.RequestEditorFn
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockIPNSClientWithResponsesInterface_PostApiIpnsPublishWithResponse_Call) Return(postApiIpnsPublishResponse *client.PostApiIpnsPublishResponse, err error) *MockIPNSClientWithResponsesInterface_PostApiIpnsPublishWithResponse_Call {
	_c.Call.Return(postApiIpnsPublishResponse, err)
	return _c
}

func (_c *MockIPNSClientWithResponsesInterface_PostApiIpnsPublishWithResponse_Call) RunAndReturn(run func(ctx context.Context, body client.IPNSPublishRequest, reqEditors ...client.RequestEditorFn) (*client.PostApiIpnsPublishResponse, error)) *MockIPNSClientWithResponsesInterface_PostApiIpnsPublishWithResponse_Call {
	_c.Call.Return(run)
	return _c
}
