// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	client "go.lumeweb.com/ipfs-sdk/internal/client"

	mock "github.com/stretchr/testify/mock"
)

// MockMetaClientWithResponsesInterface is an autogenerated mock type for the MetaClientWithResponsesInterface type
type MockMetaClientWithResponsesInterface struct {
	mock.Mock
}

type MockMetaClientWithResponsesInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetaClientWithResponsesInterface) EXPECT() *MockMetaClientWithResponsesInterface_Expecter {
	return &MockMetaClientWithResponsesInterface_Expecter{mock: &_m.Mock}
}

// GetApiExportCidCidDagWithResponse provides a mock function with given fields: ctx, cid, reqEditors
func (_m *MockMetaClientWithResponsesInterface) GetApiExportCidCidDagWithResponse(ctx context.Context, cid string, reqEditors ...client.RequestEditorFn) (*client.GetApiExportCidCidDagResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, cid)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiExportCidCidDagWithResponse")
	}

	var r0 *client.GetApiExportCidCidDagResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) (*client.GetApiExportCidCidDagResponse, error)); ok {
		return rf(ctx, cid, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) *client.GetApiExportCidCidDagResponse); ok {
		r0 = rf(ctx, cid, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetApiExportCidCidDagResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, cid, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMetaClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiExportCidCidDagWithResponse'
type MockMetaClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call struct {
	*mock.Call
}

// GetApiExportCidCidDagWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - cid string
//   - reqEditors ...client.RequestEditorFn
func (_e *MockMetaClientWithResponsesInterface_Expecter) GetApiExportCidCidDagWithResponse(ctx interface{}, cid interface{}, reqEditors ...interface{}) *MockMetaClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call {
	return &MockMetaClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call{Call: _e.mock.On("GetApiExportCidCidDagWithResponse",
		append([]interface{}{ctx, cid}, reqEditors...)...)}
}

func (_c *MockMetaClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call) Run(run func(ctx context.Context, cid string, reqEditors ...client.RequestEditorFn)) *MockMetaClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockMetaClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call) Return(_a0 *client.GetApiExportCidCidDagResponse, _a1 error) *MockMetaClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMetaClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call) RunAndReturn(run func(context.Context, string, ...client.RequestEditorFn) (*client.GetApiExportCidCidDagResponse, error)) *MockMetaClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiExportCidCidSiaObjectWithResponse provides a mock function with given fields: ctx, cid, reqEditors
func (_m *MockMetaClientWithResponsesInterface) GetApiExportCidCidSiaObjectWithResponse(ctx context.Context, cid string, reqEditors ...client.RequestEditorFn) (*client.GetApiExportCidCidSiaObjectResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, cid)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiExportCidCidSiaObjectWithResponse")
	}

	var r0 *client.GetApiExportCidCidSiaObjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) (*client.GetApiExportCidCidSiaObjectResponse, error)); ok {
		return rf(ctx, cid, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) *client.GetApiExportCidCidSiaObjectResponse); ok {
		r0 = rf(ctx, cid, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetApiExportCidCidSiaObjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, cid, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMetaClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiExportCidCidSiaObjectWithResponse'
type MockMetaClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call struct {
	*mock.Call
}

// GetApiExportCidCidSiaObjectWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - cid string
//   - reqEditors ...client.RequestEditorFn
func (_e *MockMetaClientWithResponsesInterface_Expecter) GetApiExportCidCidSiaObjectWithResponse(ctx interface{}, cid interface{}, reqEditors ...interface{}) *MockMetaClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call {
	return &MockMetaClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call{Call: _e.mock.On("GetApiExportCidCidSiaObjectWithResponse",
		append([]interface{}{ctx, cid}, reqEditors...)...)}
}

func (_c *MockMetaClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call) Run(run func(ctx context.Context, cid string, reqEditors ...client.RequestEditorFn)) *MockMetaClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockMetaClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call) Return(_a0 *client.GetApiExportCidCidSiaObjectResponse, _a1 error) *MockMetaClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMetaClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call) RunAndReturn(run func(context.Context, string, ...client.RequestEditorFn) (*client.GetApiExportCidCidSiaObjectResponse, error)) *MockMetaClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetaClientWithResponsesInterface creates a new instance of MockMetaClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetaClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetaClientWithResponsesInterface {
	mock := &MockMetaClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
