// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	iofs "io/fs"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockNode is an autogenerated mock type for the Node type
type MockNode struct {
	mock.Mock
}

type MockNode_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNode) EXPECT() *MockNode_Expecter {
	return &MockNode_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockNode) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNode_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockNode_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockNode_Expecter) Close() *MockNode_Close_Call {
	return &MockNode_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockNode_Close_Call) Run(run func()) *MockNode_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNode_Close_Call) Return(_a0 error) *MockNode_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNode_Close_Call) RunAndReturn(run func() error) *MockNode_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ModTime provides a mock function with no fields
func (_m *MockNode) ModTime() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ModTime")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// MockNode_ModTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModTime'
type MockNode_ModTime_Call struct {
	*mock.Call
}

// ModTime is a helper method to define mock.On call
func (_e *MockNode_Expecter) ModTime() *MockNode_ModTime_Call {
	return &MockNode_ModTime_Call{Call: _e.mock.On("ModTime")}
}

func (_c *MockNode_ModTime_Call) Run(run func()) *MockNode_ModTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNode_ModTime_Call) Return(mtime time.Time) *MockNode_ModTime_Call {
	_c.Call.Return(mtime)
	return _c
}

func (_c *MockNode_ModTime_Call) RunAndReturn(run func() time.Time) *MockNode_ModTime_Call {
	_c.Call.Return(run)
	return _c
}

// Mode provides a mock function with no fields
func (_m *MockNode) Mode() iofs.FileMode {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Mode")
	}

	var r0 iofs.FileMode
	if rf, ok := ret.Get(0).(func() iofs.FileMode); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(iofs.FileMode)
	}

	return r0
}

// MockNode_Mode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mode'
type MockNode_Mode_Call struct {
	*mock.Call
}

// Mode is a helper method to define mock.On call
func (_e *MockNode_Expecter) Mode() *MockNode_Mode_Call {
	return &MockNode_Mode_Call{Call: _e.mock.On("Mode")}
}

func (_c *MockNode_Mode_Call) Run(run func()) *MockNode_Mode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNode_Mode_Call) Return(_a0 iofs.FileMode) *MockNode_Mode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNode_Mode_Call) RunAndReturn(run func() iofs.FileMode) *MockNode_Mode_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function with no fields
func (_m *MockNode) Size() (int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNode_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockNode_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockNode_Expecter) Size() *MockNode_Size_Call {
	return &MockNode_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *MockNode_Size_Call) Run(run func()) *MockNode_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNode_Size_Call) Return(_a0 int64, _a1 error) *MockNode_Size_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNode_Size_Call) RunAndReturn(run func() (int64, error)) *MockNode_Size_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNode creates a new instance of MockNode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNode(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNode {
	mock := &MockNode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
