// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	client "go.lumeweb.com/ipfs-sdk/internal/client"

	mock "github.com/stretchr/testify/mock"
)

// MockWebsitesClientWithResponsesInterface is an autogenerated mock type for the WebsitesClientWithResponsesInterface type
type MockWebsitesClientWithResponsesInterface struct {
	mock.Mock
}

type MockWebsitesClientWithResponsesInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebsitesClientWithResponsesInterface) EXPECT() *MockWebsitesClientWithResponsesInterface_Expecter {
	return &MockWebsitesClientWithResponsesInterface_Expecter{mock: &_m.Mock}
}

// DeleteApiWebsitesIdDomainsDomainIdWithResponse provides a mock function with given fields: ctx, id, domainId, reqEditors
func (_m *MockWebsitesClientWithResponsesInterface) DeleteApiWebsitesIdDomainsDomainIdWithResponse(ctx context.Context, id string, domainId string, reqEditors ...client.RequestEditorFn) (*client.DeleteApiWebsitesIdDomainsDomainIdResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id, domainId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteApiWebsitesIdDomainsDomainIdWithResponse")
	}

	var r0 *client.DeleteApiWebsitesIdDomainsDomainIdResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...client.RequestEditorFn) (*client.DeleteApiWebsitesIdDomainsDomainIdResponse, error)); ok {
		return rf(ctx, id, domainId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...client.RequestEditorFn) *client.DeleteApiWebsitesIdDomainsDomainIdResponse); ok {
		r0 = rf(ctx, id, domainId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.DeleteApiWebsitesIdDomainsDomainIdResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, id, domainId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesClientWithResponsesInterface_DeleteApiWebsitesIdDomainsDomainIdWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteApiWebsitesIdDomainsDomainIdWithResponse'
type MockWebsitesClientWithResponsesInterface_DeleteApiWebsitesIdDomainsDomainIdWithResponse_Call struct {
	*mock.Call
}

// DeleteApiWebsitesIdDomainsDomainIdWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - domainId string
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWebsitesClientWithResponsesInterface_Expecter) DeleteApiWebsitesIdDomainsDomainIdWithResponse(ctx interface{}, id interface{}, domainId interface{}, reqEditors ...interface{}) *MockWebsitesClientWithResponsesInterface_DeleteApiWebsitesIdDomainsDomainIdWithResponse_Call {
	return &MockWebsitesClientWithResponsesInterface_DeleteApiWebsitesIdDomainsDomainIdWithResponse_Call{Call: _e.mock.On("DeleteApiWebsitesIdDomainsDomainIdWithResponse",
		append([]interface{}{ctx, id, domainId}, reqEditors...)...)}
}

func (_c *MockWebsitesClientWithResponsesInterface_DeleteApiWebsitesIdDomainsDomainIdWithResponse_Call) Run(run func(ctx context.Context, id string, domainId string, reqEditors ...client.RequestEditorFn)) *MockWebsitesClientWithResponsesInterface_DeleteApiWebsitesIdDomainsDomainIdWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_DeleteApiWebsitesIdDomainsDomainIdWithResponse_Call) Return(_a0 *client.DeleteApiWebsitesIdDomainsDomainIdResponse, _a1 error) *MockWebsitesClientWithResponsesInterface_DeleteApiWebsitesIdDomainsDomainIdWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_DeleteApiWebsitesIdDomainsDomainIdWithResponse_Call) RunAndReturn(run func(context.Context, string, string, ...client.RequestEditorFn) (*client.DeleteApiWebsitesIdDomainsDomainIdResponse, error)) *MockWebsitesClientWithResponsesInterface_DeleteApiWebsitesIdDomainsDomainIdWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteApiWebsitesIdWithResponse provides a mock function with given fields: ctx, id, reqEditors
func (_m *MockWebsitesClientWithResponsesInterface) DeleteApiWebsitesIdWithResponse(ctx context.Context, id string, reqEditors ...client.RequestEditorFn) (*client.DeleteApiWebsitesIdResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteApiWebsitesIdWithResponse")
	}

	var r0 *client.DeleteApiWebsitesIdResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) (*client.DeleteApiWebsitesIdResponse, error)); ok {
		return rf(ctx, id, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) *client.DeleteApiWebsitesIdResponse); ok {
		r0 = rf(ctx, id, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.DeleteApiWebsitesIdResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, id, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesClientWithResponsesInterface_DeleteApiWebsitesIdWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteApiWebsitesIdWithResponse'
type MockWebsitesClientWithResponsesInterface_DeleteApiWebsitesIdWithResponse_Call struct {
	*mock.Call
}

// DeleteApiWebsitesIdWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWebsitesClientWithResponsesInterface_Expecter) DeleteApiWebsitesIdWithResponse(ctx interface{}, id interface{}, reqEditors ...interface{}) *MockWebsitesClientWithResponsesInterface_DeleteApiWebsitesIdWithResponse_Call {
	return &MockWebsitesClientWithResponsesInterface_DeleteApiWebsitesIdWithResponse_Call{Call: _e.mock.On("DeleteApiWebsitesIdWithResponse",
		append([]interface{}{ctx, id}, reqEditors...)...)}
}

func (_c *MockWebsitesClientWithResponsesInterface_DeleteApiWebsitesIdWithResponse_Call) Run(run func(ctx context.Context, id string, reqEditors ...client.RequestEditorFn)) *MockWebsitesClientWithResponsesInterface_DeleteApiWebsitesIdWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_DeleteApiWebsitesIdWithResponse_Call) Return(_a0 *client.DeleteApiWebsitesIdResponse, _a1 error) *MockWebsitesClientWithResponsesInterface_DeleteApiWebsitesIdWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_DeleteApiWebsitesIdWithResponse_Call) RunAndReturn(run func(context.Context, string, ...client.RequestEditorFn) (*client.DeleteApiWebsitesIdResponse, error)) *MockWebsitesClientWithResponsesInterface_DeleteApiWebsitesIdWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiWebsitesConfigWithResponse provides a mock function with given fields: ctx, reqEditors
func (_m *MockWebsitesClientWithResponsesInterface) GetApiWebsitesConfigWithResponse(ctx context.Context, reqEditors ...client.RequestEditorFn) (*client.GetApiWebsitesConfigResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiWebsitesConfigWithResponse")
	}

	var r0 *client.GetApiWebsitesConfigResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...client.RequestEditorFn) (*client.GetApiWebsitesConfigResponse, error)); ok {
		return rf(ctx, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...client.RequestEditorFn) *client.GetApiWebsitesConfigResponse); ok {
		r0 = rf(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetApiWebsitesConfigResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesClientWithResponsesInterface_GetApiWebsitesConfigWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiWebsitesConfigWithResponse'
type MockWebsitesClientWithResponsesInterface_GetApiWebsitesConfigWithResponse_Call struct {
	*mock.Call
}

// GetApiWebsitesConfigWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWebsitesClientWithResponsesInterface_Expecter) GetApiWebsitesConfigWithResponse(ctx interface{}, reqEditors ...interface{}) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesConfigWithResponse_Call {
	return &MockWebsitesClientWithResponsesInterface_GetApiWebsitesConfigWithResponse_Call{Call: _e.mock.On("GetApiWebsitesConfigWithResponse",
		append([]interface{}{ctx}, reqEditors...)...)}
}

func (_c *MockWebsitesClientWithResponsesInterface_GetApiWebsitesConfigWithResponse_Call) Run(run func(ctx context.Context, reqEditors ...client.RequestEditorFn)) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesConfigWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_GetApiWebsitesConfigWithResponse_Call) Return(_a0 *client.GetApiWebsitesConfigResponse, _a1 error) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesConfigWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_GetApiWebsitesConfigWithResponse_Call) RunAndReturn(run func(context.Context, ...client.RequestEditorFn) (*client.GetApiWebsitesConfigResponse, error)) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesConfigWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiWebsitesDomainSslStatusWithResponse provides a mock function with given fields: ctx, domain, reqEditors
func (_m *MockWebsitesClientWithResponsesInterface) GetApiWebsitesDomainSslStatusWithResponse(ctx context.Context, domain string, reqEditors ...client.RequestEditorFn) (*client.GetApiWebsitesDomainSslStatusResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, domain)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiWebsitesDomainSslStatusWithResponse")
	}

	var r0 *client.GetApiWebsitesDomainSslStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) (*client.GetApiWebsitesDomainSslStatusResponse, error)); ok {
		return rf(ctx, domain, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) *client.GetApiWebsitesDomainSslStatusResponse); ok {
		r0 = rf(ctx, domain, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetApiWebsitesDomainSslStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, domain, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesClientWithResponsesInterface_GetApiWebsitesDomainSslStatusWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiWebsitesDomainSslStatusWithResponse'
type MockWebsitesClientWithResponsesInterface_GetApiWebsitesDomainSslStatusWithResponse_Call struct {
	*mock.Call
}

// GetApiWebsitesDomainSslStatusWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWebsitesClientWithResponsesInterface_Expecter) GetApiWebsitesDomainSslStatusWithResponse(ctx interface{}, domain interface{}, reqEditors ...interface{}) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesDomainSslStatusWithResponse_Call {
	return &MockWebsitesClientWithResponsesInterface_GetApiWebsitesDomainSslStatusWithResponse_Call{Call: _e.mock.On("GetApiWebsitesDomainSslStatusWithResponse",
		append([]interface{}{ctx, domain}, reqEditors...)...)}
}

func (_c *MockWebsitesClientWithResponsesInterface_GetApiWebsitesDomainSslStatusWithResponse_Call) Run(run func(ctx context.Context, domain string, reqEditors ...client.RequestEditorFn)) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesDomainSslStatusWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_GetApiWebsitesDomainSslStatusWithResponse_Call) Return(_a0 *client.GetApiWebsitesDomainSslStatusResponse, _a1 error) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesDomainSslStatusWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_GetApiWebsitesDomainSslStatusWithResponse_Call) RunAndReturn(run func(context.Context, string, ...client.RequestEditorFn) (*client.GetApiWebsitesDomainSslStatusResponse, error)) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesDomainSslStatusWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiWebsitesIdDomainsDomainIdDnsRequirementsWithResponse provides a mock function with given fields: ctx, id, domainId, reqEditors
func (_m *MockWebsitesClientWithResponsesInterface) GetApiWebsitesIdDomainsDomainIdDnsRequirementsWithResponse(ctx context.Context, id string, domainId string, reqEditors ...client.RequestEditorFn) (*client.GetApiWebsitesIdDomainsDomainIdDnsRequirementsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id, domainId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiWebsitesIdDomainsDomainIdDnsRequirementsWithResponse")
	}

	var r0 *client.GetApiWebsitesIdDomainsDomainIdDnsRequirementsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...client.RequestEditorFn) (*client.GetApiWebsitesIdDomainsDomainIdDnsRequirementsResponse, error)); ok {
		return rf(ctx, id, domainId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...client.RequestEditorFn) *client.GetApiWebsitesIdDomainsDomainIdDnsRequirementsResponse); ok {
		r0 = rf(ctx, id, domainId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetApiWebsitesIdDomainsDomainIdDnsRequirementsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, id, domainId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdDomainsDomainIdDnsRequirementsWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiWebsitesIdDomainsDomainIdDnsRequirementsWithResponse'
type MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdDomainsDomainIdDnsRequirementsWithResponse_Call struct {
	*mock.Call
}

// GetApiWebsitesIdDomainsDomainIdDnsRequirementsWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - domainId string
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWebsitesClientWithResponsesInterface_Expecter) GetApiWebsitesIdDomainsDomainIdDnsRequirementsWithResponse(ctx interface{}, id interface{}, domainId interface{}, reqEditors ...interface{}) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdDomainsDomainIdDnsRequirementsWithResponse_Call {
	return &MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdDomainsDomainIdDnsRequirementsWithResponse_Call{Call: _e.mock.On("GetApiWebsitesIdDomainsDomainIdDnsRequirementsWithResponse",
		append([]interface{}{ctx, id, domainId}, reqEditors...)...)}
}

func (_c *MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdDomainsDomainIdDnsRequirementsWithResponse_Call) Run(run func(ctx context.Context, id string, domainId string, reqEditors ...client.RequestEditorFn)) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdDomainsDomainIdDnsRequirementsWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdDomainsDomainIdDnsRequirementsWithResponse_Call) Return(_a0 *client.GetApiWebsitesIdDomainsDomainIdDnsRequirementsResponse, _a1 error) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdDomainsDomainIdDnsRequirementsWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdDomainsDomainIdDnsRequirementsWithResponse_Call) RunAndReturn(run func(context.Context, string, string, ...client.RequestEditorFn) (*client.GetApiWebsitesIdDomainsDomainIdDnsRequirementsResponse, error)) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdDomainsDomainIdDnsRequirementsWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiWebsitesIdDomainsWithResponse provides a mock function with given fields: ctx, id, reqEditors
func (_m *MockWebsitesClientWithResponsesInterface) GetApiWebsitesIdDomainsWithResponse(ctx context.Context, id string, reqEditors ...client.RequestEditorFn) (*client.GetApiWebsitesIdDomainsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiWebsitesIdDomainsWithResponse")
	}

	var r0 *client.GetApiWebsitesIdDomainsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) (*client.GetApiWebsitesIdDomainsResponse, error)); ok {
		return rf(ctx, id, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) *client.GetApiWebsitesIdDomainsResponse); ok {
		r0 = rf(ctx, id, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetApiWebsitesIdDomainsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, id, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdDomainsWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiWebsitesIdDomainsWithResponse'
type MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdDomainsWithResponse_Call struct {
	*mock.Call
}

// GetApiWebsitesIdDomainsWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWebsitesClientWithResponsesInterface_Expecter) GetApiWebsitesIdDomainsWithResponse(ctx interface{}, id interface{}, reqEditors ...interface{}) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdDomainsWithResponse_Call {
	return &MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdDomainsWithResponse_Call{Call: _e.mock.On("GetApiWebsitesIdDomainsWithResponse",
		append([]interface{}{ctx, id}, reqEditors...)...)}
}

func (_c *MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdDomainsWithResponse_Call) Run(run func(ctx context.Context, id string, reqEditors ...client.RequestEditorFn)) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdDomainsWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdDomainsWithResponse_Call) Return(_a0 *client.GetApiWebsitesIdDomainsResponse, _a1 error) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdDomainsWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdDomainsWithResponse_Call) RunAndReturn(run func(context.Context, string, ...client.RequestEditorFn) (*client.GetApiWebsitesIdDomainsResponse, error)) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdDomainsWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiWebsitesIdWithResponse provides a mock function with given fields: ctx, id, reqEditors
func (_m *MockWebsitesClientWithResponsesInterface) GetApiWebsitesIdWithResponse(ctx context.Context, id string, reqEditors ...client.RequestEditorFn) (*client.GetApiWebsitesIdResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiWebsitesIdWithResponse")
	}

	var r0 *client.GetApiWebsitesIdResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) (*client.GetApiWebsitesIdResponse, error)); ok {
		return rf(ctx, id, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) *client.GetApiWebsitesIdResponse); ok {
		r0 = rf(ctx, id, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetApiWebsitesIdResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, id, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiWebsitesIdWithResponse'
type MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdWithResponse_Call struct {
	*mock.Call
}

// GetApiWebsitesIdWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWebsitesClientWithResponsesInterface_Expecter) GetApiWebsitesIdWithResponse(ctx interface{}, id interface{}, reqEditors ...interface{}) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdWithResponse_Call {
	return &MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdWithResponse_Call{Call: _e.mock.On("GetApiWebsitesIdWithResponse",
		append([]interface{}{ctx, id}, reqEditors...)...)}
}

func (_c *MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdWithResponse_Call) Run(run func(ctx context.Context, id string, reqEditors ...client.RequestEditorFn)) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdWithResponse_Call) Return(_a0 *client.GetApiWebsitesIdResponse, _a1 error) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdWithResponse_Call) RunAndReturn(run func(context.Context, string, ...client.RequestEditorFn) (*client.GetApiWebsitesIdResponse, error)) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesIdWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiWebsitesWithResponse provides a mock function with given fields: ctx, reqEditors
func (_m *MockWebsitesClientWithResponsesInterface) GetApiWebsitesWithResponse(ctx context.Context, reqEditors ...client.RequestEditorFn) (*client.GetApiWebsitesResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiWebsitesWithResponse")
	}

	var r0 *client.GetApiWebsitesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...client.RequestEditorFn) (*client.GetApiWebsitesResponse, error)); ok {
		return rf(ctx, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...client.RequestEditorFn) *client.GetApiWebsitesResponse); ok {
		r0 = rf(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetApiWebsitesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesClientWithResponsesInterface_GetApiWebsitesWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiWebsitesWithResponse'
type MockWebsitesClientWithResponsesInterface_GetApiWebsitesWithResponse_Call struct {
	*mock.Call
}

// GetApiWebsitesWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWebsitesClientWithResponsesInterface_Expecter) GetApiWebsitesWithResponse(ctx interface{}, reqEditors ...interface{}) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesWithResponse_Call {
	return &MockWebsitesClientWithResponsesInterface_GetApiWebsitesWithResponse_Call{Call: _e.mock.On("GetApiWebsitesWithResponse",
		append([]interface{}{ctx}, reqEditors...)...)}
}

func (_c *MockWebsitesClientWithResponsesInterface_GetApiWebsitesWithResponse_Call) Run(run func(ctx context.Context, reqEditors ...client.RequestEditorFn)) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_GetApiWebsitesWithResponse_Call) Return(_a0 *client.GetApiWebsitesResponse, _a1 error) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_GetApiWebsitesWithResponse_Call) RunAndReturn(run func(context.Context, ...client.RequestEditorFn) (*client.GetApiWebsitesResponse, error)) *MockWebsitesClientWithResponsesInterface_GetApiWebsitesWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetInternalWebsitesDomainStatusWithResponse provides a mock function with given fields: ctx, domain, reqEditors
func (_m *MockWebsitesClientWithResponsesInterface) GetInternalWebsitesDomainStatusWithResponse(ctx context.Context, domain string, reqEditors ...client.RequestEditorFn) (*client.GetInternalWebsitesDomainStatusResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, domain)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetInternalWebsitesDomainStatusWithResponse")
	}

	var r0 *client.GetInternalWebsitesDomainStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) (*client.GetInternalWebsitesDomainStatusResponse, error)); ok {
		return rf(ctx, domain, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) *client.GetInternalWebsitesDomainStatusResponse); ok {
		r0 = rf(ctx, domain, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetInternalWebsitesDomainStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, domain, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesClientWithResponsesInterface_GetInternalWebsitesDomainStatusWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInternalWebsitesDomainStatusWithResponse'
type MockWebsitesClientWithResponsesInterface_GetInternalWebsitesDomainStatusWithResponse_Call struct {
	*mock.Call
}

// GetInternalWebsitesDomainStatusWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWebsitesClientWithResponsesInterface_Expecter) GetInternalWebsitesDomainStatusWithResponse(ctx interface{}, domain interface{}, reqEditors ...interface{}) *MockWebsitesClientWithResponsesInterface_GetInternalWebsitesDomainStatusWithResponse_Call {
	return &MockWebsitesClientWithResponsesInterface_GetInternalWebsitesDomainStatusWithResponse_Call{Call: _e.mock.On("GetInternalWebsitesDomainStatusWithResponse",
		append([]interface{}{ctx, domain}, reqEditors...)...)}
}

func (_c *MockWebsitesClientWithResponsesInterface_GetInternalWebsitesDomainStatusWithResponse_Call) Run(run func(ctx context.Context, domain string, reqEditors ...client.RequestEditorFn)) *MockWebsitesClientWithResponsesInterface_GetInternalWebsitesDomainStatusWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_GetInternalWebsitesDomainStatusWithResponse_Call) Return(_a0 *client.GetInternalWebsitesDomainStatusResponse, _a1 error) *MockWebsitesClientWithResponsesInterface_GetInternalWebsitesDomainStatusWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_GetInternalWebsitesDomainStatusWithResponse_Call) RunAndReturn(run func(context.Context, string, ...client.RequestEditorFn) (*client.GetInternalWebsitesDomainStatusResponse, error)) *MockWebsitesClientWithResponsesInterface_GetInternalWebsitesDomainStatusWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetInternalWebsitesDomainWithResponse provides a mock function with given fields: ctx, domain, reqEditors
func (_m *MockWebsitesClientWithResponsesInterface) GetInternalWebsitesDomainWithResponse(ctx context.Context, domain string, reqEditors ...client.RequestEditorFn) (*client.GetInternalWebsitesDomainResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, domain)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetInternalWebsitesDomainWithResponse")
	}

	var r0 *client.GetInternalWebsitesDomainResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) (*client.GetInternalWebsitesDomainResponse, error)); ok {
		return rf(ctx, domain, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) *client.GetInternalWebsitesDomainResponse); ok {
		r0 = rf(ctx, domain, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetInternalWebsitesDomainResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, domain, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesClientWithResponsesInterface_GetInternalWebsitesDomainWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInternalWebsitesDomainWithResponse'
type MockWebsitesClientWithResponsesInterface_GetInternalWebsitesDomainWithResponse_Call struct {
	*mock.Call
}

// GetInternalWebsitesDomainWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWebsitesClientWithResponsesInterface_Expecter) GetInternalWebsitesDomainWithResponse(ctx interface{}, domain interface{}, reqEditors ...interface{}) *MockWebsitesClientWithResponsesInterface_GetInternalWebsitesDomainWithResponse_Call {
	return &MockWebsitesClientWithResponsesInterface_GetInternalWebsitesDomainWithResponse_Call{Call: _e.mock.On("GetInternalWebsitesDomainWithResponse",
		append([]interface{}{ctx, domain}, reqEditors...)...)}
}

func (_c *MockWebsitesClientWithResponsesInterface_GetInternalWebsitesDomainWithResponse_Call) Run(run func(ctx context.Context, domain string, reqEditors ...client.RequestEditorFn)) *MockWebsitesClientWithResponsesInterface_GetInternalWebsitesDomainWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_GetInternalWebsitesDomainWithResponse_Call) Return(_a0 *client.GetInternalWebsitesDomainResponse, _a1 error) *MockWebsitesClientWithResponsesInterface_GetInternalWebsitesDomainWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_GetInternalWebsitesDomainWithResponse_Call) RunAndReturn(run func(context.Context, string, ...client.RequestEditorFn) (*client.GetInternalWebsitesDomainResponse, error)) *MockWebsitesClientWithResponsesInterface_GetInternalWebsitesDomainWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostApiWebsitesIdDomainsDomainIdVerifyWithResponse provides a mock function with given fields: ctx, id, domainId, reqEditors
func (_m *MockWebsitesClientWithResponsesInterface) PostApiWebsitesIdDomainsDomainIdVerifyWithResponse(ctx context.Context, id string, domainId string, reqEditors ...client.RequestEditorFn) (*client.PostApiWebsitesIdDomainsDomainIdVerifyResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id, domainId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostApiWebsitesIdDomainsDomainIdVerifyWithResponse")
	}

	var r0 *client.PostApiWebsitesIdDomainsDomainIdVerifyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...client.RequestEditorFn) (*client.PostApiWebsitesIdDomainsDomainIdVerifyResponse, error)); ok {
		return rf(ctx, id, domainId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...client.RequestEditorFn) *client.PostApiWebsitesIdDomainsDomainIdVerifyResponse); ok {
		r0 = rf(ctx, id, domainId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PostApiWebsitesIdDomainsDomainIdVerifyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, id, domainId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdDomainsDomainIdVerifyWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostApiWebsitesIdDomainsDomainIdVerifyWithResponse'
type MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdDomainsDomainIdVerifyWithResponse_Call struct {
	*mock.Call
}

// PostApiWebsitesIdDomainsDomainIdVerifyWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - domainId string
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWebsitesClientWithResponsesInterface_Expecter) PostApiWebsitesIdDomainsDomainIdVerifyWithResponse(ctx interface{}, id interface{}, domainId interface{}, reqEditors ...interface{}) *MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdDomainsDomainIdVerifyWithResponse_Call {
	return &MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdDomainsDomainIdVerifyWithResponse_Call{Call: _e.mock.On("PostApiWebsitesIdDomainsDomainIdVerifyWithResponse",
		append([]interface{}{ctx, id, domainId}, reqEditors...)...)}
}

func (_c *MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdDomainsDomainIdVerifyWithResponse_Call) Run(run func(ctx context.Context, id string, domainId string, reqEditors ...client.RequestEditorFn)) *MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdDomainsDomainIdVerifyWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdDomainsDomainIdVerifyWithResponse_Call) Return(_a0 *client.PostApiWebsitesIdDomainsDomainIdVerifyResponse, _a1 error) *MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdDomainsDomainIdVerifyWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdDomainsDomainIdVerifyWithResponse_Call) RunAndReturn(run func(context.Context, string, string, ...client.RequestEditorFn) (*client.PostApiWebsitesIdDomainsDomainIdVerifyResponse, error)) *MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdDomainsDomainIdVerifyWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostApiWebsitesIdDomainsWithResponse provides a mock function with given fields: ctx, id, body, reqEditors
func (_m *MockWebsitesClientWithResponsesInterface) PostApiWebsitesIdDomainsWithResponse(ctx context.Context, id string, body client.DomainRequest, reqEditors ...client.RequestEditorFn) (*client.PostApiWebsitesIdDomainsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostApiWebsitesIdDomainsWithResponse")
	}

	var r0 *client.PostApiWebsitesIdDomainsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.DomainRequest, ...client.RequestEditorFn) (*client.PostApiWebsitesIdDomainsResponse, error)); ok {
		return rf(ctx, id, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, client.DomainRequest, ...client.RequestEditorFn) *client.PostApiWebsitesIdDomainsResponse); ok {
		r0 = rf(ctx, id, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PostApiWebsitesIdDomainsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, client.DomainRequest, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, id, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdDomainsWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostApiWebsitesIdDomainsWithResponse'
type MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdDomainsWithResponse_Call struct {
	*mock.Call
}

// PostApiWebsitesIdDomainsWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - body client.DomainRequest
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWebsitesClientWithResponsesInterface_Expecter) PostApiWebsitesIdDomainsWithResponse(ctx interface{}, id interface{}, body interface{}, reqEditors ...interface{}) *MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdDomainsWithResponse_Call {
	return &MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdDomainsWithResponse_Call{Call: _e.mock.On("PostApiWebsitesIdDomainsWithResponse",
		append([]interface{}{ctx, id, body}, reqEditors...)...)}
}

func (_c *MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdDomainsWithResponse_Call) Run(run func(ctx context.Context, id string, body client.DomainRequest, reqEditors ...client.RequestEditorFn)) *MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdDomainsWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(client.DomainRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdDomainsWithResponse_Call) Return(_a0 *client.PostApiWebsitesIdDomainsResponse, _a1 error) *MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdDomainsWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdDomainsWithResponse_Call) RunAndReturn(run func(context.Context, string, client.DomainRequest, ...client.RequestEditorFn) (*client.PostApiWebsitesIdDomainsResponse, error)) *MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdDomainsWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostApiWebsitesIdValidateWithResponse provides a mock function with given fields: ctx, id, reqEditors
func (_m *MockWebsitesClientWithResponsesInterface) PostApiWebsitesIdValidateWithResponse(ctx context.Context, id string, reqEditors ...client.RequestEditorFn) (*client.PostApiWebsitesIdValidateResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostApiWebsitesIdValidateWithResponse")
	}

	var r0 *client.PostApiWebsitesIdValidateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) (*client.PostApiWebsitesIdValidateResponse, error)); ok {
		return rf(ctx, id, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) *client.PostApiWebsitesIdValidateResponse); ok {
		r0 = rf(ctx, id, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PostApiWebsitesIdValidateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, id, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdValidateWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostApiWebsitesIdValidateWithResponse'
type MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdValidateWithResponse_Call struct {
	*mock.Call
}

// PostApiWebsitesIdValidateWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWebsitesClientWithResponsesInterface_Expecter) PostApiWebsitesIdValidateWithResponse(ctx interface{}, id interface{}, reqEditors ...interface{}) *MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdValidateWithResponse_Call {
	return &MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdValidateWithResponse_Call{Call: _e.mock.On("PostApiWebsitesIdValidateWithResponse",
		append([]interface{}{ctx, id}, reqEditors...)...)}
}

func (_c *MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdValidateWithResponse_Call) Run(run func(ctx context.Context, id string, reqEditors ...client.RequestEditorFn)) *MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdValidateWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdValidateWithResponse_Call) Return(_a0 *client.PostApiWebsitesIdValidateResponse, _a1 error) *MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdValidateWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdValidateWithResponse_Call) RunAndReturn(run func(context.Context, string, ...client.RequestEditorFn) (*client.PostApiWebsitesIdValidateResponse, error)) *MockWebsitesClientWithResponsesInterface_PostApiWebsitesIdValidateWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostApiWebsitesWithResponse provides a mock function with given fields: ctx, body, reqEditors
func (_m *MockWebsitesClientWithResponsesInterface) PostApiWebsitesWithResponse(ctx context.Context, body client.WebsiteRequest, reqEditors ...client.RequestEditorFn) (*client.PostApiWebsitesResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostApiWebsitesWithResponse")
	}

	var r0 *client.PostApiWebsitesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.WebsiteRequest, ...client.RequestEditorFn) (*client.PostApiWebsitesResponse, error)); ok {
		return rf(ctx, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.WebsiteRequest, ...client.RequestEditorFn) *client.PostApiWebsitesResponse); ok {
		r0 = rf(ctx, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PostApiWebsitesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.WebsiteRequest, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesClientWithResponsesInterface_PostApiWebsitesWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostApiWebsitesWithResponse'
type MockWebsitesClientWithResponsesInterface_PostApiWebsitesWithResponse_Call struct {
	*mock.Call
}

// PostApiWebsitesWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - body client.WebsiteRequest
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWebsitesClientWithResponsesInterface_Expecter) PostApiWebsitesWithResponse(ctx interface{}, body interface{}, reqEditors ...interface{}) *MockWebsitesClientWithResponsesInterface_PostApiWebsitesWithResponse_Call {
	return &MockWebsitesClientWithResponsesInterface_PostApiWebsitesWithResponse_Call{Call: _e.mock.On("PostApiWebsitesWithResponse",
		append([]interface{}{ctx, body}, reqEditors...)...)}
}

func (_c *MockWebsitesClientWithResponsesInterface_PostApiWebsitesWithResponse_Call) Run(run func(ctx context.Context, body client.WebsiteRequest, reqEditors ...client.RequestEditorFn)) *MockWebsitesClientWithResponsesInterface_PostApiWebsitesWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(client.WebsiteRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_PostApiWebsitesWithResponse_Call) Return(_a0 *client.PostApiWebsitesResponse, _a1 error) *MockWebsitesClientWithResponsesInterface_PostApiWebsitesWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_PostApiWebsitesWithResponse_Call) RunAndReturn(run func(context.Context, client.WebsiteRequest, ...client.RequestEditorFn) (*client.PostApiWebsitesResponse, error)) *MockWebsitesClientWithResponsesInterface_PostApiWebsitesWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostInternalWebsitesDomainSslStatusWithResponse provides a mock function with given fields: ctx, domain, body, reqEditors
func (_m *MockWebsitesClientWithResponsesInterface) PostInternalWebsitesDomainSslStatusWithResponse(ctx context.Context, domain string, body client.SSLStatusUpdateRequest, reqEditors ...client.RequestEditorFn) (*client.PostInternalWebsitesDomainSslStatusResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, domain, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostInternalWebsitesDomainSslStatusWithResponse")
	}

	var r0 *client.PostInternalWebsitesDomainSslStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.SSLStatusUpdateRequest, ...client.RequestEditorFn) (*client.PostInternalWebsitesDomainSslStatusResponse, error)); ok {
		return rf(ctx, domain, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, client.SSLStatusUpdateRequest, ...client.RequestEditorFn) *client.PostInternalWebsitesDomainSslStatusResponse); ok {
		r0 = rf(ctx, domain, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PostInternalWebsitesDomainSslStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, client.SSLStatusUpdateRequest, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, domain, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesClientWithResponsesInterface_PostInternalWebsitesDomainSslStatusWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostInternalWebsitesDomainSslStatusWithResponse'
type MockWebsitesClientWithResponsesInterface_PostInternalWebsitesDomainSslStatusWithResponse_Call struct {
	*mock.Call
}

// PostInternalWebsitesDomainSslStatusWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - body client.SSLStatusUpdateRequest
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWebsitesClientWithResponsesInterface_Expecter) PostInternalWebsitesDomainSslStatusWithResponse(ctx interface{}, domain interface{}, body interface{}, reqEditors ...interface{}) *MockWebsitesClientWithResponsesInterface_PostInternalWebsitesDomainSslStatusWithResponse_Call {
	return &MockWebsitesClientWithResponsesInterface_PostInternalWebsitesDomainSslStatusWithResponse_Call{Call: _e.mock.On("PostInternalWebsitesDomainSslStatusWithResponse",
		append([]interface{}{ctx, domain, body}, reqEditors...)...)}
}

func (_c *MockWebsitesClientWithResponsesInterface_PostInternalWebsitesDomainSslStatusWithResponse_Call) Run(run func(ctx context.Context, domain string, body client.SSLStatusUpdateRequest, reqEditors ...client.RequestEditorFn)) *MockWebsitesClientWithResponsesInterface_PostInternalWebsitesDomainSslStatusWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(client.SSLStatusUpdateRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_PostInternalWebsitesDomainSslStatusWithResponse_Call) Return(_a0 *client.PostInternalWebsitesDomainSslStatusResponse, _a1 error) *MockWebsitesClientWithResponsesInterface_PostInternalWebsitesDomainSslStatusWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_PostInternalWebsitesDomainSslStatusWithResponse_Call) RunAndReturn(run func(context.Context, string, client.SSLStatusUpdateRequest, ...client.RequestEditorFn) (*client.PostInternalWebsitesDomainSslStatusResponse, error)) *MockWebsitesClientWithResponsesInterface_PostInternalWebsitesDomainSslStatusWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PutApiWebsitesIdWithResponse provides a mock function with given fields: ctx, id, body, reqEditors
func (_m *MockWebsitesClientWithResponsesInterface) PutApiWebsitesIdWithResponse(ctx context.Context, id string, body client.WebsiteUpdateRequest, reqEditors ...client.RequestEditorFn) (*client.PutApiWebsitesIdResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PutApiWebsitesIdWithResponse")
	}

	var r0 *client.PutApiWebsitesIdResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.WebsiteUpdateRequest, ...client.RequestEditorFn) (*client.PutApiWebsitesIdResponse, error)); ok {
		return rf(ctx, id, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, client.WebsiteUpdateRequest, ...client.RequestEditorFn) *client.PutApiWebsitesIdResponse); ok {
		r0 = rf(ctx, id, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PutApiWebsitesIdResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, client.WebsiteUpdateRequest, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, id, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebsitesClientWithResponsesInterface_PutApiWebsitesIdWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutApiWebsitesIdWithResponse'
type MockWebsitesClientWithResponsesInterface_PutApiWebsitesIdWithResponse_Call struct {
	*mock.Call
}

// PutApiWebsitesIdWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - body client.WebsiteUpdateRequest
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWebsitesClientWithResponsesInterface_Expecter) PutApiWebsitesIdWithResponse(ctx interface{}, id interface{}, body interface{}, reqEditors ...interface{}) *MockWebsitesClientWithResponsesInterface_PutApiWebsitesIdWithResponse_Call {
	return &MockWebsitesClientWithResponsesInterface_PutApiWebsitesIdWithResponse_Call{Call: _e.mock.On("PutApiWebsitesIdWithResponse",
		append([]interface{}{ctx, id, body}, reqEditors...)...)}
}

func (_c *MockWebsitesClientWithResponsesInterface_PutApiWebsitesIdWithResponse_Call) Run(run func(ctx context.Context, id string, body client.WebsiteUpdateRequest, reqEditors ...client.RequestEditorFn)) *MockWebsitesClientWithResponsesInterface_PutApiWebsitesIdWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(client.WebsiteUpdateRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_PutApiWebsitesIdWithResponse_Call) Return(_a0 *client.PutApiWebsitesIdResponse, _a1 error) *MockWebsitesClientWithResponsesInterface_PutApiWebsitesIdWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebsitesClientWithResponsesInterface_PutApiWebsitesIdWithResponse_Call) RunAndReturn(run func(context.Context, string, client.WebsiteUpdateRequest, ...client.RequestEditorFn) (*client.PutApiWebsitesIdResponse, error)) *MockWebsitesClientWithResponsesInterface_PutApiWebsitesIdWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebsitesClientWithResponsesInterface creates a new instance of MockWebsitesClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebsitesClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebsitesClientWithResponsesInterface {
	mock := &MockWebsitesClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
