// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/ipfs-sdk/internal/client"
)

// NewMockWorkspacesClientWithResponsesInterface creates a new instance of MockWorkspacesClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkspacesClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkspacesClientWithResponsesInterface {
	mock := &MockWorkspacesClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkspacesClientWithResponsesInterface is an autogenerated mock type for the WorkspacesClientWithResponsesInterface type
type MockWorkspacesClientWithResponsesInterface struct {
	mock.Mock
}

type MockWorkspacesClientWithResponsesInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkspacesClientWithResponsesInterface) EXPECT() *MockWorkspacesClientWithResponsesInterface_Expecter {
	return &MockWorkspacesClientWithResponsesInterface_Expecter{mock: &_m.Mock}
}

// DeleteApiWorkspacesIdWithResponse provides a mock function for the type MockWorkspacesClientWithResponsesInterface
func (_mock *MockWorkspacesClientWithResponsesInterface) DeleteApiWorkspacesIdWithResponse(ctx context.Context, id string, reqEditors ...client.RequestEditorFn) (*client.DeleteApiWorkspacesIdResponse, error) {
	// client.RequestEditorFn
	_va := make([]any, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteApiWorkspacesIdWithResponse")
	}

	var r0 *client.DeleteApiWorkspacesIdResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) (*client.DeleteApiWorkspacesIdResponse, error)); ok {
		return returnFunc(ctx, id, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) *client.DeleteApiWorkspacesIdResponse); ok {
		r0 = returnFunc(ctx, id, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.DeleteApiWorkspacesIdResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...client.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, id, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspacesClientWithResponsesInterface_DeleteApiWorkspacesIdWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteApiWorkspacesIdWithResponse'
type MockWorkspacesClientWithResponsesInterface_DeleteApiWorkspacesIdWithResponse_Call struct {
	*mock.Call
}

// DeleteApiWorkspacesIdWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWorkspacesClientWithResponsesInterface_Expecter) DeleteApiWorkspacesIdWithResponse(ctx any, id any, reqEditors ...any) *MockWorkspacesClientWithResponsesInterface_DeleteApiWorkspacesIdWithResponse_Call {
	return &MockWorkspacesClientWithResponsesInterface_DeleteApiWorkspacesIdWithResponse_Call{Call: _e.mock.On("DeleteApiWorkspacesIdWithResponse",
		append([]any{ctx, id}, reqEditors...)...)}
}

func (_c *MockWorkspacesClientWithResponsesInterface_DeleteApiWorkspacesIdWithResponse_Call) Run(run func(ctx context.Context, id string, reqEditors ...client.RequestEditorFn)) *MockWorkspacesClientWithResponsesInterface_DeleteApiWorkspacesIdWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []client.RequestEditorFn
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockWorkspacesClientWithResponsesInterface_DeleteApiWorkspacesIdWithResponse_Call) Return(deleteApiWorkspacesIdResponse *client.DeleteApiWorkspacesIdResponse, err error) *MockWorkspacesClientWithResponsesInterface_DeleteApiWorkspacesIdWithResponse_Call {
	_c.Call.Return(deleteApiWorkspacesIdResponse, err)
	return _c
}

func (_c *MockWorkspacesClientWithResponsesInterface_DeleteApiWorkspacesIdWithResponse_Call) RunAndReturn(run func(ctx context.Context, id string, reqEditors ...client.RequestEditorFn) (*client.DeleteApiWorkspacesIdResponse, error)) *MockWorkspacesClientWithResponsesInterface_DeleteApiWorkspacesIdWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiWorkspacesIdAccessWithResponse provides a mock function for the type MockWorkspacesClientWithResponsesInterface
func (_mock *MockWorkspacesClientWithResponsesInterface) GetApiWorkspacesIdAccessWithResponse(ctx context.Context, id string, params *client.GetApiWorkspacesIdAccessParams, reqEditors ...client.RequestEditorFn) (*client.GetApiWorkspacesIdAccessResponse, error) {
	// client.RequestEditorFn
	_va := make([]any, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, id, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiWorkspacesIdAccessWithResponse")
	}

	var r0 *client.GetApiWorkspacesIdAccessResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *client.GetApiWorkspacesIdAccessParams, ...client.RequestEditorFn) (*client.GetApiWorkspacesIdAccessResponse, error)); ok {
		return returnFunc(ctx, id, params, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *client.GetApiWorkspacesIdAccessParams, ...client.RequestEditorFn) *client.GetApiWorkspacesIdAccessResponse); ok {
		r0 = returnFunc(ctx, id, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetApiWorkspacesIdAccessResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *client.GetApiWorkspacesIdAccessParams, ...client.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, id, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesIdAccessWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiWorkspacesIdAccessWithResponse'
type MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesIdAccessWithResponse_Call struct {
	*mock.Call
}

// GetApiWorkspacesIdAccessWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - params *client.GetApiWorkspacesIdAccessParams
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWorkspacesClientWithResponsesInterface_Expecter) GetApiWorkspacesIdAccessWithResponse(ctx any, id any, params any, reqEditors ...any) *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesIdAccessWithResponse_Call {
	return &MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesIdAccessWithResponse_Call{Call: _e.mock.On("GetApiWorkspacesIdAccessWithResponse",
		append([]any{ctx, id, params}, reqEditors...)...)}
}

func (_c *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesIdAccessWithResponse_Call) Run(run func(ctx context.Context, id string, params *client.GetApiWorkspacesIdAccessParams, reqEditors ...client.RequestEditorFn)) *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesIdAccessWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *client.GetApiWorkspacesIdAccessParams
		if args[2] != nil {
			arg2 = args[2].(*client.GetApiWorkspacesIdAccessParams)
		}
		var arg3 []client.RequestEditorFn
		variadicArgs := make([]client.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesIdAccessWithResponse_Call) Return(getApiWorkspacesIdAccessResponse *client.GetApiWorkspacesIdAccessResponse, err error) *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesIdAccessWithResponse_Call {
	_c.Call.Return(getApiWorkspacesIdAccessResponse, err)
	return _c
}

func (_c *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesIdAccessWithResponse_Call) RunAndReturn(run func(ctx context.Context, id string, params *client.GetApiWorkspacesIdAccessParams, reqEditors ...client.RequestEditorFn) (*client.GetApiWorkspacesIdAccessResponse, error)) *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesIdAccessWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiWorkspacesIdWithResponse provides a mock function for the type MockWorkspacesClientWithResponsesInterface
func (_mock *MockWorkspacesClientWithResponsesInterface) GetApiWorkspacesIdWithResponse(ctx context.Context, id string, reqEditors ...client.RequestEditorFn) (*client.GetApiWorkspacesIdResponse, error) {
	// client.RequestEditorFn
	_va := make([]any, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiWorkspacesIdWithResponse")
	}

	var r0 *client.GetApiWorkspacesIdResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) (*client.GetApiWorkspacesIdResponse, error)); ok {
		return returnFunc(ctx, id, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) *client.GetApiWorkspacesIdResponse); ok {
		r0 = returnFunc(ctx, id, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetApiWorkspacesIdResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...client.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, id, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesIdWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiWorkspacesIdWithResponse'
type MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesIdWithResponse_Call struct {
	*mock.Call
}

// GetApiWorkspacesIdWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWorkspacesClientWithResponsesInterface_Expecter) GetApiWorkspacesIdWithResponse(ctx any, id any, reqEditors ...any) *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesIdWithResponse_Call {
	return &MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesIdWithResponse_Call{Call: _e.mock.On("GetApiWorkspacesIdWithResponse",
		append([]any{ctx, id}, reqEditors...)...)}
}

func (_c *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesIdWithResponse_Call) Run(run func(ctx context.Context, id string, reqEditors ...client.RequestEditorFn)) *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesIdWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []client.RequestEditorFn
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesIdWithResponse_Call) Return(getApiWorkspacesIdResponse *client.GetApiWorkspacesIdResponse, err error) *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesIdWithResponse_Call {
	_c.Call.Return(getApiWorkspacesIdResponse, err)
	return _c
}

func (_c *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesIdWithResponse_Call) RunAndReturn(run func(ctx context.Context, id string, reqEditors ...client.RequestEditorFn) (*client.GetApiWorkspacesIdResponse, error)) *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesIdWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiWorkspacesResolveWithResponse provides a mock function for the type MockWorkspacesClientWithResponsesInterface
func (_mock *MockWorkspacesClientWithResponsesInterface) GetApiWorkspacesResolveWithResponse(ctx context.Context, params *client.GetApiWorkspacesResolveParams, reqEditors ...client.RequestEditorFn) (*client.GetApiWorkspacesResolveResponse, error) {
	// client.RequestEditorFn
	_va := make([]any, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiWorkspacesResolveWithResponse")
	}

	var r0 *client.GetApiWorkspacesResolveResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *client.GetApiWorkspacesResolveParams, ...client.RequestEditorFn) (*client.GetApiWorkspacesResolveResponse, error)); ok {
		return returnFunc(ctx, params, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *client.GetApiWorkspacesResolveParams, ...client.RequestEditorFn) *client.GetApiWorkspacesResolveResponse); ok {
		r0 = returnFunc(ctx, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetApiWorkspacesResolveResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *client.GetApiWorkspacesResolveParams, ...client.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesResolveWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiWorkspacesResolveWithResponse'
type MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesResolveWithResponse_Call struct {
	*mock.Call
}

// GetApiWorkspacesResolveWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - params *client.GetApiWorkspacesResolveParams
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWorkspacesClientWithResponsesInterface_Expecter) GetApiWorkspacesResolveWithResponse(ctx any, params any, reqEditors ...any) *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesResolveWithResponse_Call {
	return &MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesResolveWithResponse_Call{Call: _e.mock.On("GetApiWorkspacesResolveWithResponse",
		append([]any{ctx, params}, reqEditors...)...)}
}

func (_c *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesResolveWithResponse_Call) Run(run func(ctx context.Context, params *client.GetApiWorkspacesResolveParams, reqEditors ...client.RequestEditorFn)) *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesResolveWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *client.GetApiWorkspacesResolveParams
		if args[1] != nil {
			arg1 = args[1].(*client.GetApiWorkspacesResolveParams)
		}
		var arg2 []client.RequestEditorFn
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesResolveWithResponse_Call) Return(getApiWorkspacesResolveResponse *client.GetApiWorkspacesResolveResponse, err error) *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesResolveWithResponse_Call {
	_c.Call.Return(getApiWorkspacesResolveResponse, err)
	return _c
}

func (_c *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesResolveWithResponse_Call) RunAndReturn(run func(ctx context.Context, params *client.GetApiWorkspacesResolveParams, reqEditors ...client.RequestEditorFn) (*client.GetApiWorkspacesResolveResponse, error)) *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesResolveWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiWorkspacesWithResponse provides a mock function for the type MockWorkspacesClientWithResponsesInterface
func (_mock *MockWorkspacesClientWithResponsesInterface) GetApiWorkspacesWithResponse(ctx context.Context, reqEditors ...client.RequestEditorFn) (*client.GetApiWorkspacesResponse, error) {
	// client.RequestEditorFn
	_va := make([]any, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiWorkspacesWithResponse")
	}

	var r0 *client.GetApiWorkspacesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...client.RequestEditorFn) (*client.GetApiWorkspacesResponse, error)); ok {
		return returnFunc(ctx, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...client.RequestEditorFn) *client.GetApiWorkspacesResponse); ok {
		r0 = returnFunc(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetApiWorkspacesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...client.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiWorkspacesWithResponse'
type MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesWithResponse_Call struct {
	*mock.Call
}

// GetApiWorkspacesWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWorkspacesClientWithResponsesInterface_Expecter) GetApiWorkspacesWithResponse(ctx any, reqEditors ...any) *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesWithResponse_Call {
	return &MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesWithResponse_Call{Call: _e.mock.On("GetApiWorkspacesWithResponse",
		append([]any{ctx}, reqEditors...)...)}
}

func (_c *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesWithResponse_Call) Run(run func(ctx context.Context, reqEditors ...client.RequestEditorFn)) *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []client.RequestEditorFn
		variadicArgs := make([]client.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesWithResponse_Call) Return(getApiWorkspacesResponse *client.GetApiWorkspacesResponse, err error) *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesWithResponse_Call {
	_c.Call.Return(getApiWorkspacesResponse, err)
	return _c
}

func (_c *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesWithResponse_Call) RunAndReturn(run func(ctx context.Context, reqEditors ...client.RequestEditorFn) (*client.GetApiWorkspacesResponse, error)) *MockWorkspacesClientWithResponsesInterface_GetApiWorkspacesWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostApiWorkspacesIdAttachWithResponse provides a mock function for the type MockWorkspacesClientWithResponsesInterface
func (_mock *MockWorkspacesClientWithResponsesInterface) PostApiWorkspacesIdAttachWithResponse(ctx context.Context, id string, body client.WorkspaceRequest, reqEditors ...client.RequestEditorFn) (*client.PostApiWorkspacesIdAttachResponse, error) {
	// client.RequestEditorFn
	_va := make([]any, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, id, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostApiWorkspacesIdAttachWithResponse")
	}

	var r0 *client.PostApiWorkspacesIdAttachResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.WorkspaceRequest, ...client.RequestEditorFn) (*client.PostApiWorkspacesIdAttachResponse, error)); ok {
		return returnFunc(ctx, id, body, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.WorkspaceRequest, ...client.RequestEditorFn) *client.PostApiWorkspacesIdAttachResponse); ok {
		r0 = returnFunc(ctx, id, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PostApiWorkspacesIdAttachResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.WorkspaceRequest, ...client.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, id, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdAttachWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostApiWorkspacesIdAttachWithResponse'
type MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdAttachWithResponse_Call struct {
	*mock.Call
}

// PostApiWorkspacesIdAttachWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - body client.WorkspaceRequest
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWorkspacesClientWithResponsesInterface_Expecter) PostApiWorkspacesIdAttachWithResponse(ctx any, id any, body any, reqEditors ...any) *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdAttachWithResponse_Call {
	return &MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdAttachWithResponse_Call{Call: _e.mock.On("PostApiWorkspacesIdAttachWithResponse",
		append([]any{ctx, id, body}, reqEditors...)...)}
}

func (_c *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdAttachWithResponse_Call) Run(run func(ctx context.Context, id string, body client.WorkspaceRequest, reqEditors ...client.RequestEditorFn)) *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdAttachWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.WorkspaceRequest
		if args[2] != nil {
			arg2 = args[2].(client.WorkspaceRequest)
		}
		var arg3 []client.RequestEditorFn
		variadicArgs := make([]client.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdAttachWithResponse_Call) Return(postApiWorkspacesIdAttachResponse *client.PostApiWorkspacesIdAttachResponse, err error) *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdAttachWithResponse_Call {
	_c.Call.Return(postApiWorkspacesIdAttachResponse, err)
	return _c
}

func (_c *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdAttachWithResponse_Call) RunAndReturn(run func(ctx context.Context, id string, body client.WorkspaceRequest, reqEditors ...client.RequestEditorFn) (*client.PostApiWorkspacesIdAttachResponse, error)) *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdAttachWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostApiWorkspacesIdResumeWithResponse provides a mock function for the type MockWorkspacesClientWithResponsesInterface
func (_mock *MockWorkspacesClientWithResponsesInterface) PostApiWorkspacesIdResumeWithResponse(ctx context.Context, id string, reqEditors ...client.RequestEditorFn) (*client.PostApiWorkspacesIdResumeResponse, error) {
	// client.RequestEditorFn
	_va := make([]any, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostApiWorkspacesIdResumeWithResponse")
	}

	var r0 *client.PostApiWorkspacesIdResumeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) (*client.PostApiWorkspacesIdResumeResponse, error)); ok {
		return returnFunc(ctx, id, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) *client.PostApiWorkspacesIdResumeResponse); ok {
		r0 = returnFunc(ctx, id, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PostApiWorkspacesIdResumeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...client.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, id, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdResumeWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostApiWorkspacesIdResumeWithResponse'
type MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdResumeWithResponse_Call struct {
	*mock.Call
}

// PostApiWorkspacesIdResumeWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWorkspacesClientWithResponsesInterface_Expecter) PostApiWorkspacesIdResumeWithResponse(ctx any, id any, reqEditors ...any) *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdResumeWithResponse_Call {
	return &MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdResumeWithResponse_Call{Call: _e.mock.On("PostApiWorkspacesIdResumeWithResponse",
		append([]any{ctx, id}, reqEditors...)...)}
}

func (_c *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdResumeWithResponse_Call) Run(run func(ctx context.Context, id string, reqEditors ...client.RequestEditorFn)) *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdResumeWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []client.RequestEditorFn
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdResumeWithResponse_Call) Return(postApiWorkspacesIdResumeResponse *client.PostApiWorkspacesIdResumeResponse, err error) *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdResumeWithResponse_Call {
	_c.Call.Return(postApiWorkspacesIdResumeResponse, err)
	return _c
}

func (_c *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdResumeWithResponse_Call) RunAndReturn(run func(ctx context.Context, id string, reqEditors ...client.RequestEditorFn) (*client.PostApiWorkspacesIdResumeResponse, error)) *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdResumeWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostApiWorkspacesIdSuspendWithResponse provides a mock function for the type MockWorkspacesClientWithResponsesInterface
func (_mock *MockWorkspacesClientWithResponsesInterface) PostApiWorkspacesIdSuspendWithResponse(ctx context.Context, id string, reqEditors ...client.RequestEditorFn) (*client.PostApiWorkspacesIdSuspendResponse, error) {
	// client.RequestEditorFn
	_va := make([]any, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostApiWorkspacesIdSuspendWithResponse")
	}

	var r0 *client.PostApiWorkspacesIdSuspendResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) (*client.PostApiWorkspacesIdSuspendResponse, error)); ok {
		return returnFunc(ctx, id, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) *client.PostApiWorkspacesIdSuspendResponse); ok {
		r0 = returnFunc(ctx, id, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PostApiWorkspacesIdSuspendResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...client.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, id, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdSuspendWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostApiWorkspacesIdSuspendWithResponse'
type MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdSuspendWithResponse_Call struct {
	*mock.Call
}

// PostApiWorkspacesIdSuspendWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWorkspacesClientWithResponsesInterface_Expecter) PostApiWorkspacesIdSuspendWithResponse(ctx any, id any, reqEditors ...any) *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdSuspendWithResponse_Call {
	return &MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdSuspendWithResponse_Call{Call: _e.mock.On("PostApiWorkspacesIdSuspendWithResponse",
		append([]any{ctx, id}, reqEditors...)...)}
}

func (_c *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdSuspendWithResponse_Call) Run(run func(ctx context.Context, id string, reqEditors ...client.RequestEditorFn)) *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdSuspendWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []client.RequestEditorFn
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdSuspendWithResponse_Call) Return(postApiWorkspacesIdSuspendResponse *client.PostApiWorkspacesIdSuspendResponse, err error) *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdSuspendWithResponse_Call {
	_c.Call.Return(postApiWorkspacesIdSuspendResponse, err)
	return _c
}

func (_c *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdSuspendWithResponse_Call) RunAndReturn(run func(ctx context.Context, id string, reqEditors ...client.RequestEditorFn) (*client.PostApiWorkspacesIdSuspendResponse, error)) *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesIdSuspendWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostApiWorkspacesWithResponse provides a mock function for the type MockWorkspacesClientWithResponsesInterface
func (_mock *MockWorkspacesClientWithResponsesInterface) PostApiWorkspacesWithResponse(ctx context.Context, body client.WorkspaceRequest, reqEditors ...client.RequestEditorFn) (*client.PostApiWorkspacesResponse, error) {
	// client.RequestEditorFn
	_va := make([]any, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostApiWorkspacesWithResponse")
	}

	var r0 *client.PostApiWorkspacesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.WorkspaceRequest, ...client.RequestEditorFn) (*client.PostApiWorkspacesResponse, error)); ok {
		return returnFunc(ctx, body, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.WorkspaceRequest, ...client.RequestEditorFn) *client.PostApiWorkspacesResponse); ok {
		r0 = returnFunc(ctx, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PostApiWorkspacesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.WorkspaceRequest, ...client.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostApiWorkspacesWithResponse'
type MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesWithResponse_Call struct {
	*mock.Call
}

// PostApiWorkspacesWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - body client.WorkspaceRequest
//   - reqEditors ...client.RequestEditorFn
func (_e *MockWorkspacesClientWithResponsesInterface_Expecter) PostApiWorkspacesWithResponse(ctx any, body any, reqEditors ...any) *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesWithResponse_Call {
	return &MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesWithResponse_Call{Call: _e.mock.On("PostApiWorkspacesWithResponse",
		append([]any{ctx, body}, reqEditors...)...)}
}

func (_c *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesWithResponse_Call) Run(run func(ctx context.Context, body client.WorkspaceRequest, reqEditors ...client.RequestEditorFn)) *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.WorkspaceRequest
		if args[1] != nil {
			arg1 = args[1].(client.WorkspaceRequest)
		}
		var arg2 []client.RequestEditorFn
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesWithResponse_Call) Return(postApiWorkspacesResponse *client.PostApiWorkspacesResponse, err error) *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesWithResponse_Call {
	_c.Call.Return(postApiWorkspacesResponse, err)
	return _c
}

func (_c *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesWithResponse_Call) RunAndReturn(run func(ctx context.Context, body client.WorkspaceRequest, reqEditors ...client.RequestEditorFn) (*client.PostApiWorkspacesResponse, error)) *MockWorkspacesClientWithResponsesInterface_PostApiWorkspacesWithResponse_Call {
	_c.Call.Return(run)
	return _c
}
